### ISSUE TITLE
Add instructions on creating a project and setting default region

### ISSUE THREAD

**Issue by elsonrodriguez** [kelseyhightower/kubernetes-the-hard-way#10]

**Comment by elsonrodriguez** [comment]
gcloud  config set compute/region us-central1

**Comment by kelseyhightower** [comment]
Let's avoid putting to much Google specific documentation in this repo. I want people to focus on the basic usage of VMs and networking which could translate into any environment.

**Comment by elsonrodriguez** [comment]
I need to verify, but I think unless you set the region, some of the magic that is used to set variables fails (since it sets the variable from standard output)
