### ISSUE TITLE
kube-dns behaves strangely; only responds to DNS queries from one worker

### ISSUE THREAD

**Issue by KamranAzeem** [kelseyhightower/kubernetes-the-hard-way#104]
Thanks for great tutorial again! 

We have setup few kubernetes clusters using your guide, and there is one thing which is really a pain in the neck. The DNS add-on (kubedns/skydns).  In past two lab setups, the DNS addons only seem to work from one worker node. We tried this on kvm/libvirt, AWS, and most recently on VirtualBox. On all instances the base OS has been Fedora 24. Here is little about the setup:

* 3 x etcd nodes
* 2 x controller nodes
* 2 x worker nodes

SELinux is disabled on all nodes. Firewalld package is removed from all nodes. Routes are added to default router, and  pods from different workers / PodCIDRs ping each other.

Our work (based on your guide) documented [here](https://github.com/Praqma/LearnKubernetes/blob/master/kamran/Kubernetes-The-Hard-Way-on-BareMetal.md).

Our latest setup is on virtualbox. When we test our kubedns deployment, we notice that it cycles through two correct responses, and then times out on third one.  It is not consistent. We have tried to look into logs, on controllers and on workers, but we could not put a finger on anything specific. 

Here is what we see:
First we get the deployment and service files from your repo. Then we set them up (not shown).

``` 
[root@controller1 tmp]# kubectl get deployment --all-namespaces
NAMESPACE     NAME           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
default       my-nginx       2         2         2            2           1h
kube-system   kube-dns-v20   2         2         2            2           58s
```
```
[root@controller1 tmp]# kubectl get pods
NAME                        READY     STATUS    RESTARTS   AGE
my-nginx-2494149703-8y52n   1/1       Running   0          1h
my-nginx-2494149703-hvr13   1/1       Running   0          1h
[root@controller1 tmp]# 
```

Here are two DNS responses, and the third one is failing:

```
[root@controller1 tmp]# kubectl exec -it my-nginx-2494149703-8y52n bash
root@my-nginx-2494149703-8y52n:/# dig yahoo.com

;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19492
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 6, ADDITIONAL: 11

;; QUESTION SECTION:
;yahoo.com.			IN	A

;; ANSWER SECTION:
yahoo.com.		991	IN	A	98.139.183.24
yahoo.com.		991	IN	A	98.138.253.109
yahoo.com.		991	IN	A	206.190.36.45

;; AUTHORITY SECTION:
yahoo.com.		68309	IN	NS	ns1.yahoo.com.
yahoo.com.		68309	IN	NS	ns4.yahoo.com.

;; ADDITIONAL SECTION:
ns4.yahoo.com.		167225	IN	A	98.138.11.157
ns3.yahoo.com.		165446	IN	AAAA	2406:8600:b8:fe03::1003

;; Query time: 11 msec
;; SERVER: 10.32.0.10#53(10.32.0.10)
;; WHEN: Tue Nov 22 13:06:17 UTC 2016
;; MSG SIZE  rcvd: 402
```

```
root@my-nginx-2494149703-8y52n:/# dig yahoo.com

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32122
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;yahoo.com.			IN	A

;; ANSWER SECTION:
yahoo.com.		990	IN	A	206.190.36.45
yahoo.com.		990	IN	A	98.138.253.109
yahoo.com.		990	IN	A	98.139.183.24

;; Query time: 2 msec
;; SERVER: 10.32.0.10#53(10.32.0.10)
;; WHEN: Tue Nov 22 13:06:18 UTC 2016
;; MSG SIZE  rcvd: 86
```

```
root@my-nginx-2494149703-8y52n:/# dig yahoo.com

; <<>> DiG 9.9.5-9+deb8u8-Debian <<>> yahoo.com
;; global options: +cmd
;; connection timed out; no servers could be reached
root@my-nginx-2494149703-8y52n:/#
```

And, this keeps repeating. Logs, etc, did not help. (May be I don't know where to look for, or may be I am blind :)

Any help is appreciated. Thanks!

**Comment by kelseyhightower** [comment]
This should be working fine on the master branch.
