### ISSUE TITLE
What's the significance of the `10.32.0.1` IP in kubernetes-csr.json?

### ISSUE THREAD

**Issue by kishorenc** [kelseyhightower/kubernetes-the-hard-way#105]
The IP `10.32.0.1` is listed in `kubernetes-csr.json` file [here](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/753e71bac8bdf2abf15237e8c45be1e6b5e4b380/docs/02-certificate-authority.md). I'm stumped as to which component uses this IP address (which given the `10.32.0.0/24` service IP CIDR is a virtual IP?).

**Comment by kishorenc** [comment]
It turns out to be the internal virtual IP of the Kubernetes API.

**Comment by zatricky** [comment]
I'm still curious as to where this IP address is defined. My current guess is the `  --service-cluster-ip-range=10.32.0.0/24 \\` line in the #configure-the-kubernetes-api-server and #configure-the-kubernetes-controller-manager sections of 08-bootstrapping-kubernetes-controllers.md

I haven't found mention of the IP address *anywhere* - just these two mentions of the IP range.

**Comment by tokiwinter** [comment]
@zatricky - as per the comment [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/master/services.go#L46-L47):
```
// Select the first valid IP from ServiceClusterIPRange to use as the GenericAPIServer service IP.
```

**Comment by Bregor** [comment]
First ip address of cluster ip range is the service address of kubernetes.default.svc.cluster.local. This address will be resolved by kube-dns for all pods, which wants to access api.
