### ISSUE TITLE
Unclear instructions about token.csv

### ISSUE THREAD

**Issue by jimcurtis** [kelseyhightower/kubernetes-the-hard-way#106]
In https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-kubernetes-controller.md the lab says the following:

Review the example token file and replace the default token.

cat token.csv

It is unclear what we are supposed to do here.  Why do we need to cat this file?  What do you mean by "replace default token"?  Is it required that we do this for the lab to work?  If you want us to replace "chAng3m3" with something of our own then tell us if there are any requirements on what we replace it with (i.e.  number of letters, mixed case, etc.).  And why not just provide the sed statement to change it?

**Comment by kelseyhightower** [comment]
This should be cleaned up on master.
