### ISSUE TITLE
Not Clear on Where to configure Remote access

### ISSUE THREAD

**Issue by jimcurtis** [kelseyhightower/kubernetes-the-hard-way#107]
This lab at https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/06-kubectl.md begins with:

Configuring the Kubernetes Client - Remote Access

Download and Install kubectl

But is is not clear where we should be doing this.  Should we do this on our gcloud console or some other machine completely outside our gcloud project?

Also, there is a section with:

Recall the token we setup for the admin user:

# /var/lib/kubernetes/token.csv on the controller nodes
chAng3m3,admin,admin
Also be sure to locate the CA certificate created earlier. Since we are using self-signed TLS certs we need to trust the CA certificate so we can verify the remote API Servers.

I don't know what you mean by "Recall the token we setup for the admin use".  Am I supposed to do anything here?

And what does "Also be sure to locate the CA certificate created earlier" mean?  What am I supposed to do?

**Comment by ReneSaenz** [comment]
@jimcurtis were you able to figure out your issue?

**Comment by kelseyhightower** [comment]
Remote access is now handled with TLS client certificates and the remote client lab has been updated.
