### ISSUE TITLE
Remote Access Lab - kubectl get componentstatuses times out with error

### ISSUE THREAD

**Issue by jimcurtis** [kelseyhightower/kubernetes-the-hard-way#108]
I completed all the preceding labs on GCE and I went through all the step in the Remote Access Lab on my gcloud console.  But when I do kubectl get componentstatuses it comes back with:

Unable to connect to the server: dial tcp 104.198.144.53:6443: i/o timeout

I verified the address is correct:

jicurtis@kube-the-hard-way-151222:~$ gcloud compute addresses list
NAME        REGION       ADDRESS         STATUS
kubernetes  us-central1  104.198.144.53  IN_USE

The firewall rules look correct:

jicurtis@kube-the-hard-way-151222:~$ gcloud compute firewall-rules list --filter "network=kubernetes"
NAME                         NETWORK     SRC_RANGES      RULES                         SRC_TAGS  TARGET_TAGS
kubernetes-allow-api-server  kubernetes  0.0.0.0/0       tcp:6443
kubernetes-allow-healthz     kubernetes  130.211.0.0/22  tcp:8080
kubernetes-allow-icmp        kubernetes  0.0.0.0/0       icmp
kubernetes-allow-internal    kubernetes  10.240.0.0/24   tcp:0-65535,udp:0-65535,icmp
kubernetes-allow-rdp         kubernetes  0.0.0.0/0       tcp:3389
kubernetes-allow-ssh         kubernetes  0.0.0.0/0       tcp:22

And the forwarding rules seem to be fine:

jicurtis@kube-the-hard-way-151222:~$ gcloud compute forwarding-rules describe kubernetes-rule
For the following forwarding rules:
 - [kubernetes-rule]
choose a region:
 [1] asia-east1
 [2] asia-northeast1
 [3] europe-west1
 [4] us-central1
 [5] us-east1
 [6] us-west1
Please enter your numeric choice:  4

IPAddress: 104.198.144.53
IPProtocol: TCP
creationTimestamp: '2016-12-01T16:00:34.371-08:00'
description: ''
id: '6093340783080703821'
kind: compute#forwardingRule
loadBalancingScheme: EXTERNAL
name: kubernetes-rule
portRange: 6443-6443
region: https://www.googleapis.com/compute/v1/projects/kube-the-hard-way-151222/regions/us-central1
selfLink: https://www.googleapis.com/compute/v1/projects/kube-the-hard-way-151222/regions/us-central1/forwardingRules/kubernetes-rule
target: https://www.googleapis.com/compute/v1/projects/kube-the-hard-way-151222/regions/us-central1/targetPools/kubernetes-pool

I am able to ping the IP address.  But ssh also does not work:

jicurtis@kube-the-hard-way-151222:~$ ssh 104.198.144.53
ssh: connect to host 104.198.144.53 port 22: Connection timed out

I am able to connect via ssh directly to the External IP addresses of my controllers.  So it would seem like a problem with the Load Balancer.  But I already showed the routing above and the details of the target-pool look fined to me:

jicurtis@kube-the-hard-way-151222:~$ gcloud compute target-pools describe kubernetes-pool
For the following target pools:
 - [kubernetes-pool]
choose a region:
 [1] asia-east1
 [2] asia-northeast1
 [3] europe-west1
 [4] us-central1
 [5] us-east1
 [6] us-west1
Please enter your numeric choice:  4
creationTimestamp: '2016-12-01T15:58:28.564-08:00'
description: ''
healthChecks:
- https://www.googleapis.com/compute/v1/projects/kube-the-hard-way-151222/global/httpHealthChecks/kube-apiserver-check
id: '5937426327705290699'
instances:
- https://www.googleapis.com/compute/v1/projects/kube-the-hard-way-151222/zones/us-central1-f/instances/controller0
- https://www.googleapis.com/compute/v1/projects/kube-the-hard-way-151222/zones/us-central1-f/instances/controller1
- https://www.googleapis.com/compute/v1/projects/kube-the-hard-way-151222/zones/us-central1-f/instances/controller2
kind: compute#targetPool
name: kubernetes-pool
region: https://www.googleapis.com/compute/v1/projects/kube-the-hard-way-151222/regions/us-central1
selfLink: https://www.googleapis.com/compute/v1/projects/kube-the-hard-way-151222/regions/us-central1/targetPools/kubernetes-pool

Any ideas?

**Comment by webeindustry** [comment]
I have same issue. In https://kubernetes.slack.com/messages/kubernetes-novice/ Another individual has issues remote connecting using AWS. It appears there may be a skip in the guide for one step. 

I get the same timeout error, he has this exact report which may provide insight:

`Error from server: x509: certificate is valid for worker0, worker1, worker2, ip-10-240-0-20, ip-10-240-0-21, ip-10-240-0-22, kubernetes, not ip-10-240-0-20.us-west-2.compute.internal`

**Comment by calebamiles** [comment]
@jimcurtis, were you trying to use `kubectl` from within a Google Cloud Shell terminal? I experienced the same `i/o timeout` error from within Cloud Shell but things worked perfectly fine from my desktop.

**Comment by jimcurtis** [comment]
@calebamiles yes that was the same thing I found when I retried it this week from my desktop.

**Comment by CruzanCaramele** [comment]
i completed this using AWS and experienced similar problems. At first , i could not SSH into my servers but i had to a rule to the default security group to allow that.
I got to configuring remote kubectl and it failed with the same problem you have all described.
I SSHed into my controllers to complete this tutorial.
I believe there might be a missing step in setting up the security groups perhaps.
