### ISSUE TITLE
can we not use kube-dns to do service discovery instead of nodeport ?

### ISSUE THREAD

**Issue by sandys** [kelseyhightower/kubernetes-the-hard-way#109]
can we not use kube-dns to route requests from loadbalancer to Service cluster-ip ? That way you dont have to bother creating the nodeports and registering them with the loadbalancer.

**Comment by kelseyhightower** [comment]
Even if you could kube-dns is not accessible outside of the cluster and most cloud LBs cannot target Pods and only VMs -- it's a limitation of the provider. In you own datacenter this would not be much of an issue.
