### ISSUE TITLE
Scaling L3 routing?

### ISSUE THREAD

**Issue by deitch** [kelseyhightower/kubernetes-the-hard-way#116]
Hi @kelseyhightower : great launch tutorial, especially like how it covers AWS _and_ GCP. Not all of us have choices with every project. :-)

Curious about scaling the L3 networking. Since you assign a `/24` to each host, does that not limit us to 256 (well, 254) pods per worker node? Granted, we are taking _pods_, not _containers_, but even so. If you wanted to remove the limit, I assume you would either go an overlay (Flannel, Weave, etc.) or IP-per-pod-no-subnet via Calico and distribute the IPs dynamically to the individual nodes via BGP?

Again, great walk-through. FYI, busy wrapping it all up in Terraform now, leveraging kops output and OpenCredo's run-through.

**Comment by kelseyhightower** [comment]
Yes, the networking option I'm using is to show how networking is done and you can adjust those limits by using something other than kubenet. Networking, like most things in Kubernetes, can be customized to fit your needs and using one of the solutions you've mentioned will help you do just that.

**Comment by deitch** [comment]
Ended up with weave on the current project, might be Calico on the next. Did some pretty intense low-level performance testing for a fintech last year (presented at LinuxCon on it), so sure, all works well.

That whole terraform ended up as a kubernetes terraform module. If they agree to open-source it, I will.

Thanks for updating to 1.6, btw, some really necessary additions in there.
