### ISSUE TITLE
UI dashboard

### ISSUE THREAD

**Issue by kaivanov** [kelseyhightower/kubernetes-the-hard-way#120]
Can you give an example how to install the dashboard and how to access it given the credentials we have created.

The docs suggest running: 
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

How do we access it afterwards?

**Comment by xueshanf** [comment]
This works for me, e.g:
```
kubectl proxy --port=8002
Starting to serve on 127.0.0.1:8002
```
Then connect to the dashboard:
```
127.0.0.1:8002/ui
```

**Comment by remonlam** [comment]
Kube-dashboard should have a nodePort that you could use;
`kubectl get svc --namespace=kube-system`

Gives you something like this;
```
NAME                   CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
heapster               10.32.0.185   <none>        80/TCP          7h
kube-dns               10.32.0.10    <none>        53/UDP,53/TCP   8h
kubernetes-dashboard   10.32.0.116   <nodes>       80:32397/TCP    8m
```
Browse to **http://[any-worker-ip]:32397** (port would be different for your environment)

**Comment by marshell08** [comment]
@remonlam How do you login to the UI ? I can view the UI but I keep getting **User "system:serviceaccount:kube-system:default" cannot list namespaces at the cluster scope. (get namespaces)**

I am thinking I need to add a user with credentials to access it ?

**Comment by kachkaev** [comment]
@marshell08 were you able to solve this problem with the user rights issue? I assume it's something to do with RBAC.

**Comment by kelseyhightower** [comment]
The cluster should support running any add on including the dashboard, but that's an exercise for the reader. I'm trying to keep the scope small here.
