### ISSUE TITLE
Worker node should reflect 1.5

### ISSUE THREAD

**Issue by hoeghh** [kelseyhightower/kubernetes-the-hard-way#124]
In the guide for setting up workernodes, there are one thing that does not work with Kubernetes 1.5, and one line that is deprecated.

in:
https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-worker.md

 --configure-cbr0=true
That is not valid in Kubernetes 1.5.

nor is (only deprecated):
  --api-servers=https://10.240.0.10:6443,https://10.240.0.11:6443,https://10.240.0.12:6443 \

**Comment by hoeghh** [comment]
Related to https://github.com/kelseyhightower/kubernetes-the-hard-way/pull/110

**Comment by kelseyhightower** [comment]
Fixed on master which is now targeting 1.6 and includes these fixes.
