### ISSUE TITLE
Failed to start certificate controller

### ISSUE THREAD

**Issue by everett-toews** [kelseyhightower/kubernetes-the-hard-way#126]
After installing kube-controller-manager and checking the status with [this command](https://github.com/kelseyhightower/kubernetes-the-hard-way/blame/26ff21f9d04ee0bb7084cbe57311f3dab08a38f8/docs/04-kubernetes-controller.md#L242):

```bash
$ sudo systemctl status kube-controller-manager --no-pager -l
● kube-controller-manager.service - Kubernetes Controller Manager
   Loaded: loaded (/etc/systemd/system/kube-controller-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-02-15 17:34:27 UTC; 1min 42s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 31425 (kube-controller)
    Tasks: 6
   Memory: 23.2M
      CPU: 315ms
   CGroup: /system.slice/kube-controller-manager.service
           └─31425 /usr/bin/kube-controller-manager --allocate-node-cidrs=true --cluster-cidr=10.200.0.0/16 --cluster-name=kubernetes --leader-elect=true --master=http://10.240.0.10:8080 --root-ca-file=/var/lib/kubernetes/ca.pem --service-account-private-key-file=/var/lib/kubernetes/kubernetes-key.pem --service-cluster-ip-range=10.32.0.0/24 --v=2

...
Feb 15 17:34:37 ip-10-240-0-10 kube-controller-manager[31425]: I0215 17:34:37.747516   31425 controllermanager.go:462] Starting certificates.k8s.io/v1alpha1 apis
Feb 15 17:34:37 ip-10-240-0-10 kube-controller-manager[31425]: I0215 17:34:37.747525   31425 controllermanager.go:464] Starting certificate request controller
Feb 15 17:34:37 ip-10-240-0-10 kube-controller-manager[31425]: E0215 17:34:37.747677   31425 controllermanager.go:474] Failed to start certificate controller: open /etc/kubernetes/ca/ca.pem: no such file or directory
Feb 15 17:34:37 ip-10-240-0-10 kube-controller-manager[31425]: E0215 17:34:37.757581   31425 util.go:45] Metric for serviceaccount_controller already registered
Feb 15 17:34:37 ip-10-240-0-10 kube-controller-manager[31425]: I0215 17:34:37.758133   31425 attach_detach_controller.go:197] Starting Attach Detach Controller
Feb 15 17:34:37 ip-10-240-0-10 kube-controller-manager[31425]: I0215 17:34:37.784167   31425 garbagecollector.go:756] Garbage Collector: Initializing
Feb 15 17:34:37 ip-10-240-0-10 kube-controller-manager[31425]: I0215 17:34:37.800853   31425 endpoints_controller.go:327] Waiting for pods controller to sync, requeuing service default/kubernetes
Feb 15 17:34:37 ip-10-240-0-10 kube-controller-manager[31425]: I0215 17:34:37.901467   31425 endpoints_controller.go:327] Waiting for pods controller to sync, requeuing service default/kubernetes
Feb 15 17:34:47 ip-10-240-0-10 kube-controller-manager[31425]: I0215 17:34:47.784786   31425 garbagecollector.go:770] Garbage Collector: All monitored resources synced. Proceeding to collect garbage
```

Note the error `Failed to start certificate controller: open /etc/kubernetes/ca/ca.pem: no such file or directory`

Perhaps the kube-controller-manager systemd service is misconfigured as documented or is this to be expected?

Versions:
* kubernetes==1.4.0
* ubuntu==16.04
* cloud==aws

**Comment by everett-toews** [comment]
```bash
$ kubectl get componentstatuses
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-2               Healthy   {"health": "true"}
etcd-1               Healthy   {"health": "true"}
etcd-0               Healthy   {"health": "true"}
```

So I guess this is to be expected? ¯\\\_(ツ)\_/¯

If so, go ahead and close the issue.

**Comment by javipolo** [comment]
I think the error log that you are getting is because you didnt set-up cluster-signing-cert ... and as far as I know it is not needed if you manage the certificates yourself ... :?

      --cluster-signing-cert-file string                                  Filename containing a PEM-encoded X509 CA certificate used to issue cluster-scoped certificates (default "/etc/kubernetes/ca/ca.pem")
      --cluster-signing-key-file string                                   Filename containing a PEM-encoded RSA or ECDSA private key used to sign cluster-scoped certificates (default "/etc/kubernetes/ca/ca.key")

**Comment by dennisxrow** [comment]
Setting `--cluster-signing-cert-file` and `--cluster-signing-key-file` fixes the `Failed to start certificate controller`.

However, it seems that these parameters or the /etc/kubernetes/ca/ca.pem are only used in Kubelet TLS Bootstrapping feature:
https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping
Which does not seems to be ready yet:
https://github.com/kubernetes/features/issues/43

**Comment by mikedanese** [comment]
It is a beta API, so it's ready. If you don't want to enable the controller, don't pass those flags. This error is absolutely not fatal (it's actually how we intend to support not enabling the controller).

**Comment by dennisxrow** [comment]
@mikedanese Thanks for the clarification, I was primarily concerned about the error message because I thought something went wrong.
Wich usually is the case if I see "failed" and "file not found" in one line :grimacing:

**Comment by mikedanese** [comment]
I will take that into consideration and change the error message. Thanks for the feedback.

**Comment by kelseyhightower** [comment]
Master is now tracking 1.6 with TLS bootstrapping enabled.
