### ISSUE TITLE
ELB should have its own subnet to avoid collision

### ISSUE THREAD

**Issue by kingpong** [kelseyhightower/kubernetes-the-hard-way#129]
I followed the [AWS instructions](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/01-infrastructure-aws.md) and when I attempted to create the first EC2 instance (controller 0), I received the following error:

    % CONTROLLER_0_INSTANCE_ID=$(aws ec2 run-instances \
    cmdsubst>   --associate-public-ip-address \
    cmdsubst>   --iam-instance-profile 'Name=kubernetes' \
    cmdsubst>   --image-id ${IMAGE_ID} \
    cmdsubst>   --count 1 \
    cmdsubst>   --key-name kubernetes \
    cmdsubst>   --security-group-ids ${SECURITY_GROUP_ID} \
    cmdsubst>   --instance-type t2.small \
    cmdsubst>   --private-ip-address 10.240.0.10 \
    cmdsubst>   --subnet-id ${SUBNET_ID} | \
    cmdsubst pipe>   jq -r '.Instances[].InstanceId')
    
    An error occurred (InvalidIPAddress.InUse) when calling the RunInstances operation: Address 10.240.0.10 is in use.

The ELB had randomly chosen 10.240.0.10 for its VPC-facing IP, so that address was unavailable for controller 0.

I am working around this problem by placing the ELB in its own dedicated subnet (same VPC, same routing table), which should prevent further collisions.  PR forthcoming.

**Comment by kelseyhightower** [comment]
I've decided to focus on a single platform for this guide. I'm shifting focus to cover more configuration options such as RBAC, TLS bootstrapping, and add-ons. Too much time required to keep the IaaS bits in sync with AWS.
