### ISSUE TITLE
AWS Docs?

### ISSUE THREAD

**Issue by malnick** [kelseyhightower/kubernetes-the-hard-way#136]
Was there a force commit recently that removed the AWS-specific docs? I refreshed my page while doing this tutorial and they are now gone. I can live with out them,  but copy/paste was making quick work of the tutorial.

**Comment by Bregor** [comment]
Not so force, but here they are:

https://github.com/kelseyhightower/kubernetes-the-hard-way/commit/4989117cf2eedb9c1ca44e24b4b9c90375b9d942

https://github.com/kelseyhightower/kubernetes-the-hard-way/commit/333aefba3f0e60ee4f80b626950b09e7e02b5be9

https://github.com/kelseyhightower/kubernetes-the-hard-way/commit/8022f4077b6bca9da0126045c53f9e78a5d1633f

**Comment by tristanls** [comment]
"remove AWS support" :? ... oh well... it's free so ¯\\_(ツ)_/¯

**Comment by malnick** [comment]
Ah missed those, thanks @Bregor
