### ISSUE TITLE
kube-proxy failing certificate validation

### ISSUE THREAD

**Issue by spirrello** [kelseyhightower/kubernetes-the-hard-way#141]
Hi,

Since following the new instructions for 1.6 I've been getting the following errors on my worker nodes on the kube-proxy process.  I've imported the ca.pem as a trusted CA on all nodes but this doesn't seem to fix the problem.  Has anyone seen a problem like this?

 k8s.io/kubernetes/pkg/proxy/config/api.go:49: Failed to list *api.Endpoints: Get https://10.155.9.254:6443/api/v1/endpoints?resourceVersion=0: x509: certificate is valid for 10.155.9.136, 10.157.17.1, not 10.155.9.254

**Cert diagnostics:**
 openssl verify -verbose -CAfile ca.pem kubernetes.pem
kubernetes.pem: OK

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            5c:87:2d:26:98:da:ad:97:9f:c6:74:56:37:7d:22:a6:1e:28:53:ed
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=Georgia, L=Alpharetta, O=Acme Technologies, OU=GA, CN=Kubernetes
        Validity
            Not Before: Mar 29 14:48:00 2017 GMT
            Not After : Mar 27 14:48:00 2027 GMT
        Subject: C=US, ST=Georgia, L=Alpharetta, O=Acme Technologies, OU=at4d-dev, CN=kubernetes
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:af:49:bb:2d:e5:77:d8:cd:ce:fc:d4:ef:3d:7a:
                    68:5c:25:a7:57:79:32:90:28:17:c7:f1:3c:49:50:
                    e4:7c:9e:76:f5:44:ff:8a:e4:ad:55:9a:bf:ae:3d:
                    04:87:08:c6:c9:5b:0d:3a:41:61:11:ad:ad:67:86:
                    4e:7a:8a:c6:0e:88:50:c7:86:5c:27:54:b2:dc:be:
                    cf:49:bc:a3:31:90:d5:da:83:27:2b:4f:72:ed:2a:
                    d5:a7:1d:17:09:f7:44:6f:63:82:77:39:bc:9a:69:
                    3b:b3:26:62:e3:b2:27:2d:e3:19:81:14:07:4f:f0:
                    e3:78:40:f8:bd:30:b6:19:22:b9:79:b0:be:9d:0a:
                    8f:24:ef:55:bb:50:bf:ef:de:cc:d4:ba:50:b3:99:
                    3a:ab:71:aa:8a:ab:0c:d4:80:fc:20:7d:16:df:69:
                    2e:75:f2:c3:08:52:3f:b7:a4:15:22:c5:08:4c:6c:
                    f2:b2:b7:f5:94:68:ee:0a:ec:08:17:30:17:58:0d:
                    ec:d2:9c:ac:5c:cd:fa:e3:65:1b:7f:f2:0e:74:e0:
                    a7:23:d0:d9:9e:27:ac:92:ac:fb:75:fe:72:70:65:
                    2d:e1:80:7d:35:f9:98:d7:36:53:45:a6:70:3c:8a:
                    7d:64:84:e4:50:d6:71:e2:34:8b:7c:aa:d9:15:4d:
                    89:1f
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                C4:FA:03:94:40:96:56:27:21:36:B9:97:E8:0A:96:A0:B0:C1:0F:C3
            X509v3 Authority Key Identifier:
                keyid:A2:39:3D:CB:84:EE:60:62:6D:02:B0:66:2F:06:2E:F1:C5:C7:41:B9

            X509v3 Subject Alternative Name:
                DNS:Acme.com, DNS:*.Acme.dev, DNS:*.Acme.prod, DNS:*.Acme, DNS:*.pass.Acme, IP Address:10.155.9.135, IP Address:10.155.9.136, IP Address:10.155.9.137, IP Address:10.155.9.254
    Signature Algorithm: sha256WithRSAEncryption
         61:2c:96:97:d7:e1:4b:73:62:e5:74:0f:13:3a:04:e0:c8:66:
         2e:38:88:8c:fa:d5:bd:d3:20:79:70:00:66:40:53:1f:2e:44:
         39:f7:82:5f:e2:aa:4f:3a:9f:51:90:14:d0:20:0d:25:8e:31:
         29:82:3a:4e:b7:bb:38:1c:79:d1:ba:d4:8b:fb:3c:21:6a:54:
         cf:f4:ef:96:2f:e4:5e:98:92:cb:4a:fe:18:82:f8:35:8d:01:
         84:b6:10:62:70:72:32:b6:d3:aa:a5:39:17:62:5f:a5:70:d9:
         d4:6a:f0:d3:89:47:86:b0:e4:f0:0a:c5:d1:09:6d:43:2a:61:
         90:9c:a7:d4:76:35:42:3d:ba:44:ed:6b:7a:6c:80:61:de:1a:
         66:73:d2:89:fe:1d:e1:72:fe:6e:36:48:a5:6a:a2:8d:47:ca:
         69:4a:9f:a2:19:85:1b:74:25:79:f4:93:bf:c1:a8:88:3c:87:
         16:4d:6e:09:d4:76:d0:63:40:54:09:89:ac:1e:ee:1d:58:c3:
         20:8c:ce:16:0d:6c:9d:4a:f3:67:03:52:9a:a9:74:f8:bd:1c:
         41:f0:c3:68:05:3d:e6:8f:c0:be:61:1a:cf:31:00:ee:0d:ef:
         c4:2b:43:fb:1a:b3:26:2f:d4:23:76:a3:4b:65:fd:a9:13:85:
         f2:0f:15:05

**Comment by kelseyhightower** [comment]
Notice in the new guide you have to generate a set of certificates just for the proxy.

**Comment by kelseyhightower** [comment]
You need to generate a TLS cert for the proxy: https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/02-certificate-authority.md#create-the-kube-proxy-client-certificate


Then a kubeconfig just for the proxy: https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-auth-configs.md#create-the-kube-proxy-kubeconfig

In the updated guide the kube-proxy.kubeconfig will be used when setting up the kube-proxy service -- see the update kube-proxy.service system unit file.

**Comment by spirrello** [comment]
Understood and I've followed all of the steps thoroughly.  I have all of the certs (kubernetes, kube-proxy and ca certs) and I've redeployed them multiple times with the same issue.  Which component of the kube-proxy is it that would be failing to recognize the certs on the Master nodes?  Etcd is running fine using the kubernetes certs and neither of the etcd servers are complaining. 

If you look at the output of my openssl check 10.155.9.254 (VIP), 10.155.9.135-137 are covered within the kubernetes.pem cert.  The funny thing is that if I update the kube-proxy.kubeconfig file to point to one of the individual masters it will begin complaining about the cert being signed by an unknown authority.

**Comment by spirrello** [comment]
One more thing....if I do a "systemctl status kube-apiserver" on the master nodes, I see the following errors.

Mar 30 01:40:08 at4d-lvk8s01.Acme.prod kube-apiserver[10583]: I0330 01:40:08.621437   10583 logs.go:41] http: TLS handshake error from 10.155.9.138:41533: read tcp 10.155.9.135:6443->10.155.9.138:41533: read: connection reset by peer
Mar 30 01:40:08 at4d-lvk8s01.Acme.prod kube-apiserver[10583]: I0330 01:40:08.633490   10583 logs.go:41] http: TLS handshake error from 10.155.9.139:47911: read tcp 10.155.9.135:6443->10.155.9.139:47911: read: connection reset by peer
Mar 30 01:40:08 at4d-lvk8s01.Acme.prod kube-apiserver[10583]: I0330 01:40:08.814471   10583 logs.go:41] http: TLS handshake error from 10.155.9.4:55969: read tcp 10.155.9.135:6443->10.155.9.4:55969: read: connection reset by peer
Mar 30 01:40:09 at4d-lvk8s01.Acme.prod kube-apiserver[10583]: I0330 01:40:09.188226   10583 logs.go:41] http: TLS handshake error from 10.155.9.4:50422: read tcp 10.155.9.135:6443->10.155.9.4:50422: read: connection reset by peer
Mar 30 01:40:09 at4d-lvk8s01.Acme.prod kube-apiserver[10583]: I0330 01:40:09.210821   10583 logs.go:41] http: TLS handshake error from 10.155.9.139:47914: read tcp 10.155.9.135:6443->10.155.9.139:47914: read: connection reset by peer
Mar 30 01:40:09 at4d-lvk8s01.Acme.prod kube-apiserver[10583]: I0330 01:40:09.270517   10583 logs.go:41] http: TLS handshake error from 10.155.9.139:47915: read tcp 10.155.9.135:6443->10.155.9.139:47915: read: connection reset by peer
Mar 30 01:40:09 at4d-lvk8s01.Acme.prod kube-apiserver[10583]: I0330 01:40:09.515981   10583 logs.go:41] http: TLS handshake error from 10.155.9.138:41536: read tcp 10.155.9.135:6443->10.155.9.138:41536: read: connection reset by peer
Mar 30 01:40:09 at4d-lvk8s01.Acme.prod kube-apiserver[10583]: I0330 01:40:09.622109   10583 logs.go:41] http: TLS handshake error from 10.155.9.138:41537: read tcp 10.155.9.135:6443->10.155.9.138:41537: read: connection reset by peer
Mar 30 01:40:09 at4d-lvk8s01.Acme.prod kube-apiserver[10583]: I0330 01:40:09.635491   10583 logs.go:41] http: TLS handshake error from 10.155.9.138:41538: read tcp 10.155.9.135:6443->10.155.9.138:41538: read: connection reset by peer
Mar 30 01:40:09 at4d-lvk8s01.Acme.prod kube-apiserver[10583]: I0330 01:40:09.648240   10583 logs.go:41] http: TLS handshake error from 10.155.9.139:47916: read tcp 10.155.9.135:6443->10.155.9.139:47916: read: connection reset by peer
