### ISSUE TITLE
Clarify Worker to API communication path 

### ISSUE THREAD

**Issue by loganlee** [kelseyhightower/kubernetes-the-hard-way#144]
The Bootstrapping Kubernetes Workers Lab includes a section on how to create the kubelet systemd unit file.  In it you have the following:

```
API_SERVERS=$(sudo cat /var/lib/kubelet/bootstrap.kubeconfig | \
  grep server | cut -d ':' -f2,3,4 | tr -d '[:space:]')
```

You then use API_SERVERS here:
`--api-servers=${API_SERVERS} \\`

Can you please expand on what IP the API_SERVER is intended to be and what path you intend communication from each of the the 3 Workers to any of the 3 masters to take?

**Comment by loganlee** [comment]
Also, I believe you may be recommending one path for kubelet and a different path for kubeproxy due to the differences in their support for multiple masters.  If so, it would be useful to highlight that.

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
