### ISSUE TITLE
use kubenet after install cni network plugin

### ISSUE THREAD

**Issue by alirezaDavid** [kelseyhightower/kubernetes-the-hard-way#145]
Hi 
thanks for your awesome work.
in worker section you install cni network plugin but use  this `  --network-plugin=kubenet `  flag.
Can i using it with `  --network-plugin=cni`?

**Comment by Dmitry1987** [comment]
@alirezaDavid  hi, I had issue with **kubelet** not connecting to masters (with error about kubenet no CIDR config ready or something), were you able to make kubenet work? or switching to cni helps?

**Comment by vogxn** [comment]
I found this confusing too. In fact encountered the same issue reported in #53 although I'm using google cloud. I will try the CNI plugin and report back. FWIW, this is the error I see on the worker nodes when kubelet attempts to register to the apiserver

```
May 04 14:02:24 worker1 kubelet[3093]: E0504 14:02:24.983970    3093 kubelet.go:2067] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
```

**Comment by vogxn** [comment]
I'm able to proceed a little further by using the following in `/etc/cni/net.d/kube.conf`

```json
{
    "cniVersion": "0.5.2",
    "name": "mynet",
    "type": "bridge",
    "bridge": "cni0",
    "isGateway": true,
    "ipMasq": true,
    "ipam": {
        "type": "host-local",
        "subnet": "10.22.0.0/16"
    }
}```

But my workers are unable to register with kube-apiserver due to a tcp timeout on port 6443. Appears to be a separate problem though.

**Comment by temal-** [comment]
To anwer the inital question of @alirezaDavid:

Reading the [kubetnet documentation](https://kubernetes.io/docs/concepts/cluster-administration/network-plugins/#kubenet) helped me understand this a little bit better.

The CNI tools (not all, but at least `bridge`, `lo` and `host-local`) are required for kubenet to work. When you start the kubelet with `--network-plugin=kubenet` you should see a generated CNI configuration in the logs which is used by the kubelet.

When you start the kubelet with `--network-plugin=cni` you'll have to provide your own CNI configuration.

**Comment by iftachsc** [comment]
@kelseyhightower 
I was getting to the same situation as @vogxn, then adding his cube.conf and then there are no errors any more. not on kubelet on the node and not on the api server.
but node is not registering. my only indication is kubectl get node on one of the masters which returns no resources found.

I know this hard-way procedure is meant for kube-net but it will be awesome if we have a walkthrough for a chi, e.g flannel. 

in usual deployments, automated. etc, you can apply flannel configuration with a daemon sets that mounts the /etc/cni/net.d and pour the content  there. here I don't have a joined node so the daemon set can run on. I am not sure what are the steps for making chi like flannel deployed on this the-hard-way procedure. will be happy to know!

many thanks for the good work!

**Comment by kelseyhightower** [comment]
This is being fixed and will be updated in the docs.

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.

**Comment by avgKol** [comment]
@temal- @kelseyhightower Hi , Thank you so much these for these labs. Just got your book "Kubernetes: Up and Running" and it is amazing.
However ,I am confused about the network plugins flag.  You have mentioned that you do not want to use an overlay network but you are using `--network-plugin=cni`  in Chapter "Bootstrapping the Kubernetes Worker Nodes". Should we not be using `--network-plugin=kubenet` instead ?
