### ISSUE TITLE
Unable to kubectl exec or kubectl run 

### ISSUE THREAD

**Issue by augabet** [kelseyhightower/kubernetes-the-hard-way#146]
Hello,

When I am trying to access logs or go inside a POD, I encounter some certificates problems: 

```
$ kubectl logs nginx-158599303-bbkwt
Error from server: Get https://aug-worker1:10250/containerLogs/default/nginx-158599303-bbkwt/nginx: x509: certificate is valid for system:node:aug-worker1, not aug-worker1
```

```
$ kubectl exec -it nginx-158599303-bbkwt /bin/sh
Error from server: error dialing backend: x509: certificate is valid for system:node:aug-worker1, not aug-worker1
```

When I look my certificate obtained with TLS bootstraping: 
 ```
$ openssl x509 -in /var/run/kubernetes/kubelet-client.crt -text -noout

[12:03]  
 Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0d:0f:12:7c:35:62:58:91:10:12:9d:13:02:e2:ae:b0:50:d4:fe:8c
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=FR, ST=Paris, L=Paris, O=TOTO, OU=OPS, CN=Kubernetes
        Validity
            Not Before: Apr  3 08:29:00 2017 GMT
            Not After : Apr  3 08:29:00 2018 GMT
        Subject: O=system:nodes, CN=system:node:aug-worker1
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: .......
```
My cluster seems to be healthy :

```$ kubectl get componentstatuses
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-2               Healthy   {"health": "true"}
etcd-1               Healthy   {"health": "true"}
etcd-0               Healthy   {"health": "true"}
```

```
$ kubectl get csr
NAME        AGE       REQUESTOR           CONDITION
csr-1zcr4   8h        kubelet-bootstrap   Approved,Issued
csr-9j2wk   8h        kubelet-bootstrap   Approved,Issued
csr-gv1hm   8h        kubelet-bootstrap   Approved,Issued
```

```
$ kubectl get nodes
NAME          STATUS    AGE       VERSION
aug-worker1   Ready     7h        v1.6.0
aug-worker2   Ready     7h        v1.6.0
aug-worker3   Ready     7h        v1.6.0
```

I am not able to find if I misconfigured my cluster or if it could be a bug.

**Comment by cyeong** [comment]
facing the same issue here, temporarily removed

```
  --kubelet-certificate-authority=/var/lib/kubernetes/ca.pem \
  --kubelet-client-certificate=/var/lib/kubernetes/kubernetes.pem \
  --kubelet-client-key=/var/lib/kubernetes/kubernetes-key.pem \
```

from kube-apiserver service file to make it work, but what would be the solution to this?

**Comment by liggitt** [comment]
the solution is to give the kubelet a serving certificate signed by the `--kubelet-certificate-authority`

**Comment by augabet** [comment]
OK, thank you for your feedback. Should I understand that the TLS Bootstrapping feature is not fully terminated, and should not be used for now. Am I correct ?

Regards.

**Comment by liggitt** [comment]
Correct, it is still in progress (the flag to enable it is named `--experimental-bootstrap-kubeconfig` :)

Currently it bootstraps client credentials for the kubelet using the CSR API. Work is in progress for it to separately request serving certs using the CSR API.

**Comment by kalise** [comment]
@liggitt In 1.7.2 the issue is still present even if the flag changed from ``--experimental-bootstrap-kubeconfig `` to  `` --bootstrap-kubeconfig`` in the documentation.

```[root@centos kube-samples]# kubectl exec -it nginx1 bash
Error from server: error dialing backend: x509: certificate is valid for system:node:kubew03, not kubew03
[root@centos kube-samples]#
```

**Comment by liggitt** [comment]
that flag does not control serving certificate bootstrapping. serving certificate bootstrapping is alpha in 1.7, and not enabled by default. see docs on the RotateKubeletServerCertificate feature gate in https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/ or follow https://github.com/kubernetes/features/issues/267 for more info on the serving cert bootstrapping
