### ISSUE TITLE
RBAC DENY Messages

### ISSUE THREAD

**Issue by spirrello** [kelseyhightower/kubernetes-the-hard-way#148]
Hi,

I'm getting these messages on my masters.  How can I fix this to begin approving the CSRs from the worker nodes?

Apr 04 21:32:33 at4d-lvk8s01.acme kube-apiserver[2532]: I0404 21:32:33.121424    2532 rbac.go:87] RBAC DENY: user "kubelet-bootstrap" groups [system:kubelet-bootstrap system:authenticated] cannot "create" resource "events" in namespace "default"

**Comment by maxx** [comment]
@spirrello did you figure this one out?

**Comment by maxx** [comment]
@spirrello did you run this piece?  

from https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/06-kubernetes-worker.md#prerequisites

```kubectl create clusterrolebinding kubelet-bootstrap \
  --clusterrole=system:node-bootstrapper \
  --user=kubelet-bootstrap```

**Comment by spirrello** [comment]
Yeah actually I added the following to my playbook and I believe it corrected the issue.

- name: enable TLS bootstrapping
  shell: kubectl create clusterrolebinding kubelet-bootstrap \
         --clusterrole=system:node-bootstrapper \
         --user=kubelet-bootstrap
  when: inventory_hostname in groups['masters'][0]

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
