### ISSUE TITLE
client not able to reach the cluster

### ISSUE THREAD

**Issue by ophintor** [kelseyhightower/kubernetes-the-hard-way#149]
I'm not able to reach the cluster from my client:

```
$ kubectl get componentstatuses
Unable to connect to the server: dial tcp 104.198.143.170:6443: i/o timeout
```

I'm pretty sure it's me but I don't know how to troubleshoot it further. I've reviewed my ~.kube/config file. All seems good. I did ran the command to open the port 6443 (in the controllers creation section) but don't seem able to reach it via telnet.

What else could I do to identify the root issue? I'm pretty stuck here.
Thanks!
David

**Comment by xuwang** [comment]
@ophintor You might want to make sure the kube-apiserver is running alright.  Login on to one of the controllers and run:
```
$ journalctl -f -u kube-apiserver
```
This might give you some clue if the api server is having any problems.

**Comment by ophintor** [comment]
Hi @xuwang, thanks! I will check that out...

**Comment by amandadebler** [comment]
I'm also having that issue, even from Cloud Shell. I'm able to SSH into all the nodes from Cloud Shell, and telnet (external IP address of controllerX) 22 connects, but telnet (external IP of controllerX/IP of load balancer) 6443 does not. The telnet tests work inside the cluster, as do all the kubectl commands, including deploying nginx.

The FW rule for the NodePort also doesn't work from outside or Cloud Shell, but curl to that port works from within the cluster.

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now. Also note cloud shell is limited on which ports it can hit -- support only a hand full of ports, and node ports fall out of range.
