### ISSUE TITLE
Explain how HA works

### ISSUE THREAD

**Issue by ae6rt** [kelseyhightower/kubernetes-the-hard-way#15]
Kelsey, this is great stuff.  Thank you.

When I studied the API server command line flags, I expected to see some indication of where the other API servers were running in the cluster.  Instead, I see only _--apiserver-count=3_, which doesn't say where to find the other two instances.

In the same vein, when I look at the controller-manager and scheduler command line config, I can reason about how they leader-elect, because they both point at a master in the know.

So what is not clear is how the masters find each other, if in fact they need to find each other at all.

Could you add a paragraph elaborating on this?

**Comment by Bregor** [comment]
> which doesn't say where to find the other two instances

etcd says about it ;)

**Comment by ae6rt** [comment]
Fair enough.  But then why is _api-server-count_ needed if a master can simply consult etcd for the same value?

**Comment by Bregor** [comment]
In my head (i can be terribly wrong) it looks like following:

1. First apiserver says to etcd: "there will be 3 apiservers here, show me others or I'll be the first"
2. Second apiserver says: "there will be 3 apiservers here, show me the the others or... oh shi!"
3. <you get the idea>

**Comment by kelseyhightower** [comment]
This is a great issue thanks for opening it. The apiserver count is for the service that Kubernetes creates inside the cluster which will be used to populate the endpoints for the api server service. I'm a little fuzzy on why that flag is required at all, so I'll get some clarity and update the docs.

**Comment by ae6rt** [comment]
Here is a cross reference, which I am sure you know about.  It does not mention apiserver-count at all:

http://kubernetes.io/docs/admin/high-availability/

**Comment by kelseyhightower** [comment]
@ae6rt I've found this github issue https://github.com/kubernetes/kubernetes/issues/24327, which I'll reworking into some docs for this repo.

**Comment by ae6rt** [comment]
Ran across this re worker processes and multiple API servers:  https://github.com/kubernetes/kubernetes/issues/18174

**Comment by kelseyhightower** [comment]
I've update the worker nodes to leverage the LB that sits in from of the API server. I'm also using the `--apiserver-count` flag when bootstrapping the control plane.
