### ISSUE TITLE
Connecting to kube-proxy occasionally times-out

### ISSUE THREAD

**Issue by Alan01252** [kelseyhightower/kubernetes-the-hard-way#151]
Occasionally connections to the proxy will timeout. Meaning in the smoke test it'll look like the service isn't working.

This happens both on the worker and externally via the curl call.

Editing` /etc/systemd/system/kube-proxy.service` and changing 

`proxy-mode=iptables `
to 
`proxy-mode=userspace`

"fixes" the issue.

This could be related to https://github.com/kubernetes/kubernetes/issues/29759 .

**Comment by mercer** [comment]
Indeed, this fixed the issue for me.

**Comment by claytonmorrow** [comment]
Following on that this fixed the smoke test for me as well.

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
