### ISSUE TITLE
Subnet creation passes zone instead of region

### ISSUE THREAD

**Issue by castillobgr** [kelseyhightower/kubernetes-the-hard-way#153]
This is not an issue with this repo but with `gcloud` (I have the latest version, but it happens in the cloud shell as well).
I am following the guide and while [creating the subnet](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/01-infrastructure-gcp.md#setup-networking) it failed with
```
ERROR: (gcloud.compute.networks.subnets.create) Some requests did not succeed:
 - Invalid value for field 'region': 'us-central1-f'. Unknown region
```
For some reason, it's passing the zone instead of the region. So I had to pass it explicitly:
```
gcloud compute networks subnets create kubernetes --network kubernetes-the-hard-way --range 10.240.0.0/24 --region us-central1
```
I'll update the docs so the setup goes smoothly 😃

**Comment by jacquestardie** [comment]
This happened for me as well, thanks for noting @castillobgr 🙏

**Comment by abraithwaite** [comment]
Ran into the same issue following the same exact guide.  Thanks for opening this report!

**Comment by loffelmacher** [comment]
If you're slow like me, let me help you. You can go into the Cloud Console and use the GUI to complete this step.
