### ISSUE TITLE
Custom Linux

### ISSUE THREAD

**Issue by snap9** [kelseyhightower/kubernetes-the-hard-way#157]
Currently this guide "requires access to Google Compute Engine". Why, and are there any plans to make the guide not require this?

I'm interested in not relying on Google and just using my own Linux VPS for everything.

**Comment by themsay** [comment]
You simply need to do your homework by searching for fork related projects.

I managed set it up on vagrant with shutit [link](https://github.com/ianmiell/shutit-k8s-the-hard-way).

Although this has external Loadbalancer which can be used in place of GCE builtin loadbalancer functionality.

#### Step1 - Create python virtualenv:
<pre>
mkdir ~/Project && cd ~/Project
virtualenv env
. env/bin/activate
pip install shutit
</pre>
Note: you may need <code>gawk</code> and <code>gnu-tar</code> if is not already installed, in my case is MacOS.

#### Step1 - Vagrant clone the repo:
<pre>
git clone --recursive https://github.com/ianmiell/shutit-k8s-the-hard-way
cd shutit-k8s-the-hard-way
./walkthrough.sh
</pre>

### Management
<pre>
cd ~/shutit_k8s_the_hard_way_XXXXX/
vagrant up/halt
</pre>
Note: shutit_k8s_the_hard_way_XXXXX is shutit auto generated vagrant directory, XXXXX can be any string.


Well, with this at hand you can learn the inner workings of Kubernetes but still 'The Hard Way'!

**Comment by opsnull** [comment]
@snap9 
I'm writting a series documents about installing k8s cluster on CentOS 7 or Ubuntu 16.04 in chinese, 
you can find [here;](https://github.com/opsnull/follow-me-install-kubernetes-cluster)

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now. But I only plan to support a single OS. I only have so much time.
