### ISSUE TITLE
--api-servers has been deprecated

### ISSUE THREAD

**Issue by glycerine** [kelseyhightower/kubernetes-the-hard-way#158]
starting a kubelet with `--api-servers`,  per step 06, https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/06-kubernetes-worker.md, results in this logged warning:

Apr 21 00:05:10 k1 kubelet[18925]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
