### ISSUE TITLE
kube-proxy and kubelet have different master values

### ISSUE THREAD

**Issue by ae6rt** [kelseyhightower/kubernetes-the-hard-way#16]
If the kubelet has CSV list of masters for _api-servers_, should kube-proxy have the same value for _master_?

**Comment by Bregor** [comment]
Unfortunately `kube-proxy` have no ability to use list of masters (due to `--help`):

          --master="": The address of the Kubernetes API server (overrides any value in kubeconfig)

**Comment by kelseyhightower** [comment]
@Bregor Is right. This are the kind of issues that I want to highlight so we can get them fixed.

**Comment by Bregor** [comment]
BTW, @kelseyhightower is it possible to use list of masters in `kubeconfig`?

**Comment by kelseyhightower** [comment]
@Bregor I'm research the `kubeconfig` options now. Last time I checked I don't think you can do that. For remote clients this is not really a big deal, but for internal components it would be nice to support to use a list of masters.

**Comment by kelseyhightower** [comment]
Looks like `kubeconfig` only accepts a single server. I'm sure this was done clients should really be pointed at a load balancer that sits in front of multiple masters.
