### ISSUE TITLE
open ports in 01-infrastructure ?

### ISSUE THREAD

**Issue by samv** [kelseyhightower/kubernetes-the-hard-way#160]
Hi, I was working through this and couldn't help but notice the extra open ports in the instructions.

22 is ssh, as expected.  6443 after some googling seems to be an alternate 443 for management in case 443 can't be allocated due to privileges.  But port 3389 is not referenced anywhere else, nor can I find it to be anything except RDP - remote desktop port.  Forgive me if it is mentioned somewhere else, but those open ports probably deserve an explanation.  If you answer I can make a PR :)

**Comment by debianmaster** [comment]
ya,  i did not understand why we need to open `3389`  port.  can anyone explain please

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.

**Comment by kelseyhightower** [comment]
Port 3389 is RDP and has been removed from the list and is not required.
