### ISSUE TITLE
Unexpected service-account-key-file value change

### ISSUE THREAD

**Issue by Bregor** [kelseyhightower/kubernetes-the-hard-way#161]
Before https://github.com/kelseyhightower/kubernetes-the-hard-way/commit/f62e9c9777fe08dfe35a31b48f4b92f66c08cd86 value of `--service-account-key-file` was `kubernetes-key.pem` (apiserver's private key).
But in https://github.com/kelseyhightower/kubernetes-the-hard-way/commit/f62e9c9777fe08dfe35a31b48f4b92f66c08cd86#diff-c7cea6d6c96b88b8ecc73c023fb24210R136 its value unexpectedly changes to `ca-key.pem` (private part of CA).

Was it intentionally or accidentally?

**Comment by Bregor** [comment]
Same for controller manager in https://github.com/kelseyhightower/kubernetes-the-hard-way/commit/3b1700d85e9de1ff6a6f20eb3d01353e8b5810c4#diff-6b315d1b1f1a6ff82d104075d9ec8cbcR264

    --service-account-private-key-file=/var/lib/kubernetes/ca-key.pem

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
