### ISSUE TITLE
Default cluster has no server defined

### ISSUE THREAD

**Issue by b3nder2016** [kelseyhightower/kubernetes-the-hard-way#162]
I failed on the step 6. I am using AWS EC2 and k8s 1.6.2. here is what I see in the logs:

Apr 22 20:15:11 ip-10-1-1-147 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Apr 22 20:15:11 ip-10-1-1-147 systemd[1]: Stopped Kubernetes Kubelet.
Apr 22 20:15:11 ip-10-1-1-147 systemd[1]: Started Kubernetes Kubelet.
Apr 22 20:15:11 ip-10-1-1-147 kubelet[5401]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Apr 22 20:15:11 ip-10-1-1-147 kubelet[5401]: I0422 20:15:11.890481    5401 feature_gate.go:144] feature gates: map[]
Apr 22 20:15:11 ip-10-1-1-147 kubelet[5401]: I0422 20:15:11.890698    5401 bootstrap.go:58] Using bootstrap kubeconfig to generate TLS client cert, key and kubeconfig file
Apr 22 20:15:11 ip-10-1-1-147 kubelet[5401]: error: failed to run Kubelet: unable to load bootstrap kubeconfig: invalid configuration: default cluster has no server defined
Apr 22 20:15:11 ip-10-1-1-147 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 20:15:11 ip-10-1-1-147 systemd[1]: kubelet.service: Unit entered failed state.
Apr 22 20:15:11 ip-10-1-1-147 systemd[1]: kubelet.service: Failed with result 'exit-code'.

here is my bootstrap.kubeconfig

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4RENDQXF5Z0F3SUJBZ0lVZFF3TkkrSHRRS1FzSm9wNkdST0daOU1wcjlNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJNd0VRWURWUVFECkV3cExkV0psY201bGRHVnpNQjRYRFRFM01EUXlNakUxTVRZd01Gb1hEVEl5TURReU1URTFNVFl3TUZvd2FERUwKTUFrR0ExVUVCaE1DVlZNeER6QU5CZ05WQkFnVEJrOXlaV2R2YmpFUk1BOEdBMVVFQnhNSVVHOXlkR3hoYm1ReApFekFSQmdOVkJBb1RDa3QxWW1WeWJtVjBaWE14Q3pBSkJnTlZCQXNUQWtOQk1STXdFUVlEVlFRREV3cExkV0psCmNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE5aFREQUNXcGdHL2MKUE50U0U1UHBRenNKQ0dTdk9rWnJQajRabS90TG1kNTJQZ1RkNUpiZ0tpOXZSWjc4R0s0aytoakhBWEl0TWtEZgpnU3dmOW9WTCtHa1JBb3l1S1hvalFLNWwxclJDS0hMK1dNZGt1T1dkcmpSRUg1ME5VVWdQZEpKQmEycU5mSmJZCjJaamdNVk5KL0tjWDljV3pTMm1PRFhUemU1SW4zRkxhY0ZuT3I0eVYrRGZPRURxN2lTazhqRWV3TkRXSnErOTIKbmZ5aDkyTFZQTnZBeThjckNpbEZ4U3M0OW5iQVplMWs0NWZrOFpMcGtVWGppWGR4aHZRd2hBUlM2QXZzWkJXYwo3cG1hdmhIQ0VDWDh2a2tyNUc3aTFZd1A3Rk8yamc3N3VBNzNpNHI2aUFJelg1U2MrbGNaS0Y3Ynl6Y1dhMGUyCkVXbVVrRDJOK3dJREFRQUJvMll3WkRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIKL3dJQkFqQWRCZ05WSFE0RUZnUVVsOEJXV1YvdVRsTTZQZ3pwaVJ1MEt3Y0FKL293SHdZRFZSMGpCQmd3Rm9BVQpsOEJXV1YvdVRsTTZQZ3pwaVJ1MEt3Y0FKL293RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUpSVEZCWS95SDBrCmp3Um9FU1VtVGFVVGcwY0FzYXpxS3c1NmxGTStZLzZNay93M0MrUGxKa2dSVmloQmttbSs4WFJ6VTRrZTNVWVIKUm5QUWh4MlZqVmZWS3Y3dmQrN2lJekcwS01Selo1eHRqbys1dHdqWnBYZjdNaVZacUc2Q2VXenhZeUZjQktaaApObkpIREtzbGlFQWNPcEdGMHA4OEZoUUc0VnRLb0hnaC92MnFaZUlwemRZZ2dqQUhFWTZVM1BaVWR0eEFJSEV3CjhCYTJnS0NWMFl5ZE01MCtsd0dQWWF2bHoxUjlWckYxWE1lYVN1RzduM0NyYjdOMG9ncERxaG5RajdWOFFHeWQKN0xUK1NwOTQ5Ti9vOUNBbWVDVlQ2aExnaHlUWDNXOU5wYjVlcVZmNHBoRHJ6OVVvd01CbmU1eFJzcW1NTXJibQpmZC93bWJYdUV2Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://xx.xx.xx.xx:6443
  name: kubernetes-xxx
contexts:
- context:
    cluster: kubernetes-xxx
    user: kubelet-bootstrap
  name: default
current-context: ""
kind: Config
preferences: {}
users:
- name: kubelet-bootstrap
  user:
    token: f590b80bd982286368edaaf34e2a9270

**Comment by pranavrajtyagi** [comment]
I am getting the same error.  +1

**Comment by RRAlex** [comment]
Not sure if that'll help, but the only difference I see with mine is: 
`current-context: default`

**Comment by tevren** [comment]
@RRAlex's solution worked for me.

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
