### ISSUE TITLE
`gcloud compute target-pools create kubernetes-target-pool` does not work

### ISSUE THREAD

**Issue by loffelmacher** [kelseyhightower/kubernetes-the-hard-way#164]
This sounds a little bit like another issue I ran into at the beginning of the walk-through, where an apparent bug with `gcloud` is mixing up zone/region. 

When I run the `gcloud compute target-pools create kubernetes-target-pool --http-health-check=kube-apiserver-health-check` step I'm getting back this message: 

```
ERROR: (gcloud.compute.target-pools.create) Some requests did not succeed:
 - Invalid value for field 'region': 'us-central1-a'. Unknown region.
```

So I tried it "by-hand" in the Cloud Console. This allowed me to make the target pool just fine, but now the step where one creates the forwarding-rules, that is not working for me now.

**Comment by gamename** [comment]
I'm getting the same error here too:
```
$ gcloud compute networks subnets create kubernetes \
  --network kubernetes-the-hard-way \
  --range 10.240.0.0/24
ERROR: (gcloud.compute.networks.subnets.create) Some requests did not succeed:
 - Invalid value for field 'region': 'us-central1-f'. Unknown region.
```

**Comment by mkorejo** [comment]
I think this is a regression in the `gcloud compute` CLI where it sees the zone and considers it a region. I noticed this in Lab 1 when creating a subnet and Lab 5 when creating targeting pools. You can get past this simply by specifying the region manually with `--region`. Example:

`gcloud compute networks subnets create kubernetes --network kube-the-hard-way --range 10.240.0.0/24 --region us-central1`

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
