### ISSUE TITLE
create clusterrolebinding not working

### ISSUE THREAD

**Issue by gamename** [kelseyhightower/kubernetes-the-hard-way#167]
This is in reference to `06-kubernetes-worker.md`, under the "Prerequisites" section.  When run on my controller0, the command 
```
kubectl create clusterrolebinding kubelet-bootstrap \
  --clusterrole=system:node-bootstrapper \
  --user=kubelet-bootstrap
```
gives this error:
```
kubectl create clusterrolebinding kubelet-bootstrap \
>   --clusterrole=system:node-bootstrapper \
>   --user=kubelet-bootstrap
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by mkorejo** [comment]
There is some problem here in your setup, I think. What does `kubectl get cs` output on each controller node? Check that kube-apiserver, kube-scheduler, and kube-controller-manager are running properly on each controller node with `sudo systemctl status kube-apiserver`, etc.

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.

**Comment by XinchenWan** [comment]
@kelseyhightower @mkorejo

**Comment by nippip** [comment]
@XinchenWan "Disclaimer: I will always be learning K8s", however, I am going to take a guess at your question.  
I am thinking that if you have kubectl installed on the node and KUBECONFIG=/path_to_your_kubeconfig defined then it should work. 
Do you have a proxy set?  If you do can run a curl test to check for connectivity as mentioned [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/http-proxy-access-api/).
My logic here is that on each node the kubelet is installed and that communicates with the API controller so one way or another you should be able to get kubectl working.
One other thought is to use tcpdump to examine how the kubelet is communicating with the API controller and then try to mimic that connection.
Would you please let me know what you discover?  -- Nippip

**Comment by XinchenWan** [comment]
@nippip Thanks so much for your suggestion. I will run it in a few days and have a discussion with you.
