### ISSUE TITLE
 Can you tell me how to configure the overlay network in a non gce environment?

### ISSUE THREAD

**Issue by moonek** [kelseyhightower/kubernetes-the-hard-way#171]
I get great information about how to install kubernetes cluster.
All other parts are well resolved, but the overlay network configuration of the manual is locked-in to gce.
Can you tell me how to configure an overlay network such as flanneld in a pure baremetal environment without cloud dependencies?
I can not use apt-get, yum repo because the internet is blocked.

(Added)
I installed the K8S Cluster according to this guide.
There is nothing wrong with pod creation and all commands via kubectl.
And then, I manually installed the flanneld.
But my problem is that I can't access NodePort from other nodes. (This is possible on the same node where the Pod is running.)
It seems that the overlay network is not properly configured.
Could you advise me on my configurations?

Environmental Information
--------------------------------------------------------------------------------
Vagrant + VirtualBox
OS: ubuntu/xenial64
Master&ETCD: 172.28.128.41
Worker1, 2: 172.28.128.42, 172.28.128.43

docker.service (Worker1)
--------------------------------------------------------------------------------
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.io

[Service]
ExecStart=/usr/bin/docker daemon \
  --iptables=false \
  --ip-masq=false \
  --host=unix:///var/run/docker.sock \
  --log-level=error \
  --storage-driver=overlay \
  --bip=10.200.96.1/24 \
  --mtu=1450
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

flanneld.service (Worker1)
--------------------------------------------------------------------------------
[Unit]
Description=Flanneld overlay address etcd agent
After=network.target
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
EnvironmentFile=-/etc/default/flanneld
ExecStart=/usr/bin/flanneld --public-ip=172.28.128.42 -etcd-endpoints=http://172.28.128.41:2379 -etcd-prefix=/kubernetes-cluster/network $FLANNEL_OPTIONS
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service

/var/run/flannel/subnet.env (Worker1)
--------------------------------------------------------------------------------
FLANNEL_NETWORK=10.200.0.0/16
FLANNEL_SUBNET=10.200.96.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false

kubelet.service (Worker1)
--------------------------------------------------------------------------------
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
ExecStart=/usr/bin/kubelet \
  --api-servers=https://172.28.128.41:6443 \
  --allow-privileged=true \
  --cluster-dns=10.32.0.10 \
  --cluster-domain=cluster.local \
  --container-runtime=docker \
  --experimental-bootstrap-kubeconfig=/var/lib/kubelet/bootstrap.kubeconfig \
  --kubeconfig=/var/lib/kubelet/kubeconfig \
  --serialize-image-pulls=false \
  --register-node=true \
  --tls-cert-file=/var/lib/kubelet/kubelet-client.crt \
  --tls-private-key-file=/var/lib/kubelet/kubelet-client.key \
  --cert-dir=/var/lib/kubelet \
  --v=2 \
  --node-ip=172.28.128.42
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

kube-proxy.service (Worker1)
--------------------------------------------------------------------------------
[Unit]
Description=Kubernetes Kube Proxy
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/usr/bin/kube-proxy \
  --cluster-cidr=10.200.0.0/16 \
  --masquerade-all=true \
  --kubeconfig=/var/lib/kube-proxy/kube-proxy.kubeconfig \
  --proxy-mode=iptables \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

ip addr show (Worker1)
--------------------------------------------------------------------------------
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:d8:e4:47:7a:33 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::d8:e4ff:fe47:7a33/64 scope link
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:48:2f:16 brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.42/24 brd 172.28.128.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe48:2f16/64 scope link
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 56:7d:bf:97:b8:ee brd ff:ff:ff:ff:ff:ff
    inet 10.200.96.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::547d:bfff:fe97:b8ee/64 scope link
       valid_lft forever preferred_lft forever
8: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:45:f7:af:61 brd ff:ff:ff:ff:ff:ff
    inet 10.200.96.1/24 scope global docker0
       valid_lft forever preferred_lft forever

**Comment by pashok2398** [comment]
The overlay networking configured by the kubenet CNI plugin (--network-plugin=kubenet)
I used this guide to create Bare-Metal cluster on private network.
You can find more here https://kubernetes.io/docs/concepts/cluster-administration/networking/ about other plugins...

**Comment by moonek** [comment]
I am trying to integrate flanneld into the k8s 1.6 installed with this guide, but it is not working.

**Comment by domix** [comment]
With k8s `v1.7.0-alpha.4` I successfully installed flannel on baremetal and working fine

**Comment by moonek** [comment]
@domix Could you advise me on my configurations?

Environmental Information
--------------------------------------------------------------------------------
Vagrant + VirtualBox
Master&ETCD: 172.28.128.41
Worker1, 2: 172.28.128.42, 172.28.128.43

docker.service (Worker1)
--------------------------------------------------------------------------------
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.io

[Service]
ExecStart=/usr/bin/docker daemon \
  --iptables=false \
  --ip-masq=false \
  --host=unix:///var/run/docker.sock \
  --log-level=error \
  --storage-driver=overlay \
  --bip=10.200.96.1/24 \
  --mtu=1450
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

flanneld.service (Worker1)
--------------------------------------------------------------------------------
[Unit]
Description=Flanneld overlay address etcd agent
After=network.target
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
EnvironmentFile=-/etc/default/flanneld
ExecStart=/usr/bin/flanneld --public-ip=172.28.128.42 -etcd-endpoints=http://172.28.128.41:2379 -etcd-prefix=/kubernetes-cluster/network $FLANNEL_OPTIONS
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service

kubelet.service (Worker1)
--------------------------------------------------------------------------------
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
ExecStart=/usr/bin/kubelet \
  --api-servers=https://172.28.128.41:6443 \
  --allow-privileged=true \
  --cluster-dns=10.32.0.10 \
  --cluster-domain=cluster.local \
  --container-runtime=docker \
  --experimental-bootstrap-kubeconfig=/var/lib/kubelet/bootstrap.kubeconfig \
  --kubeconfig=/var/lib/kubelet/kubeconfig \
  --serialize-image-pulls=false \
  --register-node=true \
  --tls-cert-file=/var/lib/kubelet/kubelet-client.crt \
  --tls-private-key-file=/var/lib/kubelet/kubelet-client.key \
  --cert-dir=/var/lib/kubelet \
  --v=2 \
  --node-ip=172.28.128.42
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target


ip addr show (Worker1)
--------------------------------------------------------------------------------
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:d8:e4:47:7a:33 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::d8:e4ff:fe47:7a33/64 scope link
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:48:2f:16 brd ff:ff:ff:ff:ff:ff
    inet 172.28.128.42/24 brd 172.28.128.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe48:2f16/64 scope link
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 56:7d:bf:97:b8:ee brd ff:ff:ff:ff:ff:ff
    inet 10.200.96.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::547d:bfff:fe97:b8ee/64 scope link
       valid_lft forever preferred_lft forever
8: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:45:f7:af:61 brd ff:ff:ff:ff:ff:ff
    inet 10.200.96.1/24 scope global docker0
       valid_lft forever preferred_lft forever

**Comment by moonek** [comment]
@domix 
I wrote my setup information in the body.
Could you advise me on my configurations?

**Comment by moonek** [comment]
I solved the problem.
The cause was the virtualbox network interface.
The problem was solved by putting "-iface=enp0s8" as the flanneld option.
