### ISSUE TITLE
smoke-test not working / kube-proxy not starting

### ISSUE THREAD

**Issue by Strange-Account** [kelseyhightower/kubernetes-the-hard-way#173]
Hi,

there seems to miss some config for the kube-proxy service. I get the following error:

May 30 14:38:57 worker2 systemd[1]: kube-proxy.service: Service hold-off time over, scheduling restart.
May 30 14:38:57 worker2 systemd[1]: Stopped Kubernetes Kube Proxy.
May 30 14:38:57 worker2 systemd[1]: Started Kubernetes Kube Proxy.
May 30 14:38:57 worker2 kube-proxy[21481]: I0530 14:38:57.440296   21481 server.go:173] setting OOM scores is unsupported in this build
**May 30 14:38:57 worker2 kube-proxy[21481]: invalid configuration: no server found for cluster "kubernetes-the-hard-way"**
May 30 14:38:57 worker2 systemd[1]: kube-proxy.service: Main process exited, code=exited, status=1/FAILURE
May 30 14:38:57 worker2 systemd[1]: kube-proxy.service: Unit entered failed state.
May 30 14:38:57 worker2 systemd[1]: kube-proxy.service: Failed with result 'exit-code'.

After i added the "cluster" entry from the bootstrap.kubeconfig to the kube-proxy.kubeconfig it seems to work.

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
