### ISSUE TITLE
Kubernetes API server RBAC related udpates

### ISSUE THREAD

**Issue by archyufa** [kelseyhightower/kubernetes-the-hard-way#177]
In 1.6 RBAC has been moved beta, therefore below configurations needs to be updated:
L126:  --runtime-config=rbac.authorization.k8s.io/v1alpha1 \\

I'm not 100% sure if we need just remove this line or update to beta1. 
So far I have not seen any cluster with RBAC who has runtime-config option with RBAC.

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
