### ISSUE TITLE
Add details about creating kubelet-client.crt

### ISSUE THREAD

**Issue by variadico** [kelseyhightower/kubernetes-the-hard-way#187]
On this page

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/06-kubernetes-worker.md

there is a unit file with this `ExecStart`.

```
ExecStart=/usr/bin/kubelet \\
  --api-servers=${API_SERVERS} \\
  --allow-privileged=true \\
  --cluster-dns=10.32.0.10 \\
  --cluster-domain=cluster.local \\
  --container-runtime=docker \\
  --experimental-bootstrap-kubeconfig=/var/lib/kubelet/bootstrap.kubeconfig \\
  --network-plugin=kubenet \\
  --kubeconfig=/var/lib/kubelet/kubeconfig \\
  --serialize-image-pulls=false \\
  --register-node=true \\
  --tls-cert-file=/var/lib/kubelet/kubelet-client.crt \\
  --tls-private-key-file=/var/lib/kubelet/kubelet-client.key \\
  --cert-dir=/var/lib/kubelet \\
  --v=2
```

Where are `/var/lib/kubelet/kubelet-client.crt` coming from? I searched the rest of the repo, but I didn't see anything that talked about how to create that file. Seems like there is some detail missing there.

**Comment by nkaravias** [comment]
That certificate is generated automatically by the boostrap process you enabled with this line:
`  --experimental-bootstrap-kubeconfig=/var/lib/kubelet/bootstrap.kubeconfig \\
`

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
