### ISSUE TITLE
Intermittent firewall issue in smoke test

### ISSUE THREAD

**Issue by mercer** [kelseyhightower/kubernetes-the-hard-way#190]
After finishing lab 10, smoke test, i get inconsistent connectivity to nginx.

Note that I'm able to see nginx landing page from time to time.

Please see an nmap log that oscillates from open to filtered: [kubernetes-the-hard-way-filtered.txt](https://github.com/kelseyhightower/kubernetes-the-hard-way/files/1155948/kubernetes-the-hard-way-filtered.txt)

![image](https://user-images.githubusercontent.com/95358/28318974-420cdda4-6bd5-11e7-963e-2e0ffe05df48.png)

![image](https://user-images.githubusercontent.com/95358/28318905-0a390056-6bd5-11e7-9ccd-0124a180cf53.png)

![image](https://user-images.githubusercontent.com/95358/28318933-1f369f90-6bd5-11e7-8778-59a9576f3d7d.png)

**Comment by mercer** [comment]
Could be a duplicate of #151

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
