### ISSUE TITLE
mention of metadata.google.internal for "standalone" instructions

### ISSUE THREAD

**Issue by ldemailly** [kelseyhightower/kubernetes-the-hard-way#193]
https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-controller.md#kubernetes-api-server

```
INTERNAL_IP=$(curl -s -H "Metadata-Flavor: Google" \
  http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ip)
```
doesn't work outside gke ?

**Comment by ldemailly** [comment]
```
INTERNAL_IP=$(ip -4 -br address |awk '/UP/ {print $3}' | awk -F/ '{print $1}')
```
or some such seems simpler than making an outcall ? (which could return a NAT box addr)

**Comment by kelseyhightower** [comment]
No. You'll need to find another way to get the internal IP of your node.
