### ISSUE TITLE
Question about "healthz" source addresses

### ISSUE THREAD

**Issue by ftclausen** [kelseyhightower/kubernetes-the-hard-way#198]
In `01-infrastructure-gcp.md` we set up a firewall rule of

```
gcloud compute firewall-rules create allow-healthz \
  --allow tcp:8080 \
  --network kubernetes-the-hard-way \
  --source-ranges 130.211.0.0/22,35.191.0.0/16
```

with a hard coded set of public networks - what are these?

**Comment by trescst** [comment]
These are the IP addresses/ranges of the loadbalancers and health checkers.  When your healthz endpoint gets probed (to check its health) the health probes originate from these addresses.

For more details check:
- https://cloud.google.com/compute/docs/load-balancing/http/#components (Firewall rules)
- https://cloud.google.com/compute/docs/load-balancing/health-checks#update_a_health_check

**Comment by kelseyhightower** [comment]
I've updated all the docs. This is explained in the docs now with links.
