### ISSUE TITLE
gcloud filter syntax change?

### ISSUE THREAD

**Issue by calebhailey** [kelseyhightower/kubernetes-the-hard-way#199]
Hi @kelseyhightower! 👋 

Thanks for your hard work in putting this guide together! In working through it I encountered what looks like a syntax change in the `gcloud` CLI or Google APIs. A `gcloud --version` tells me I'm using `Google Cloud SDK 168.0.0` which I just downloaded today, so presumably it's not an outdated version? Anyway, it complained when I tried to list my firewall rules via: 

```
$ gcloud compute firewall-rules list --filter "network=kubernetes-the-hard-way"

WARNING: filter : operator evaluation is changing for consistency across Google APIs. 
network=kubernetes-the-hard-way does not match but will match in the near future. 
Run 'gcloud topics filters' for details. 
```

Based on that warning it looks like a change may not be needed, because the `network=kubernetes-the-hard-way` syntax will eventually work (?); but I had to modify it to use a colon (`:` instead of `=`) to get it to work, per the instructions provided via `gcloud topic filters`. 

```
gcloud compute firewall-rules list --filter network:kubernetes-the-hard-way
```

That did the trick for me, just FYI. 

Thanks again for sharing your knowledge! 🙌

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
