### ISSUE TITLE
Kubernetes server certificate and new node problem

### ISSUE THREAD

**Issue by minhdanh** [kelseyhightower/kubernetes-the-hard-way#204]
Assuming that I have successfully installed a Kubernetes cluster.
Now I need to add a new worker node to that cluster. But as the new node has a new IP address, so the certificate that generated at this step https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/02-certificate-authority.md#create-the-kubernetes-server-certificate doesn't include the new IP. This means that the communication part from the Kubernetes master to the new kubelet node may experience problem. So in this case, what will be the best way to add a new node to a running cluster?

**Comment by pashok2398** [comment]
@minhdanh Workers are not mentioned in csr, only masters, in the step you mention you creating certs for master/loadBalancer ip/dns names only.
The cluster trusting all certs that signed by you ca that you create in the first step, this mean that you workers just need to be signed with your ca what described and done automatically in https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/06-kubernetes-worker.md at "Approve the TLS certificate requests"

**Comment by minhdanh** [comment]
Oh, sorry it was my mistake as I thought the IPs of the controllers were of the workers. Closing this now. Thank you!
