### ISSUE TITLE
Provisioning certs the kubeadm way

### ISSUE THREAD

**Issue by Promaethius** [kelseyhightower/kubernetes-the-hard-way#213]
Your guide is incredibly helpful for starters.

Could you possibly include in your guide all the components necessary to provision certificates from these kubernetes.io guides? Not only for myself, who has had a hard time understanding these concepts, but for others who are looking to make HA, auto-tls stacks.

https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/
https://kubernetes.io/docs/admin/bootstrap-tokens/

**Comment by kelseyhightower** [comment]
I will revisit this when bootstrap tokens go GA.
