### ISSUE TITLE
Incorrect field selected when getting the public IP

### ISSUE THREAD

**Issue by seeafish** [kelseyhightower/kubernetes-the-hard-way#214]
Hi Kelsey,

In https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md on line 219 you have this snippet:

```
KUBERNETES_PUBLIC_ADDRESS=$(gcloud compute addresses describe kubernetes-the-hard-way \
  --region $(gcloud config get-value compute/region) \
  --format 'value(name)')
```

The `--format` line grabs the name of the address, not the address itself. This means that `KUBERNETES_PUBLIC_ADDRESS` ends up with a value of `kubernetes-the-hard-way` rather than an IP address.
This was correct before your recent refresh of the docs.

Thanks.

**Comment by kelseyhightower** [comment]
Fixed on master. Thanks for reporting this.
