### ISSUE TITLE
Insecure port is exposed on all interfaces

### ISSUE THREAD

**Issue by jeroenjacobs1205** [kelseyhightower/kubernetes-the-hard-way#215]
Hi,

In the control pane section, you expose the apiserver the insecure port on all interfaces:

`--insecure-bind-address=0.0.0.0`

Since the insecure port is only used by the kube-controller-manager and kube-scheduler, which use the loopback adapter to connect to the api-server, it would be a lot safer to use:

`--insecure-bind-address=127.0.0.1`

This little change will result in a cluster which is a lot more secure, without any side-effects.

**Comment by bgeesaman** [comment]
https://github.com/kelseyhightower/kubernetes-the-hard-way/pull/208

You saw the same thing I did.  It's in this PR waiting to be tested/merged.

**Comment by kelseyhightower** [comment]
Fixed! This is the configuration on master (tagged 1.8) and will remain the setting going forward. We also enabled `--authorization-mode=Webhook` on the kubelet.
