### ISSUE TITLE
Featureish request: A dedicated reddit would be useful

### ISSUE THREAD

**Issue by marchuobi** [kelseyhightower/kubernetes-the-hard-way#217]
Hi,

Thanks for all the work you put into this, it is very helpful.

It would be nice to have answers pile up in one place for future reference,  
https://www.reddit.com/r/kubernetes-the-hard-way for example.

For example I am having some issues bridging the gap for the differences between a local vmware test env and the google cloud env.  In chapter 9 configure-cni-networking section I am having a bit of trouble translating POD_CIDR into a cidr network for each worker node.  I am sure I am missing something basic here and it really is not a good issue for a ticket.  

I am happy to create and admin it if that helps, would you be willing to put a link up in the project to feed people to it?

Thanks,

Marc

**Comment by tokiwinter** [comment]
👎 Aren't GH issues the right place for this anyway? Please don't move anything anywhere near reddit! If the question isn't hard way specific, then off to upstream/IRC/Slack/whatever it goes?

**Comment by marchuobi** [comment]
I find reddit much more useful for finding answers without asking questions than irc or slack.  My original, now resolved, issue was not so much a issue with the guide as much as applying it somewhere else that is different.  It is fair to say that we are using google cloud and other things are out of scope.  This is exactly the kind of thing that a reddit would be great at handling.  

Opening a ticket in my mind implies a defect to be resolved or a gap to be closed.  Neither was present in my opinion about my issue, I just was ignorant about what I needed to do on a platform that was out of scope.  Kubernetecs is a big lump to swallow at first and having all these out of scope details will in the main doc will make it harder to follow the core issue of getting things up and running for most of the people using the doc.   

There are very specific points that need to be addressed on how kubernetecs interacts with different envs and that is where reddit would shine

**Comment by tokiwinter** [comment]
Fair point, I just like the idea of keeping everything kthw-related right here at kelseyhightower/kubernetes-the-hard-way. All resources in one place. k8s itself - that's a different beast in terms of community and support.

**Comment by marchuobi** [comment]
I am fine with keeping everything that is in the scope of the project here, but aws and vmware are not in scope.  For things that are not in scope but happen a lot, adapting to not google cloud having one blessed if not official place is much preferred to having it spread out over half a dozen or more sites.  And who is to say that in time the Q&A will not lead to a AWS or VMWare faq

**Comment by bgeesaman** [comment]
Suggest you fork the repo, make the necessary changes to make it work in VMWare, and then link to your repo from here.  Issues related to this guide are here, and issues related to your implementation are handled how you see fit.

**Comment by kelseyhightower** [comment]
This repo is for learning and the distro, VM platform does not matter. The focus is on Kubernetes.
