### ISSUE TITLE
non-GCE platforms networking dose not work following the tutorial

### ISSUE THREAD

**Issue by marchuobi** [kelseyhightower/kubernetes-the-hard-way#218]
Out of scope but the kubernetecs networking works out of the box on GCE, would it be possible to emphasize that  you need to install more software to get this working in the prerequisites page? 

Thanks

**Comment by kelseyhightower** [comment]
GCE networking requires routes to be setup, so it does not work out of the box. When it comes to other environments "it depends". I want to keep this guide focused and maintainable. I'm only offering one way to do it.
