### ISSUE TITLE
why is localhost etcd http?

### ISSUE THREAD

**Issue by marchuobi** [kelseyhightower/kubernetes-the-hard-way#220]
I was trying to get things working and the interaction of etcdctl and the mix of http on local host and https on my non localhost ips is problematic, setting up things for http and I get redirected to non localhost from localhost where it dies and setting it up for https means the default ip does not work.  Is there a reason for this that I missed? It works much better when everything is https on a controller node

**Comment by kelseyhightower** [comment]
Ideally everything should work if you use the instance internal IP. Localhost is enable for running etcdctl on the local machines -- going for ease of use.

**Comment by tokiwinter** [comment]
fwiw, I use https on both listen addresses (localhost and my internal IP) and with the appropriate environment variables in `~/.bashrc` it's no hassle to use `etcdctl`.
```
export ETCDCTL_API=3
export ETCDCTL_ENDPOINTS="https://127.0.0.1:2379"
export ETCDCTL_CACERT="/etc/etcd/ca.pem"
export ETCDCTL_CERT="/etc/etcd/client.pem"
export ETCDCTL_KEY="/etc/etcd/client.key"
```
Unrelated, I also run `etcd` under an unprivileged user and group. Trying to be as secure as I can wherever I can.

**Comment by kelseyhightower** [comment]
@tokiwinter No doubt! I'm going to do a big security update in the coming week of this entire guide.
