### ISSUE TITLE
Unable to register node "worker-0" with API server

### ISSUE THREAD

**Issue by lonefreak** [kelseyhightower/kubernetes-the-hard-way#228]
During the "Bootstrapping the Kubernetes Worker Nodes" (on the 1.7.4 tag) I cannot register a node. Could you please help me know what is going on?

kubelet keeps telling me 

`Unable to register node "worker-0" with API server: User "system:node:" cannot create nodes at the cluster scope.: "unknown node for user \"system:node:\"" (post nodes)`

`/var/lib/kubelet/kubeconfig` seems to be ok, since it is configured for the correct user:

```
users:
- name: system:node:worker-0
```
The error seems to be thrown by node_authorizer, as can be seem here:

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/node/node_authorizer.go#L75

Also certs were generated correctly and are present where kubelet is looking for them.

**Comment by lonefreak** [comment]
Update:

I followed my idea that this could has something to do with the node_authorizer and managed to make it work by removing `NodeRestriction` from `--admission-control` and leaving only `RBAC` in `--authorization-mode=RBAC`

**Comment by kelseyhightower** [comment]
I've updated and tested this guide for 1.8 and 1.9. In both versions everything should be working.

**Comment by YZerg** [comment]
@lonefreak thanks you a lot for this advice :)

**Comment by bithavoc** [comment]
the name of the hostname where kubelet is running needs to match the hostname passed to `cfssl gencert ... -hostname=` and `"CN": "system:node:${instance}"` in the -csr.json file.

**Comment by RamanPndy** [comment]
> Update:
> 
> I followed my idea that this could has something to do with the node_authorizer and managed to make it work by removing `NodeRestriction` from `--admission-control` and leaving only `RBAC` in `--authorization-mode=RBAC`

Thanks @lonefreak This solution works for me. I can see now my worker nodes and master nodes in cluster. but i want to understand the logic of these flags and why these are getting used. Please help me to understand the purpose of NodeRestriction.

**Comment by NickJLange** [comment]
> the name of the hostname where kubelet is running needs to match the hostname passed to `cfssl gencert ... -hostname=` and `"CN": "system:node:${instance}"` in the -csr.json file.

This helped., Thank you.  
NB for Google: If you have a bad CN value, in addition to re-generating the certs, you need to generate the kubeconfig file for the corrected CN to be picked up by kubelet.
