### ISSUE TITLE
is kubectl required on the worker nodes ?

### ISSUE THREAD

**Issue by tsugliani** [kelseyhightower/kubernetes-the-hard-way#23]
In the [05-kubernetes-worker](kubernetes-the-hard-way/docs/05-kubernetes-worker.md) guide we install `kubectl`, but to my current understanding, only `kubelet`, `kube-proxy` and `docker` are required. 
To me all the communications happens between the kubernetes master `kube-apiserver` <-> and the `kubelet` agent as shown in the architecture diagram below:
![Kubernetes Architecture](https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/design/architecture.png?raw=true)

Can anyone clarify what `kubectl` is for on the worker nodes ?

Thanks in advance,

**Comment by ae6rt** [comment]
I suspect it's a just convenience.  It is not strictly required really anywhere, but on your admin desktop to perform general cluster control.

**Comment by tsugliani** [comment]
@ae6rt ok thanks I just wanted to be sure, `kubelet` didn't call somehow `kubectl` in the backend for specific tasks or anything.

**Comment by kelseyhightower** [comment]
@tsugliani That's right kubectl is not required and I install it as a nice to have. That way from any machine, with the right permissions, you can use kubectl.

**Comment by ZW007** [comment]
@kelseyhightower May I ask how can I get kubectl works on the worker node in a local cluster? I suspect I should have the somethings called kubeconifg but I don't know how.

**Comment by andrei-bamboi** [comment]
> @kelseyhightower May I ask how can I get kubectl works on the worker node in a local cluster? I suspect I should have the somethings called kubeconifg but I don't know how.

@ZW007 the easy way to do it is to copy the config from master node usually found here : /etc/kubernetes/admin.conf , to whetever node you want to configure kubectl ( even on master node) . The location to be copied is : $HOME/.kube/config .

**Comment by nttlong** [comment]
> > @kelseyhightower May I ask how can I get kubectl works on the worker node in a local cluster? I suspect I should have the somethings called kubeconifg but I don't know how.
> 
> @ZW007 the easy way to do it is to copy the config from master node usually found here : /etc/kubernetes/admin.conf , to whetever node you want to configure kubectl ( even on master node) . The location to be copied is : $HOME/.kube/config .

can I copy /etc/kubernetes/admin.conf  to worker node via SSH?
