### ISSUE TITLE
suggestion: make select/copy-paste a bit easier

### ISSUE THREAD

**Issue by petermd** [kelseyhightower/kubernetes-the-hard-way#231]
thanks again for creating such a useful resource!

i did find copy/pasting a bit finicky so was wondering if you'd considered using github pages to render the docs and customizing a little?

by way of example, i did a [quick patch](https://github.com/petermd/kubernetes-the-hard-way/commit/c6ab199fc71d727b92716c442286e14c9844cda9) that renders using a tweaked layout and adds a little javascript hack to auto-highlight a complete code block when you click anywhere on it.

the auto-generated site at [https://petermd.github.io/kubernetes-the-hard-way/](https://petermd.github.io/kubernetes-the-hard-way/04-certificate-authority.html) shows how it would look

**Comment by kelseyhightower** [comment]
This is pretty nice, but I won't have the time to actively maintain this. I'm opening to you hosting such a site.

**Comment by petermd** [comment]
Sorry Kelsey, hope you don't think I was trying to make more work for you!

Making the `/docs` tree render as a site is just [a github setting](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch), the only change I made is to tweak the default layout and include the "auto-select" javascript.
