### ISSUE TITLE
K8S the hardway setup using console-GKE/GCP only - possible?

### ISSUE THREAD

**Issue by mamudragon** [kelseyhightower/kubernetes-the-hard-way#232]
Not really an issue, does the console of GCP support setting up K8S the hard way? or Is gcloud cloud shell or CLI the only option?

Right now, GKE on GCP supports 1.7.6 version, I started my300$ Free Tier today and hence the above Question.

Thanks

**Comment by kelseyhightower** [comment]
I used the shell to ensure a step by step experience that's easy for me to test and others to replicate. For the most part you can do almost everything using the GCP console, but I would have to create a ton of screenshots to provide a step by step guide.

**Comment by mamudragon** [comment]
Perhaps, a video recording to YouTube might help for newbies likeme. Thanks.
