### ISSUE TITLE
Node fails to register with kube-apiserver

### ISSUE THREAD

**Issue by guillierf** [kelseyhightower/kubernetes-the-hard-way#237]
all configs were OK until configuring the worker node.

when trying to start the kubelet service, I got these messages:

root@worker-0:~# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-10-09 16:33:15 PDT; 18h ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 1134 (kubelet)
    Tasks: 13
   Memory: 80.6M
      CPU: 8min 12.656s
   CGroup: /system.slice/kubelet.service
           └─1134 /usr/local/bin/kubelet --allow-privileged=true --anonymous-auth=false --authorization-mode=Webhook --client-ca-file=/var/lib/kuber

Oct 10 11:24:12 worker-0 kubelet[1134]: E1010 11:24:12.550039    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:422: Failed to list
Oct 10 11:24:13 worker-0 kubelet[1134]: E1010 11:24:13.548517    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed
Oct 10 11:24:13 worker-0 kubelet[1134]: E1010 11:24:13.549546    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:413: Failed to list
Oct 10 11:24:13 worker-0 kubelet[1134]: E1010 11:24:13.550613    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:422: Failed to list
Oct 10 11:24:14 worker-0 kubelet[1134]: E1010 11:24:14.549782    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed
Oct 10 11:24:14 worker-0 kubelet[1134]: E1010 11:24:14.550475    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:413: Failed to list
Oct 10 11:24:14 worker-0 kubelet[1134]: E1010 11:24:14.551434    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:422: Failed to list
Oct 10 11:24:15 worker-0 kubelet[1134]: E1010 11:24:15.550953    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed
Oct 10 11:24:15 worker-0 kubelet[1134]: E1010 11:24:15.551943    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:413: Failed to list
Oct 10 11:24:15 worker-0 kubelet[1134]: E1010 11:24:15.553063    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:422: Failed to list

/var/log/syslog:
Oct 10 11:23:38 worker-0 kubelet[1134]: E1010 11:23:38.527259    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:413: Failed to list *v1.Service: Get https://=10.40.207.40:6443/api/v1/services?resourceVersion=0: dial tcp: lookup =10.40.207.40: no such host
Oct 10 11:23:38 worker-0 kubelet[1134]: E1010 11:23:38.528414    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:422: Failed to list *v1.Node: Get https://=10.40.207.40:6443/api/v1/nodes?fieldSelector=metadata.name%3Dworker-0&resourceVersion=0: dial tcp: lookup =10.40.207.40: no such host
Oct 10 11:23:39 worker-0 kubelet[1134]: E1010 11:23:39.526648    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://=10.40.207.40:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dworker-0&resourceVersion=0: dial tcp: lookup =10.40.207.40: no such host
Oct 10 11:23:39 worker-0 kubelet[1134]: E1010 11:23:39.527603    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:413: Failed to list *v1.Service: Get https://=10.40.207.40:6443/api/v1/services?resourceVersion=0: dial tcp: lookup =10.40.207.40: no such host
Oct 10 11:23:39 worker-0 kubelet[1134]: E1010 11:23:39.528796    1134 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:422: Failed to list *v1.Node: Get https://=10.40.207.40:6443/api/v1/nodes?fieldSelector=metadata.name%3Dworker-0&resourceVersion=0: dial tcp: lookup =10.40.207.40: no such host

thanks in advance

**Comment by jeromepin** [comment]
Logs shows you have a typo : 

`Get https://=10.40.207.40:6443/api/v1/services?resourceVersion=0: dial tcp: lookup =10.40.207.40`

Somewhere in your configuration files, you have an `=` which should be there.

**Comment by zatricky** [comment]
Minor typo from @jeromepin: "you have an `=` which should **not** be there"
`=10.40.207.40` is an invalid address. It is trying to do a DNS lookup and failing. If you remove the `=`, it will go to the address directly instead of attempting a bad lookup.

**Comment by guillierf** [comment]
@jeromepin @zatricky 
thanks a lot !
it was the root cause (I misconfigured the worker-x.kubeconfig file)
now, everything works fine.

**Comment by kelseyhightower** [comment]
Looks like this is resolved. Thanks @zatricky @jeromepin.

**Comment by batibm** [comment]
in our case restarting nginx lb and solved the issue

**Comment by aparnamartin** [comment]
We have encountered similar and issue and is resolved after restarting nginx loadbalacer 

Apr 22 02:21:14 hostname.cloud kubelet[23297]: I0422 02:21:14.475362   23297 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
Apr 22 02:21:14 hostname.cloud kubelet[23297]: I0422 02:21:14.477224   23297 kubelet_node_status.go:79] Attempting to register node hostname.cloud
Apr 22 02:21:14 hostname.cloud kubelet[23297]: E0422 02:21:14.477651   23297 kubelet_node_status.go:103] Unable to register node "hostname.cloud" with API server: Post https://ip:16443/api/v1/nodes: dial tcp ip:16443: connect: connection refused
Apr 22 02:21:14 hostname.cloud kubelet[23297]: E0422 02:21:14.941380   23297 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Get https://ip:16443/api/v1/nodes?fieldSelector=metadata.name%3Dhostname.cloud&limit=500&resourceVersion=0: dial tcp ip:16443: connect: connection
