### ISSUE TITLE
config file for cfssl gencert 

### ISSUE THREAD

**Issue by DenisBiondic** [kelseyhightower/kubernetes-the-hard-way#239]
In the section on generating admin client certificate, there is a command which requires a config file which is not there. 

Is this missing or I missed a step somehow?

fssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json  --- where does this config file come from?

**Comment by schu** [comment]
@DenisBiondic that file is created here: https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#certificate-authority (`cat > ca-config.json <<EOF ...`)

**Comment by DenisBiondic** [comment]
Grrr ... I've deleted it via some bash move magic I made in between. Sorry for the silly question
