### ISSUE TITLE
Status of recommendation to host etcd on dedicated machines?

### ISSUE THREAD

**Issue by geekofalltrades** [kelseyhightower/kubernetes-the-hard-way#240]
@kelseyhightower , in the past, you've recommended in this guide that etcd should be hosted on a separate, dedicated set of machines.

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-etcd.md#why

>In production environments etcd should be run on a dedicated set of machines for the following reasons:
> * The etcd lifecycle is not tied to Kubernetes. We should be able to upgrade etcd independently of Kubernetes.
> * Scaling out etcd is different than scaling out the Kubernetes Control Plane.
> * Prevent other applications from taking up resources (CPU, Memory, I/O) required by etcd.

The link to this recommendation seems to have come from this guide, but is now a 404. I've come across the link in a couple of different places the last few days.

Has your/Kubernetes' recommendation changed on hosting etcd on dedicated machines?

**Comment by stafot** [comment]
@kelseyhightower As follow-up of above question isn't a better idea to keep etcd instances seperate from kubernetes-core. If not can you elaborate why is it better to be these coupled in the controller instances?

**Comment by tokiwinter** [comment]
Probably because of simplicity, and this comment in README.md?

> Kubernetes The Hard Way is optimized for learning, which means taking the long route to ensure
> you understand each task required to bootstrap a Kubernetes cluster.
> The results of this tutorial should not be viewed as production ready, and may receive limited
> support from the community, but don't let that stop you from learning!

**Comment by zatricky** [comment]
In terms of performance (latency between controller and etcd), it is sensible to want etcd on the same hosts as the controllers - but only at small scales. In terms of HA it is certainly *simpler* to do it this way.

Again, however, @tokiwinter is spot on in pointing toward the purpose of the guide. This is not intended for production.

**Comment by kelseyhightower** [comment]
@tokiwinter and @zatricky thanks for the help here. I would run etcd on dedicated machines in a production setup, but that's not required. You have many options of how you want to run etcd. I'm just showing one path. Keep in mind I moved the etcd nodes to the controller nodes to help cut down on cost for people learning.

**Comment by stafot** [comment]
@kelseyhightower thank you very much for your clarification.
