### ISSUE TITLE
Why do we need to provide the client's private key to the etcd server

### ISSUE THREAD

**Issue by khaldoune** [kelseyhightower/kubernetes-the-hard-way#246]
Hi,
could somebody please explain why, when configuring a secure etcd cluster (step 7), we need to provide the client's private key (the private key of the api server in our case)? 

I've never seen this in HTTPS 2 way ssl, for me, this key should never go out of the server.

Thanks.

**Comment by tokiwinter** [comment]
The same certificate/key are being used for, I presume, simplicity in the tutorial. I obviously always set up entirely different certs/keys for etcd (and even peer cert/key), and do not use the API server's certs/keys. I even set up a separate cert/key for _each_ API server, and have a bunch of `etcd`-client cert/keys for each API server, and you can then use `etcd .. --client-crl-file` to allow revocation of a compromised client. I guess you can take this as a basic tutorial, and then secure as per best practices if you plan on using it in Production.

As per the comment right at the top of README.md:

> The results of this tutorial should not be viewed as production ready, and may receive limited
> support from the community, but don't let that stop you from learning!

**Comment by khaldoune** [comment]
Hi @tokiwinter, thanks for your answer. I agree with you, in production, we should do things like you describe.
But I still cannot understand the need of using the client key even for certificate revocation. In order to revoke a certificate using the CRL, the CA only needs the public key, it should be the same from the client side.
Sorry for insisting...

**Comment by tokiwinter** [comment]
@khaldoune - I agree with you, maybe you misunderstood my comment - my clients keys (and certs for that matter) do not go anywhere near my `etcd` servers. The `etcd` client keypairs are on the respective API servers, not on the `etcd` server. The only thing that gets shared around is the CA certificate.

**Comment by khaldoune** [comment]
@tokiwinter OK, so there is no need to specify this parameter right?

**Comment by tokiwinter** [comment]
@khaldoune - lets clarify - which parameters are you talking about - `--key-file` and `--peer-key-file`? You totally and definitely _do_ need those parameters for TLS to work for the `etcd` server (the former), and peer TLS between `etcd` members (the latter). If you, like I, have security concerns, you need to generate dedicated certificates/keys (I do this twice for _each_ `etcd` server, one "keypair" for the server, one for peering), the certs appropriately signed by the correct CA, and distribute those, and then generate client certs/keys, again with the right extensions, for use by your `kube-apiserver`'s via their `--etcd-<blah>` options.

All this is probably why it was omitted from the tutorial, as this isn't a PKI tutorial. I have my entire k8s cluster setup automated, and use `pyOpenSSL` to take the headache out of all this.

**Comment by khaldoune** [comment]
Ok Ok, further reading has clarified things for me, especially the example 3:
https://coreos.com/etcd/docs/latest/op-guide/security.html

So --key-file and --peer-key-file are both the SERVER keys used by clients when ETCD acts as server, they may be different if we have two different keypairs for peers and clients.

It's clear now, the client's private key remains private :) So everything is OK.

Thanks for your help.

**Comment by tokiwinter** [comment]
@khaldoune - cool, the confusing aspect in this tutorial is that the same cert/key is being used for both the server, peers, and the client, across the entire control plane, as well as for the API server's TLS iteself. Not ideal, but again, there is a big note in the README saying this isn't production-ready and is for learning purposes only. Don't check what the service account key is in this tutorial (hint: it's the CA private key 😱).

**Comment by khaldoune** [comment]
@tokiwinter Yes I've seen it lol 
But this tutorial is very good, I've learned several things. No I'm able to challenge what the installation tools (like kubespray and others) do.

**Comment by tokiwinter** [comment]
@khaldoune - agree 100% there - it is an amazing resource. It does exactly what it is supposed to do, and that is concentrate on showing how the various k8s components hang together. Dragging folks into production-grade PKI implementation would drive a lot of people away, and obscure the true purpose. I used it as the basis for my own python-based deployment tool, and extended it a lot to make it production ready. Big 👍 to @kelseyhightower for putting this together.

**Comment by khaldoune** [comment]
Yes big thanks to @kelseyhightower 
@tokiwinter Existing deployment tools dont have full coverage, especially when several cloud technologies are involved (Azure and OpenStack for me).
It's a great challenge...

**Comment by omkensey** [comment]
Of note, @bgeesaman is working on [hardening-kubernetes/from-scratch](https://github.com/hardening-kubernetes/from-scratch/) to give all the PKI and other security details you could ever want, following on from his work on improving the default security posture of Kubernetes cluster installers.

**Comment by tokiwinter** [comment]
@omkensey - watched and starred - nice!
