### ISSUE TITLE
Unable to register worker nodes

### ISSUE THREAD

**Issue by joshfischer1108** [kelseyhightower/kubernetes-the-hard-way#247]
I've followed through the walk through problem free until tonight. It seems I'm some how not getting the ip address of the api server to connect.  I was walking through the Readme(s) in order and thought I did everything I was supposed to.  Looking back, I think put the configuration files together in Readme05 correctly, but it seems I may have messed something up here?...  Any ideas of where I went wrong?  This is occurring on all worker nodes.

kubelet_node_status.go:107] Unable to register node "worker-0" with API server: Post https://:6443/api/v1/nodes: dial tcp :6443: getsockopt: connection refused

^^  if you look above you will see my missing IP address.  Thank you for your time.

**Comment by tokiwinter** [comment]
On one of your worker nodes, what is the output of the following command?
```
# grep server /var/lib/kubernetes/kubeconfig
```

**Comment by joshfischer1108** [comment]
Ahhh, it seems that the file `/var/lib/kubernetes/kubeconfig` does not exist on my workers.  I must have missed something while I was creating them.

**Comment by zatricky** [comment]
In 09, you probably missed this step:
```sudo mv ${HOSTNAME}.kubeconfig /var/lib/kubelet/kubeconfig```

**Comment by zatricky** [comment]
In 09 there's this line - but the path is slightly different:

```sudo mv ${HOSTNAME}.kubeconfig /var/lib/kubelet/kubeconfig```

**Comment by joshfischer1108** [comment]
Thank you for responding.  I will look at this later on!

**Comment by tokiwinter** [comment]
@joshfischer1108, @zatricky Ah yes, don't mind me, I provided the path to the file in my own environment.

My reasoning here is sound though, I suspect that `server:` is not properly formed in `/var/lib/kubelet/kubeconfig`, maybe as a result of `${KUBERNETES_PUBLIC_ADDRESS}` being undefined when you generated it.

**Comment by joshfischer1108** [comment]
That was it.  Thank you @tokiwinter and @zatricky for looking at this for me, definitely saved me some headaches!
