### ISSUE TITLE
Use the public key to the kube-apiserver in --service-account-key-file option

### ISSUE THREAD

**Issue by kalise** [kelseyhightower/kubernetes-the-hard-way#248]
It looks to me you should use the public key to the kube-apiserver in `--service-account-key-file` option according to https://kubernetes.io/docs/admin/service-accounts-admin/

> You must pass a service account private key file to the token controller in the controller-manager by using the --service-account-private-key-file option. The private key will be used to sign generated service account tokens. Similarly, you must pass the corresponding public key to the kube-apiserver using the --service-account-key-file option. The public key will be used to verify the tokens during authentication

In the apiserver you should use `--service-account-key-file=/var/lib/kubernetes/ca.pem` and in the controller-manager you should use `--service-account-private-key-file=/var/lib/kubernetes/ca-key.pem`

Please, advice in case I'm wrong.
Thanks

**Comment by tokiwinter** [comment]
`kube-apiserver --help` seems to indicate that both are acceptable:
```
      --service-account-key-file stringArray                    File containing PEM-encoded x509 RSA or ECDSA private or public keys, used to verify ServiceAccount tokens. If unspecified, --tls-private-key-file is used. The specified file can contain multiple keys, and the flag can be specified multiple times with different files.
```
I've just tested with both combinations and it works in both cases.

**Comment by kalise** [comment]
My experience is when using `ca-key.pem` in both API server and Controller Manager, as reported in the KHT tutorial, the service accounts are created but trying to `kubectl exec -it <pod> bash` you get deny with `Certificate signed by unknow authority`. If you have time. please test it and let me know about your results. Thanks.

**Comment by tokiwinter** [comment]
I was using a dedicated private key generated just for this purpose, no signing there as it's just a key. It worked fine. I have now moved to an actual cert signed by my cluster-wide CA. I don't use the CA key or cert for this, never have. In both cases, with the appropriate clusterrole and clusterrolebinding configured, `kubectl exec` has never been an issue - that said I also use dedicated kubelet client certs on my API servers. My PKI is very complex when compared with this tutorial so ymmv.

**Comment by lukesiler** [comment]
@tokiwinter - care to elaborate on your PKI setup?  Just getting acquainted with kubernetes and looking for pki best practices.

**Comment by tokiwinter** [comment]
@lukesiler - for sure. I use dedicated certs/keys wherever possible. I create dedicated `kubeconfig`s with embedded dedicated certs for `kube-scheduler` and `kube-controller-manager`. `ca.key` _is_ needed on my masters, but for `kube-controller-manager` as I use TLS bootstrapping for the `kubelet`s and need the cluster signing cert/key set up. I also have dedicated apiserver->kubelet certs/keys, my etcd nodes have their own cert/keys for both serving and peering, I have a dedicated keypair for each of my masters (as etcd clients) and so on. I also have another CA with an appropriate keypair API aggregation.

I'd suggest looking at the following for more info on this:

https://nixaid.com/kubernetes-from-scratch/
https://github.com/kubernetes/kubeadm/blob/master/docs/design/design_v1.8.md

I'd also recommend spinning up a cluster via `kubeadm` and dissecting that, as well as browsing the `kubeadm` source.

It's all beyond the scope of this tutorial, but does things in a production-grade manner.

HTH

**Comment by tokiwinter** [comment]
Oh, you'll learn plenty about RBAC by doing this stuff too :)

**Comment by tokiwinter** [comment]
@kalise - with that, I find it's usually because you need to set up `--kubelet-client-certificate` and `--kubelet-client-key` but _not_ `--kubelet-certificate-authority` options to `kube-apiserver`. That said, it's variable depending on your exact PKI setup.

**Comment by kalise** [comment]
@tokiwinter, yes you're right. Just realized that by reverse engineering of a kubeadm setup. For PKI infrastructure, k8s documentation needs to be improved, imo. Issue can be closed, but i would keep it open for further discussion. Thanks

**Comment by tokiwinter** [comment]
@kalise - regarding documentation, watch this space. I'm starting work with the community on improving the documentation around setting up Kubernetes clusters from scratch, and PKI will be a major area of focus.

**Comment by kalise** [comment]
@tokiwinter thanks the wiki  you mentioned above is very good and clarifies most of my dubts. However still struggling to understand the meaning of --kubelet-certificate-authority parameter and how/when to be used or not used. Please, advise. Thanks

**Comment by tokiwinter** [comment]
@kalise - if you're using a real live CA to sign your stuff, then you can use this flag, and specify the path to a root certificate bundle. With self-signed stuff, I don't believe it works.

**Comment by kalise** [comment]
@tokiwinter Thanks, makes sense. Just realized that most of the confusion in my mind with k8s PKI is related to the fact that all the examples and tutorial assume to have a single CA for all the cluster. Starting to think in terms of separate CAs for each function, it seems to me more clear.

Here few examples, please have a look and correct me if wrong

### kubectl -> apiserver interaction
*e.g. kubectl get pods*

In this case, we have a Client CA signing certificates for the human users and a Server CA signing the API server certificate.
 
```

          +------------+                           +------------+
          | Server CA  |                           | Client CA  |
          +-+----------+                           +-+----------+
            ^                                        ^
            |                                        |
            | Can I trust server.pem?                | Can I trust client-cert.pem?
            |                                        |
            |                        tcp port :6443  |
        +---+-----------+   client.pem           +---+-----------+
        |               | +--------------------> |               |
        |    kubectl    |                        |   API Server  |
        |               | <--------------------+ |               |
        +---------------+      server-cert.pem   +---------------+

kubeconfig                                      kube-apiserver
 certificate-authority: ca.pem                   --client-ca-file=client-ca.pem
 client-certificate: client.pem                  --tls-cert-file=server.pem
 client-key: client-key.pem                      --tls-private-key-file=server-key.pem
                                                 --tls-ca-file= #NOT USED
                                                 --kubelet-certificate-authority= #NOT USED
                                                 --kubelet-client-certificate= #NOT USED
                                                 --kubelet-client-key= #NOT USED

					        kube-controller-manager
                                                 --root-ca-file=ca.pem
                                                 --cluster-signing-cert-file= #NOT USED
                                                 --cluster-signing-key-file=  #NOT USED	
openssl x509 -in server.pem -noout -issuer -subject
issuer= /C=IT/ST=Italy/L=Milan/CN=Server CA
subject= /CN=apiserver

openssl x509 -in client.pem -noout -issuer -subject
issuer= /CN=Client CA
subject= /O=system:masters/CN=admin
```

### kubelet -> apiserver interaction (no TLS bootstraapping)
*e.g. worker node registration* 
In this case, in addition to the CAs above, we create another CA signing certificates for the worker nodes. Since we have now two CAs on the API server, we bundle them in a single file `cat client-ca.pem > bundle-ca.pem && and cat worker-ca.pem >> bundle-ca.pem` and set `--client-ca-file=bundle-ca.pem` on the API server

```
          +------------+                           +------------+
          | Server CA  |                           | Worker CA  |
          +-+----------+                           +-+----------+
            ^                                        ^
            |                                        |
            | Can I trust server.pem?                | Can I trust kubelet.pem?
            |                                        |
            |                         tcp port :6443 |
        +---+-----------+   kubelet.pem          +---+-----------+
        |               | +--------------------> |               |
        |    kubelet    |                        |   API Server  |
        |               | <--------------------+ |               |
        +---------------+      server.pem        +---------------+

kubelet
 --kubeconfig=/var/lib/kubelet/kubeconfig
 
kubeconfig                                      kube-apiserver
 certificate-authority: ca.pem                   --client-ca-file=bundle-ca.pem #bundle-ca.pem contains both client-ca.pem and worker-ca.pem
 client-certificate: kubelet.pem                 --tls-cert-file=server.pem
 client-key: kubelet-key.pem                     --tls-private-key-file=server-key.pem
                                                 --tls-ca-file= #NOT USED
                                                 --kubelet-certificate-authority= #NOT USED
                                                 --kubelet-client-certificate= #NOT USED
                                                 --kubelet-client-key= #NOT USED

					        kube-controller-manager
                                                 --root-ca-file=ca.pem
                                                 --cluster-signing-cert-file= #NOT USED
                                                 --cluster-signing-key-file=  #NOT USED	

openssl x509 -in server.pem -noout -issuer -subject
issuer= /C=IT/ST=Italy/L=Milan/CN=Server CA
subject= /CN=apiserver

openssl x509 -in kubelet.pem -noout -issuer -subject
issuer= /CN=Worker CA
subject= /O=system:nodes/CN=system:kubelet
```

### apiserver -> kubelet interaction
*e.g. kubectl exec -it <pod> /bin/bash*

In this case, we still use the Server CA to sign certificates in requests from the API server to the kubelet HTTPS services on TCP port 10255, eg. when users issue `kubectl exec -it <pod> /bin/bash` commands. My question here: is still this interaction a two-way TLS authentication handshake? i.e. the kubelet and the API server authenticate each other? Or only the API (server) client certificate `kubelet-client.pem` is authenticated by the kubelet server?

```
          +------------+                             +------------+
          | Server CA  |                             | Worker CA  |
          +-+----------+                             +-+----------+
            ^                                          ^
            |                                          |
            | Can I trust kubelet-client.pem           | Can I trust kubelet.pem?
            |                                          |
            |         tcp port:10255                   |
        +---+-----------+       kubelet-client.pem +---+-----------+
        |               | <----------------------+ |               |
        |    kubelet    |                          |   API Server  |
        |               | +----------------------> |               |
        +---------------+  kubelet.pem             +---------------+
                           ^
                           | IS IT USED IN THIS CONTEXT?
                           | i.e. is still a two-way authentication?

kubelet
 --kubeconfig=/var/lib/kubelet/kubeconfig
 --anonymous-auth=false
 --client-ca-file=ca.pem
 
kubeconfig                                      kube-apiserver
 certificate-authority: ca.pem                   --client-ca-file=bundle-ca.pem # bundle-ca.pem contains both the client-ca.pem and the worker-ca.pem
 client-certificate: kubelet.pem                 --tls-cert-file=server.pem
 client-key: kubelet-key.pem                     --tls-private-key-file=server-key.pem
                                                 --tls-ca-file= #NOT USED
                                                 --kubelet-certificate-authority= #NOT USED
                                                 --kubelet-client-certificate=kubelet-client.pem
                                                 --kubelet-client-key=kubelet-client-key.pem

					        kube-controller-manager
                                                 --root-ca-file=ca.pem
                                                 --cluster-signing-cert-file= #NOT USED
                                                 --cluster-signing-key-file=  #NOT USED	

openssl x509 -in kubelet-client.pem -noout -issuer -subject
issuer= /C=IT/ST=Italy/L=Milan/CN=Server CA
subject= /O=system:masters/CN=kubelet-client

openssl x509 -in kubelet.pem -noout -issuer -subject
issuer= /CN=Worker CA
subject= /O=system:nodes/CN=system:kubelet

```

Please, note in all the examples above I **never** set the `--kubelet-certificate-authority` and `--tls-ca-file`, so still unsure when these options have to be used.
Thanks
