### ISSUE TITLE
typo in lab 8

### ISSUE THREAD

**Issue by stubblyhead** [kelseyhightower/kubernetes-the-hard-way#249]
In the **Kubernetes Frontend Load Balancer** section you use the following to get the public kubernetes address:
```
KUBERNETES_PUBLIC_ADDRESS=$(gcloud compute addresses describe kubernetes-the-hard-way \
  --region $(gcloud config get-value compute/region) \
  --format 'value(name)')
```

The format parameter at the end should be `'value(address)'`, not `'value(name)'`.

**Comment by aditya-konarde** [comment]
Tried both ways. Works with 'value(name)' as well. Looks like --address can resolve by name.

**Comment by kelseyhightower** [comment]
It works as is. I'm going to leave this as is unless it breaks someone.
