### ISSUE TITLE
Translating POD_CIDR for non-GCP environments?

### ISSUE THREAD

**Issue by andyshinn** [kelseyhightower/kubernetes-the-hard-way#251]
#217 asked a valid question about `POD_CIDR` but it didn't seem to get answered in the larger issue scope. I'm translating the tutorial steps to a local bare-metal cluster and not quite sure what `POD_CIDR` is. Is it a smaller subnet inside to Cluster CIDR? Or something made up that just needs to be unique per node (such as `172.16.11.0/24`, `172.16.12.0/24`, etc)?

**Comment by zatricky** [comment]
As you imagined, yes: It is "a smaller subnet inside [the] Cluster CIDR".

These subnets are node-specific inside the cluster network. The kubelet service issues IP addresses to pods from the --pod-cidr parameter. This is defined in the kubelet.service systemd definition in kthw-09:
`  --pod-cidr=\${POD_CIDR}`

If you use the described /16 main CIDR and /24 subnets, you are limited to ~253 nodes and ~253 pods per node. For a test/learning cluster, this is more than enough. For production, this is probably* more than enough. As you scale up, this limit would need to be evaluated of course.

*As the project is aimed mostly as teaching/learning and is technically not suitable for production. ;)

**Comment by andyshinn** [comment]
Thanks! This is helpful.
