### ISSUE TITLE
DNS lookup fails

### ISSUE THREAD

**Issue by awardsolutionsuser** [kelseyhightower/kubernetes-the-hard-way#254]
i can see DNS pods.  not sure why they are restarting.  nslookup doesn't work from inside busybox.

vagrant@vagrant:~/Downloads$ **kubectl get pods**
NAME                       READY     STATUS    RESTARTS   AGE
busybox-56db8bd9d7-4cmnf   1/1       Running   0          11m

vagrant@vagrant:~/Downloads$ **kubectl get pods -l k8s-app=kube-dns -n kube-system**
NAME                        READY     STATUS    RESTARTS   AGE
kube-dns-7797cb8758-q5nh2   2/3       Running   3          2m
kube-dns-7797cb8758-tzfmw   2/3       Running   3          2m

POD_NAME=$(kubectl get pods -l run=busybox -o jsonpath="{.items[0].metadata.name}")
vagrant@vagrant:~/Downloads$ **kubectl exec -ti $POD_NAME -- nslookup kubernetes**
Server:    10.32.0.10
                     Address 1: 10.32.0.10

                                          **nslookup: can't resolve 'kubernetes'**
                                                                              command terminated with exit code 1
vagrant@vagrant:~/Downloads$ kubectl exec -ti $POD_NAME -- nslookup kubernetes
Server:    10.32.0.10
                     Address 1: 10.32.0.10

                                          nslookup: can't resolve 'kubernetes'
                                                                              command terminated with exit code 1

**Comment by tokiwinter** [comment]
One of the containers in the kube-dns pods isn't coming up. What do the logs say? I suspect a networking issue within your cluster is to blame here.

**Comment by cfchou** [comment]
Hi I have the same problem here.

I firstly checked that all pods are running fine:
```
kube-shell> kubectl get service --all-namespaces
NAMESPACE     NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
default       kubernetes   ClusterIP   10.32.0.1    <none>        443/TCP         1h
kube-system   kube-dns     ClusterIP   10.32.0.10   <none>        53/UDP,53/TCP   3m
kube-shell> kubectl get pod --all-namespaces
NAMESPACE     NAME                       READY     STATUS    RESTARTS   AGE
default       busybox-56db8bd9d7-xq8sn   1/1       Running   0          15m
kube-system   kube-dns-6c5f4f95b-dpkc9   3/3       Running   0          16m
kube-system   kube-dns-6c5f4f95b-vkk7h   3/3       Running   0          16m
```

```
kube-shell>  kubectl describe pod -n kube-system kube-dns-6c5f4f95b-dpkc9                                                                                             [82/4947]
Name:           kube-dns-6c5f4f95b-dpkc9
Namespace:      kube-system
Node:           worker-0/10.240.0.20
Start Time:     Wed, 08 Nov 2017 06:33:31 +0000
Labels:         k8s-app=kube-dns
                pod-template-hash=271909516
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kube-dns-6c5f4f95b","uid":"bd382b6d-c44e-11e7-8d11-42010af00...
                scheduler.alpha.kubernetes.io/critical-pod=
Status:         Running
IP:             10.200.0.3
Created By:     ReplicaSet/kube-dns-6c5f4f95b
Controlled By:  ReplicaSet/kube-dns-6c5f4f95b
Containers:
  kubedns:
    Container ID:  containerd://63f308aa1fdf60f8125ae28b0aaec8b434a8941ba21fa58f1f2f52753aaaf095
    Image:         gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.4
    Image ID:      gcr.io/google_containers/k8s-dns-kube-dns-amd64@sha256:40790881bbe9ef4ae4ff7fe8b892498eecb7fe6dcc22661402f271e03f7de344
    Ports:         10053/UDP, 10053/TCP, 10055/TCP
    Args:
      --domain=cluster.local.
      --dns-port=10053
      --config-dir=/kube-dns-config
      --v=4
    State:          Running
      Started:      Wed, 08 Nov 2017 06:33:51 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:      100m
      memory:   70Mi
    Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PROMETHEUS_PORT:  10055
    Mounts:
      /kube-dns-config from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-gtl6g (ro)
  dnsmasq:
    Container ID:  containerd://e737c81d1a3cdfb8023de12f58fac8d6f0832bf4036d06d1ec1248fab8c264de
    Image:         gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.4                                                                                                      [39/4947]
    Image ID:      gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64@sha256:aeeb994acbc505eabc7415187cd9edb38cbb5364dc1c2fc748154576464b3dc2
    Ports:         53/UDP, 53/TCP
    Args:
      -v=2
      -logtostderr
      -configDir=/etc/k8s/dns/dnsmasq-nanny
      -restartDnsmasq=true
      --
      -k
      --cache-size=1000
      --log-facility=-
      --server=/cluster.local/127.0.0.1#10053
      --server=/in-addr.arpa/127.0.0.1#10053
      --server=/ip6.arpa/127.0.0.1#10053
    State:          Running
      Started:      Wed, 08 Nov 2017 06:33:51 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        150m
      memory:     20Mi
    Liveness:     http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/k8s/dns/dnsmasq-nanny from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-gtl6g (ro)
  sidecar:
    Container ID:  containerd://6e3e062b281d756da98d197efb60d05ecc0ec661370360b94d93d65a86ce0317
    Image:         gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.4
    Image ID:      gcr.io/google_containers/k8s-dns-sidecar-amd64@sha256:97074c951046e37d3cbb98b82ae85ed15704a290cce66a8314e7f846404edde9
    Port:          10054/TCP
    Args:
      --v=2
      --logtostderr
      --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,A
      --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,A
    State:          Running
      Started:      Wed, 08 Nov 2017 06:33:51 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        10m
      memory:     20Mi
    Liveness:     http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-gtl6g (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  kube-dns-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-dns
    Optional:  true
  kube-dns-token-gtl6g:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-dns-token-gtl6g
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               47m   default-scheduler  Successfully assigned kube-dns-6c5f4f95b-dpkc9 to worker-0
  Normal   SuccessfulMountVolume   47m   kubelet, worker-0  MountVolume.SetUp succeeded for volume "kube-dns-config"
  Normal   SuccessfulMountVolume   47m   kubelet, worker-0  MountVolume.SetUp succeeded for volume "kube-dns-token-gtl6g"
  Warning  FailedCreatePodSandBox  47m   kubelet, worker-0  Failed create pod sandbox.
  Warning  FailedSync              47m   kubelet, worker-0  Error syncing pod
  Normal   Pulled                  47m   kubelet, worker-0  Container image "gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.4" already present on machine
  Normal   Started                 47m   kubelet, worker-0  Started container
  Normal   Created                 47m   kubelet, worker-0  Created container
  Normal   Pulled                  47m   kubelet, worker-0  Container image "gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.4" already present on machine
  Normal   Created                 47m   kubelet, worker-0  Created container
  Normal   Started                 47m   kubelet, worker-0  Started container
  Normal   Pulled                  47m   kubelet, worker-0  Container image "gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.4" already present on machine
  Normal   Created                 47m   kubelet, worker-0  Created container
  Normal   Started                 47m   kubelet, worker-0  Started container
```

In busybox pod, it failed to resolve external domain and cluster.local:
```
kube-shell> kubectl exec busybox-56db8bd9d7-xq8sn -- nslookup github.com
Server:    10.32.0.10
Address 1: 10.32.0.10

nslookup: can't resolve 'github.com'
command terminated with exit code 1
kube-shell> kubectl exec busybox-56db8bd9d7-xq8sn -- nslookup kubernetes
Server:    10.32.0.10
Address 1: 10.32.0.10

nslookup: can't resolve 'kubernetes'
command terminated with exit code 1
```

However, on a worker things are a bit different as it resolves correctly resolve external domain:
```
cfchou@worker-0:~$ nslookup www.github.com 10.32.0.10
Server:         10.32.0.10
Address:        10.32.0.10#53

Non-authoritative answer:
www.github.com  canonical name = github.com.
Name:   github.com
Address: 192.30.253.113
Name:   github.com
Address: 192.30.253.112

cfchou@worker-0:~$ nslookup kubernetes 10.32.0.10
Server:         10.32.0.10
Address:        10.32.0.10#53

** server can't find kubernetes: NXDOMAIN

```

It looks like a problem with the dns setup but I'm not sure where to look at.

**Comment by tokiwinter** [comment]
@cfchou can you ping between pods across different worker nodes? If not there is a fundamental connectivity issue.

**Comment by osoriano** [comment]
I had the same issue @awardsolutionsuser (Also experiencing the weird terminal output you're seeing).

The pod isn't able to connect to the DNS service IP. Seems related to https://github.com/kubernetes/kubernetes/issues/40761.

I was able to get around it by adding `--masquerade-all=true` to the kube-proxy service. I'm not sure why pod to service IP traffic isn't being masqueraded properly. I see that `"ipMasq": true,` is already set in `/etc/cni/net.d/10-bridge.conf`

**Comment by tokiwinter** [comment]
@osoriano - that is where I was heading. The broken container in the DNS pod is probably trying to connect to the kubernetes API svc IP, fixed with the same option to `kube-proxy`, which is why only 2/3 of the DNS pods are running.

**Comment by vladislavPV** [comment]
just add modprobe br_netfilter
this should help

**Comment by awardsolutionsuser** [comment]
i finally tore everything down and restarted from scratch and the DNS stuff works now.
vagrant@vagrant:~/Downloads/khw$ kubectl get pods -l k8s-app=kube-dns -n kube-system
NAME                        READY     STATUS    RESTARTS   AGE
kube-dns-7797cb8758-579r2   3/3       Running   0          28s
kube-dns-7797cb8758-nl7jz   3/3       Running   0          28s


 kubectl exec -ti $POD_NAME -- nslookup kubernetes
Server:    10.32.0.10
                     Address 1: 10.32.0.10 kube-dns.kube-system.svc.cluster.local

                                                                                 Name:      kubernetes
                                                                                                      Address 1: 10.32.0.1 kubernetes.default.svc.cluster.local

not sure what makes the nslookup output look so wierd.

**Comment by awardsolutionsuser** [comment]
tore everthing down and rebuilt and DNS is OK

**Comment by zatricky** [comment]
In case it helps anyone else, I was having this exact issue with the same symptoms on a new non-cloud (self-hosted VMs) staging cluster. The scripts I used to build the cluster were only slightly updated from scripts (based on kthw) I'd used on a previous test cluster I had built 30 days prior that was still fully operational - so it gave me an opportunity to compare.

Tearing it down and starting over also proved that the problem was reproducible.

The cause was a config in docker, which deviates from Kelsey's guide as he uses CRI-O. Docker's default configuration adds some iptables rules that blocks inter-pod communication. In my case, nodes could ping all other nodes and their own pods. Pods could only ping their own node but no other pods.

The fix on the new cluster was to add the `"iptables":false` option to `/etc/docker/daemon.json`. This option can be plugged in elsewhere - for example in the systemd service unit - but I was already making use of a daemon.json anyway.

I was reproducibly able to block or unblock communication on the new cluster with that config - but cannot reproduce the issue on the older cluster. I'm not sure exactly what version the behaviour changed in - but likely in a recent version of docker due to the timing.

**Comment by jicowan** [comment]
@tokiwinter I am having the issue that @cfchou described.  All the kube-dns pods are running, but I can't ping across pods.  I built my cluster in AWS which may account for the issues I'm having.  The instances are deployed in a VPC with a CIDR of 10.240.0.0/24 with 1 subnet.  I created additional routes in the default VPC route table for the 10.200.0.0/16 network so that traffic for 10.200.0.0/24, 10.200.1.0/24 and 10.200.2.0/24 are routed to the appropriate nodes.  This is what I see when I look at the route on the busybox pod:
```bash
default via 10.200.2.1 dev eth0
```
and this is the route on the worker node that the pod is running on: 
```bash
default via 10.240.0.1 dev eth0
10.200.2.0/24 dev cnio0  proto kernel  scope link  src 10.200.2.1
10.240.0.0/24 dev eth0  proto kernel  scope link  src 10.240.0.158
```
I sense there's a routing issue, but I'm not sure how to fix it.

**Comment by tokiwinter** [comment]
@jicowan - are you using `--masquerade-all` as a `kube-proxy` option? If not, give that a try. It fixes a number of strange issues in my environment at least.

**Comment by jicowan** [comment]
@tokiwinter You mean update the kube-proxy.service systemd startup options?  Like this?
```
[Unit]
Description=Kubernetes Kube Proxy
Documentation=https://github.com/kubernetes/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-proxy \\
  --cluster-cidr=10.200.0.0/16 \\
  --kubeconfig=/var/lib/kube-proxy/kubeconfig \\
  --proxy-mode=iptables \\
  --masquerade-all \\
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by tokiwinter** [comment]
@jicowan - yes

**Comment by jicowan** [comment]
@tokiwinter A couple errors appeared in the logs for kube-proxy when I restarted it.  I see similar entries in the logs before I restarted the service.  

```
Jan 26 18:10:42 [hostname] kube-proxy[5265]: E0126 18:10:42.394760    5265 proxier.go:792] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed
```

```
Failed to delete stale service IP [internal-ip] connections, error: error deleting connection tracking state for UDP service IP: [internal-ip], error: error looking for path of conntrack: exec: "conntrack": executable file not found in $PATH
```

**Comment by teodororicciardello** [comment]
I had the same problem as @jicowan, I'm also running kthw in AWS. 
In my case I've found there was no connectivity between the worker nodes because I didn't implement for AWS the flag `--can-ip-forward` of the tutorial. 

In AWS this is done by setting the flag `source-dest-check=false` for each VM after the creation. 
Once set this flag for all workers the DNS deployment worked as expected. 
Perhaps this can help someone.

**Comment by aleksystasiak** [comment]
I have exact same problem.
None of solutions proposed above helps.
(bare metal - ubuntu 16.04 - k8s 1.9.0 with weave)
