### ISSUE TITLE
etcdctl tls error

### ISSUE THREAD

**Issue by onesolpark** [kelseyhightower/kubernetes-the-hard-way#255]
Docs 07-bootstrapping-etcd.md  - Verification
~~~
ETCDCTL_API=3 etcdctl member list
~~~
command is used to verify whether etcd is up and running.

Since tls is set in the etcd configuration file, the following error occurs.

~~~
client: etcd cluster is unavailable or misconfigured
~~~

Put in the debug option to see in detail the errors.

~~~
start to sync cluster using endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379)
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
got endpoints(https://172.17.8.101:2379,https://172.17.8.102:2379,https://172.17.8.103:2379) after sync
Cluster-Endpoints: https://172.17.8.101:2379, https://172.17.8.102:2379, https://172.17.8.103:2379
cURL Command: curl -X GET https://172.17.8.101:2379/v2/members
cURL Command: curl -X GET https://172.17.8.102:2379/v2/members
cURL Command: curl -X GET https://172.17.8.103:2379/v2/members
client: etcd cluster is unavailable or misconfigured
~~~

As the endpoints are all https I think you have to add the additional flags to make this command work

~~~
ETCDCTL_API=3 etcdctl --ca-file=/etc/etcd/ca.pem --cert-file=/etc/etcd/kubernetes.pem --key-file=/etc/etcd/kubernetes-key.pem member list
~~~

Assuming that you have placed the tls files in the following directory.
The command above should work fine.

I don't know if there is a way to set the config in etcdctl, so that you don't have to put the global options every time you use the command.

**Comment by tokiwinter** [comment]
> I don't know if there is a way to set the config in etcdctl, so that you don't have to put the global options every time you use the command.

See my comment on #220

**Comment by kelseyhightower** [comment]
I'm going to consider updating the guide during the security update to ease the use of etcd beyond the bootstrapping phase.

**Comment by karthikvt26** [comment]
Hi, I am also facing the above issue if I am invoking 

```ETCDCTL_API=3 etcdctl member list```

> client: etcd cluster is unavailable or misconfigured; error #0: x509: certificate signed by unknown authority
; error #1: x509: certificate signed by unknown authority

as a normal user and if I do the following

```ETCDCTL_API=3 etcdctl --ca-file=/etc/etcd/ca.pem --cert-file=/etc/etcd/kubernetes.pem --key-file=/etc/etcd/kubernetes-key.pem member list```

> 3a57933972cb5131: name=controller-2 peerURLs=https://10.240.0.12:2380 clientURLs= isLeader=false
f98dc20bce6225a0: name=controller-0 peerURLs=https://10.240.0.10:2380 clientURLs=https://10.240.0.10:2379 isLeader=true
ffed16798470cab5: name=controller-1 peerURLs=https://10.240.0.11:2380 clientURLs=https://10.240.0.11:2379 isLeader=false

It lists the members correctly. Am I doing anything wrong?

**Comment by indrayam** [comment]
@karthikvt26 I faced the same issue while running the `etcdctl` command. I have documented the things I had to do to make things work in my own fork of the document:

https://github.com/indrayam/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md#verification

Plan on opening upstream PR for @kelseyhightower to review once I am done going through all 14 docs. 

HTH
