### ISSUE TITLE
Unable to connect using public IP address

### ISSUE THREAD

**Issue by ananthNeudesic** [kelseyhightower/kubernetes-the-hard-way#262]
Trying to connect to run command : 
`curl --cacert ca.pem https://${KUBERNETES_PUBLIC_ADDRESS}:6443/version`
Results in an error :
**curl: (7) Failed to connect to 35.203.183.142 port 6443: Connection timed out**

My control plane is working correctly. When I run on any controller :
`kubectl get componentstatuses`
Result :
_NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   
scheduler            Healthy   ok                   
etcd-2               Healthy   {"health": "true"}   
etcd-1               Healthy   {"health": "true"}_ 

Running this command on any controller :
`curl --cacert ca.pem https://127.0.0.1:6443/version`
Result :
_{
  "major": "1",
  "minor": "8",
  "gitVersion": "v1.8.0",
  "gitCommit": "6e937839ac04a38cac63e6a7a306c5d035fe7b0a",
  "gitTreeState": "clean",
  "buildDate": "2017-09-28T22:46:41Z",
  "goVersion": "go1.8.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}_

**Comment by kelseyhightower** [comment]
Please ensure you have create the firewall rule based on the guide and ensure 6443 is not blocked on your end. I just tested the guide and it's working for me.

**Comment by youyongsong** [comment]
@ananthNeudesic hi, I suffered this problem too. This problem only appears when using google cloud shell, you should copy your ca.pem to your computer then try it again.

**Comment by ashleyconnor** [comment]
I'm running into this:

```
➜  gcloud compute firewall-rules list --filter="network:kubernetes-the-hard-way"
NAME                                             NETWORK                  DIRECTION  PRIORITY  ALLOW                 DENY  DISABLED
kubernetes-the-hard-way-allow-external           kubernetes-the-hard-way  INGRESS    1000      tcp:22,tcp:6443,icmp        False
kubernetes-the-hard-way-allow-health-check       kubernetes-the-hard-way  INGRESS    1000      tcp                         False
kubernetes-the-hard-way-firewall-allow-internal  kubernetes-the-hard-way  INGRESS    1000      icmp,udp,tcp                False
```

Running `netstat` on the controllers shows them listening on `6443`:

```
ashleyconnor@controller-2:~$ sudo netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      13919/etcd
tcp        0      0 10.240.0.12:2379        0.0.0.0:*               LISTEN      13919/etcd
tcp        0      0 10.240.0.12:2380        0.0.0.0:*               LISTEN      13919/etcd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      26382/nginx: master
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      14356/kube-apiserve
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1256/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1159/sshd
tcp6       0      0 :::10251                :::*                    LISTEN      14360/kube-schedule
tcp6       0      0 :::6443                 :::*                    LISTEN      14356/kube-apiserve
tcp6       0      0 :::10252                :::*                    LISTEN      14359/kube-controll
tcp6       0      0 :::80                   :::*                    LISTEN      26382/nginx: master
tcp6       0      0 :::10257                :::*                    LISTEN      14359/kube-controll
tcp6       0      0 :::10259                :::*                    LISTEN      14360/kube-schedule
tcp6       0      0 :::22                   :::*                    LISTEN      1159/sshd
```

**Comment by elnemesisdivina** [comment]
I also run same checks on firewalls and routes and I have the same exact problem, any clue on this?

**Comment by elnemesisdivina** [comment]
> I'm running into this:
> 
> ```
> ➜  gcloud compute firewall-rules list --filter="network:kubernetes-the-hard-way"
> NAME                                             NETWORK                  DIRECTION  PRIORITY  ALLOW                 DENY  DISABLED
> kubernetes-the-hard-way-allow-external           kubernetes-the-hard-way  INGRESS    1000      tcp:22,tcp:6443,icmp        False
> kubernetes-the-hard-way-allow-health-check       kubernetes-the-hard-way  INGRESS    1000      tcp                         False
> kubernetes-the-hard-way-firewall-allow-internal  kubernetes-the-hard-way  INGRESS    1000      icmp,udp,tcp                False
> ```
> 
> Running `netstat` on the controllers shows them listening on `6443`:
> 
> ```
> ashleyconnor@controller-2:~$ sudo netstat -plnt
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      13919/etcd
> tcp        0      0 10.240.0.12:2379        0.0.0.0:*               LISTEN      13919/etcd
> tcp        0      0 10.240.0.12:2380        0.0.0.0:*               LISTEN      13919/etcd
> tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      26382/nginx: master
> tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      14356/kube-apiserve
> tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1256/systemd-resolv
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1159/sshd
> tcp6       0      0 :::10251                :::*                    LISTEN      14360/kube-schedule
> tcp6       0      0 :::6443                 :::*                    LISTEN      14356/kube-apiserve
> tcp6       0      0 :::10252                :::*                    LISTEN      14359/kube-controll
> tcp6       0      0 :::80                   :::*                    LISTEN      26382/nginx: master
> tcp6       0      0 :::10257                :::*                    LISTEN      14359/kube-controll
> tcp6       0      0 :::10259                :::*                    LISTEN      14360/kube-schedule
> tcp6       0      0 :::22                   :::*                    LISTEN      1159/sshd
> ```

@ashleyconnor  did you make it work? I also run same tests and seems like the firewall is ok as well on mine so  I have exact same problem.

**Comment by tejaskargutkar** [comment]
I believe the command needs to be run from the "controller" nodes and not the physical machine. Running it from the controller nodes gives me the right output and it times out with the exception you shared when run from the physical machine.
