### ISSUE TITLE
Unable to access nginx service from external [http://${EXTERNAL_IP}:${NODE_PORT}}]

### ISSUE THREAD

**Issue by jetune** [kelseyhightower/kubernetes-the-hard-way#264]
Hi everybody,
my english iss very poor so, don't worry about mistakes...

I have followed all steps to build K8S cluster but the "Services Exposition Test" in 13-smoke-test don't work as expected, and I cannot reach my NGINX service from external.

In the chapter 13-smoke-test, all test works well except the test on [Services](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/13-smoke-test.md#services).

the steps I followed are that :

1. Deploy nginx : `kubectl run nginx --image=nginx`

2. Listing the pods result : `nginx-7c87f569d-qcc2v   1/1       Running   0          11m`

3. Exposed nginx service : `kubectl expose deployment nginx --port 80 --type NodePort`

4. Listing services : 
`NAME    TYPE          CLUSTER-IP    EXTERNAL-IP    PORT(S)             AGE` 
`nginx     NodePort   10.32.0.115      <none>               80:31193/TCP   12m`

5. Get NodePort and Authorized it on Google VPC
`NODE_PORT=$(kubectl get svc nginx --output=jsonpath='{range .spec.ports[0]}{.nodePort}')`
`gcloud compute firewall-rules create kubernetes-the-hard-way-allow-nginx-service --allow=tcp:${NODE_PORT} --network kubernetes-the-hard-way`

6. Rule Created on Google VPC
`kubernetes-the-hard-way-allow-nginx-service  kubernetes-the-hard-way  INGRESS    1000      tcp:31193`

7. Get the Node external IP
`EXTERNAL_IP=$(gcloud compute instances describe worker-0 --format 'value(networkInterfaces[0].accessConfigs[0].natIP)')`

**8. Try to reach nginx from external**
**`curl -I http://${EXTERNAL_IP}:${NODE_PORT}`**

**CURL command result on error :** 
**`curl: (7) Failed to connect to 35.197.74.10 port 31193: Connection refused`**

**NB : I've tried with worker-1 and worker-2 external IP but have the same result.**

**I don't know what happend, but i think kube-proxy can be the source, because I don't see any SERVICE Related rule in iptables**

**I execute command : `sudo iptables -t nat -nvL`**

Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 75 packets, 4500 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 63 packets, 3780 bytes)
 pkts bytes target     prot opt in     out     source               destination         
14662  881K KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */
 2342  141K CNI-01a2aee4e89a77122fb993ef  all  --  *      *       10.200.0.0/24        0.0.0.0/0            /* name: "bridge" id: "a899be0bb9dd387b2614eb255483c69134d98b91c9453abeba228aa259bcc610" */

Chain CNI-01a2aee4e89a77122fb993ef (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 2340  140K ACCEPT     all  --  *      *       0.0.0.0/0            10.200.0.0/24        /* name: "bridge" id: "a899be0bb9dd387b2614eb255483c69134d98b91c9453abeba228aa259bcc610" */
    2   120 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "bridge" id: "a899be0bb9dd387b2614eb255483c69134d98b91c9453abeba228aa259bcc610" */

Chain KUBE-MARK-DROP (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x8000

Chain KUBE-MARK-MASQ (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x4000

Chain KUBE-POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000

**NB : This is my worker-0 configuration, worker-1 and worker-2 are similar**

**kube-proxy.service [worker-0]**
Description=Kubernetes Kube Proxy
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-proxy \
  --master=https://35.197.87.166:6443
  --cluster-cidr=10.200.0.0/16 \
  --kubeconfig=/var/lib/kube-proxy/kubeconfig \
  --proxy-mode=iptables \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

**kubelet.service [worker-0]**

[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=cri-containerd.service
Requires=cri-containerd.service

[Service]
ExecStart=/usr/local/bin/kubelet \
  --allow-privileged=true \
  --anonymous-auth=false \
  --authorization-mode=Webhook \
  --client-ca-file=/var/lib/kubernetes/ca.pem \
  --cluster-dns=10.32.0.10 \
  --cluster-domain=cluster.local \
  --container-runtime=remote \
  --container-runtime-endpoint=unix:///var/run/cri-containerd.sock \
  --image-pull-progress-deadline=2m \
  --kubeconfig=/var/lib/kubelet/kubeconfig \
  --network-plugin=cni \
  --pod-cidr=10.200.0.0/24 \
  --register-node=true \
  --require-kubeconfig \
  --runtime-request-timeout=15m \
  --tls-cert-file=/var/lib/kubelet/worker-0.pem \
  --tls-private-key-file=/var/lib/kubelet/worker-0-key.pem \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by kelseyhightower** [comment]
I've just run through this guide end to end. Be sure to open the firewall as required by the guide.

**Comment by elnemesisdivina** [comment]
> Hi everybody,
> my english iss very poor so, don't worry about mistakes...
> 
> I have followed all steps to build K8S cluster but the "Services Exposition Test" in 13-smoke-test don't work as expected, and I cannot reach my NGINX service from external.
> 
> In the chapter 13-smoke-test, all test works well except the test on [Services](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/13-smoke-test.md#services).
> 
> the steps I followed are that :
> 
> 1. Deploy nginx : `kubectl run nginx --image=nginx`
> 2. Listing the pods result : `nginx-7c87f569d-qcc2v   1/1       Running   0          11m`
> 3. Exposed nginx service : `kubectl expose deployment nginx --port 80 --type NodePort`
> 4. Listing services :
>    `NAME    TYPE          CLUSTER-IP    EXTERNAL-IP    PORT(S)             AGE`
>    `nginx     NodePort   10.32.0.115      <none>               80:31193/TCP   12m`
> 5. Get NodePort and Authorized it on Google VPC
>    `NODE_PORT=$(kubectl get svc nginx --output=jsonpath='{range .spec.ports[0]}{.nodePort}')`
>    `gcloud compute firewall-rules create kubernetes-the-hard-way-allow-nginx-service --allow=tcp:${NODE_PORT} --network kubernetes-the-hard-way`
> 6. Rule Created on Google VPC
>    `kubernetes-the-hard-way-allow-nginx-service  kubernetes-the-hard-way  INGRESS    1000      tcp:31193`
> 7. Get the Node external IP
>    `EXTERNAL_IP=$(gcloud compute instances describe worker-0 --format 'value(networkInterfaces[0].accessConfigs[0].natIP)')`
> 
> **8. Try to reach nginx from external**
> **`curl -I http://${EXTERNAL_IP}:${NODE_PORT}`**
> 
> **CURL command result on error :**
> **`curl: (7) Failed to connect to 35.197.74.10 port 31193: Connection refused`**
> 
> **NB : I've tried with worker-1 and worker-2 external IP but have the same result.**
> 
> **I don't know what happend, but i think kube-proxy can be the source, because I don't see any SERVICE Related rule in iptables**
> 
> **I execute command : `sudo iptables -t nat -nvL`**
> 
> Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
> pkts bytes target prot opt in out source destination
> 
> Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
> pkts bytes target prot opt in out source destination
> 
> Chain OUTPUT (policy ACCEPT 75 packets, 4500 bytes)
> pkts bytes target prot opt in out source destination
> 
> Chain POSTROUTING (policy ACCEPT 63 packets, 3780 bytes)
> pkts bytes target prot opt in out source destination
> 14662 881K KUBE-POSTROUTING all -- * * 0.0.0.0/0 0.0.0.0/0 /* kubernetes postrouting rules _/ 2342 141K CNI-01a2aee4e89a77122fb993ef all -- * * 10.200.0.0/24 0.0.0.0/0 /_ name: "bridge" id: "a899be0bb9dd387b2614eb255483c69134d98b91c9453abeba228aa259bcc610" */
> 
> Chain CNI-01a2aee4e89a77122fb993ef (1 references)
> pkts bytes target prot opt in out source destination
> 2340 140K ACCEPT all -- * * 0.0.0.0/0 10.200.0.0/24 /* name: "bridge" id: "a899be0bb9dd387b2614eb255483c69134d98b91c9453abeba228aa259bcc610" _/ 2 120 MASQUERADE all -- * * 0.0.0.0/0 !224.0.0.0/4 /_ name: "bridge" id: "a899be0bb9dd387b2614eb255483c69134d98b91c9453abeba228aa259bcc610" */
> 
> Chain KUBE-MARK-DROP (0 references)
> pkts bytes target prot opt in out source destination
> 0 0 MARK all -- * * 0.0.0.0/0 0.0.0.0/0 MARK or 0x8000
> 
> Chain KUBE-MARK-MASQ (0 references)
> pkts bytes target prot opt in out source destination
> 0 0 MARK all -- * * 0.0.0.0/0 0.0.0.0/0 MARK or 0x4000
> 
> Chain KUBE-POSTROUTING (1 references)
> pkts bytes target prot opt in out source destination
> 0 0 MASQUERADE all -- * * 0.0.0.0/0 0.0.0.0/0 /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000
> 
> **NB : This is my worker-0 configuration, worker-1 and worker-2 are similar**
> 
> **kube-proxy.service [worker-0]**
> Description=Kubernetes Kube Proxy
> Documentation=https://github.com/GoogleCloudPlatform/kubernetes
> 
> [Service]
> ExecStart=/usr/local/bin/kube-proxy
> --master=https://35.197.87.166:6443
> --cluster-cidr=10.200.0.0/16
> --kubeconfig=/var/lib/kube-proxy/kubeconfig
> --proxy-mode=iptables
> --v=2
> Restart=on-failure
> RestartSec=5
> 
> [Install]
> WantedBy=multi-user.target
> 
> **kubelet.service [worker-0]**
> 
> [Unit]
> Description=Kubernetes Kubelet
> Documentation=https://github.com/GoogleCloudPlatform/kubernetes
> After=cri-containerd.service
> Requires=cri-containerd.service
> 
> [Service]
> ExecStart=/usr/local/bin/kubelet
> --allow-privileged=true
> --anonymous-auth=false
> --authorization-mode=Webhook
> --client-ca-file=/var/lib/kubernetes/ca.pem
> --cluster-dns=10.32.0.10
> --cluster-domain=cluster.local
> --container-runtime=remote
> --container-runtime-endpoint=unix:///var/run/cri-containerd.sock
> --image-pull-progress-deadline=2m
> --kubeconfig=/var/lib/kubelet/kubeconfig
> --network-plugin=cni
> --pod-cidr=10.200.0.0/24
> --register-node=true
> --require-kubeconfig
> --runtime-request-timeout=15m
> --tls-cert-file=/var/lib/kubelet/worker-0.pem
> --tls-private-key-file=/var/lib/kubelet/worker-0-key.pem
> --v=2
> Restart=on-failure
> RestartSec=5
> 
> [Install]
> WantedBy=multi-user.target

I have the exac same issue, also did the same serie of checks and no luck how did you solve this @jetune ?

**Comment by anilanar** [comment]
In my case I had `udp:6443` instead of `tcp:6443` for the external firewall rule.
