### ISSUE TITLE
De-emphasizing Google Cloud Platform

### ISSUE THREAD

**Issue by stuartpb** [kelseyhightower/kubernetes-the-hard-way#268]
Based on [the conversation we just had](https://twitter.com/kelseyhightower/status/936637536327237633) (thanks again!), it looks like these docs are going to be a great way to learn Kubernetes: however, like I was saying at the start of the conversation, when I'd come across them independently, I was never able to get into it.

After having @kelseyhightower show me some of the later page contents, it's clear that this guide is mostly *not* GCP-specific: however, these few moments where it *is* - specifically, having the *introduction* specific to it - had kept me away from reading the document *altogether* (ie. I was under the impression that it was going to teach me how to use the Kubernetes Engine).

If it's OK, I'd like to submit some patches (where I can) to summarize what the Google-specific steps are for, and what any non-Google alternatives to the GCP-centric actions would need to accomplish to approximate them (ie. that a single Raspberry Pi could be used in place of provisioning multiple compute instances via `gcloud compute instances create`).

**Comment by kelseyhightower** [comment]
I think I've covered in the intro to the labs "This tutorial assumes you have access to the Google Cloud Platform. While GCP is used for basic infrastructure requirements the lessons learned in this tutorial can be applied to other platforms."
