### ISSUE TITLE
Why are we not using the IP of the load balanced Kubernetes Control plane in some of the config files?

### ISSUE THREAD

**Issue by KamranAzeem** [kelseyhightower/kubernetes-the-hard-way#27]
First, thank you Kelsey for a great HowTo! Very much appreciated! Indeed!

In [https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-worker.md](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-worker.md) , you create a file /var/lib/kubelet/kubeconfig . You are using a fixed IP of one of the controllers in that file, such as 
```
. . . 
clusters:
- cluster:
    certificate-authority: /var/lib/kubernetes/ca.pem
    server: https://10.240.0.21:6443
  name: kubernetes
. . . 
``` 
Shouldn't we be able to use the IP of the Kubernetes load balancer, which you setup at the end of the previous step, "Bootstrapping an H/A Kubernetes Control Plane" ? I am not sure why should we ask a worker node to access just one controller and not the IP address of the Kubernetes Control Plane". 

The same is observed when you create a systemd file for kube-proxy , in which you specify a fixed IP of only one of the controllers as 'master': 

```
. . . 
[Service]
ExecStart=/usr/bin/kube-proxy \
  --master=https://10.240.0.21:6443 \
  --kubeconfig=/var/lib/kubelet/kubeconfig \
  --proxy-mode=iptables \
  --v=2
. . . 
``` 
Ideally we should be using the IP of the load balancer which is put in front of the Kubernetes Control Plane? Or is there something wrong with my understanding? Or is there a limitation why we can't use that (load balancer IP) here?

**Comment by kelseyhightower** [comment]
Because GCP does not have internal load balancing. I figured it would be better to use the internal address for now. There is a ticket open to push support for multiple masters on each component.

**Comment by KamranAzeem** [comment]
Very nice! Thanks for clearing that up!

On Thu, Jul 14, 2016 at 6:55 PM, Kelsey Hightower <notifications@github.com>
wrote:

> Because GCP does not have internal load balancing. I figured it would be
> better to use the internal address for now. There is a ticket open to push
> support for multiple masters on each component.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/27#issuecomment-232725422>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEBWMRcLH9hu2glzeQQkJE0GlCpCCBuLks5qVmn1gaJpZM4JMcjJ>
> .
>



-- 
http://www.wbitt.com
Computer bugs are like shipwrecks. They are not found, unless they want to
be found.
