### ISSUE TITLE
bootstrap control plane and wait for what?

### ISSUE THREAD

**Issue by lukesiler** [kelseyhightower/kubernetes-the-hard-way#270]
After setting up k8s control plane services, there is an expectation to allow some time to pass for control plane to be healthy.  The statement is:

>> Allow up to 10 seconds for the Kubernetes API Server to fully initialize.

My question is what API endpoints need to be polled to determine that control plane is healthy and ready to be utilized?  

http://localhost:6443/healthz is one but are there others?  I'm expecting this one to indicate that local API server and etcd are ready to go.  The rest of the system should be eventually consistent with the state of API/etcd so maybe just this is enough - I'd appreciate hearing from your experiences here.

Thanks,
Luke

**Comment by tokiwinter** [comment]
I usually just poll the output of `kubectl get cs`, and once everything is healthy, presume it is good to go (that will fail completely if the API server is not ready).

**Comment by lukesiler** [comment]
thanks @tokiwinter - I am polling http://localhost:8080/healthz on third master and then configuring RBAC after that and then adding workers.  This seems to be reliable.  I'll use componentstatuses if I need more.
