### ISSUE TITLE
Suggestion: Kubernetes Fundamentals (LFS258)

### ISSUE THREAD

**Issue by mlasalmo** [kelseyhightower/kubernetes-the-hard-way#273]
The course Kubernetes Fundamentals (LFS258) includes kubernetes-the-hard-way as part of the curriculum, it would be nice to keep this repo updated and out of issues in a short term basis so it is easier to follow.

**Comment by tokiwinter** [comment]
@mlasalmo. I work for the LF and am the technical lead on CKA and CKAD, on the certification team, and work closely with the maintainers of LFS258 and the lab developers. If appropriate, I'd be happy to help take on a maintainer role here.

**Comment by mlasalmo** [comment]
Hi @tokiwinter, good to know and nice to meet you! Do you think we could find another channel (Slack maybe?) where we could exchange some feedback and issues I've been gathering along the course?

**Comment by tokiwinter** [comment]
Hi @mlasalmo - likewise :) Definitely - if you ping me via DM on the kubernetes or cloud-native slacks we can discuss there.

**Comment by kelseyhightower** [comment]
Thanks you two. I've updated the guide for Kubernetes 1.9. Everything is up to date and tested end to end. I'm about to add a security update to capture best practices over the next few weeks.
