### ISSUE TITLE
Getting a bunch of 404 when Initializers option is activated

### ISSUE THREAD

**Issue by nmaupu** [kelseyhightower/kubernetes-the-hard-way#276]
Hi,

I currently have an issue with the `apiserver` daemon using the default options provided. I have a lot of 404 pointing to `/apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations` which is an alpha feature.
Documentation is available here : https://kubernetes.io/docs/admin/extensible-admission-controllers

Not better when activating `--feature-gates=Initializers=true` flag.

```Dec 19 12:43:30 rmxk8sctl01 kube-apiserver[7012]: I1219 12:43:30.665129    7012 wrap.go:42] GET /apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations: (167.967µs) 404 [[kube-apiserver/v1.8.5 (linux/amd64) kubernetes/cce11c6] 127.0.0.1:45026]```

Removing `Initializers` from `--admission-control` flag fixes the problem but I am not sure to know exactly if this alpha feature is needed or not.

In any cases, kubernetes-the-hard-way's apiserver configuration does not seem to be optimal.
What do you think ?

EDIT : Adding `--runtime-config=admissionregistration.k8s.io/v1alpha1` solves the issue... feature-gates does not seem to activate anything for that particular feature though.

**Comment by den-is** [comment]
I got same 404 errors, thanks for pointing on documentation.
Interestingly apiserver built by kubeadm, has Initializers admission controller but doesn't `--runtime-config` - interesting how do they achieve that.

```
...
I0128 06:57:12.386983       1 initialization.go:90] enabled Initializers feature as part of admission plugin setup
...
W0128 06:57:12.556362       1 genericapiserver.go:342] Skipping API admissionregistration.k8s.io/v1alpha1 because it has no resources.
...
```
I'm not using `the_hardway` as only tutorital but combining all possible options I can find, and configs produced by kubeadm are one of the standards

**Comment by hgfischer** [comment]
I got a bit confused by the first post here.

What is the right/best approach, or is it both?

> Removing Initializers from --admission-control flag fixes the problem but I am not sure to know exactly if this alpha feature is needed or not.

> EDIT : Adding --runtime-config=admissionregistration.k8s.io/v1alpha1 solves the issue... feature-gates does not seem to activate anything for that particular feature though.

**Comment by den-is** [comment]
@hgfischer probably better to enable and play with it.
Some day it will become default option.
Also regarding my
> Interestingly apiserver built by kubeadm, has Initializers admission controller enabled, but doesn't have `--runtime-config` - interesting how do they achieve that.

Probably there is same "issue" just have not seen in logs because kubeadm has no verbose logging enabled for apiserver `--v=2` I wasn't able to enable it, but disabling verbose logging in my cluster achieves same log view as in kubeadm. :)

**Comment by rahulmishra** [comment]
@hgfischer 

If you want to experiment with Initializers, you need to leave the "admission-control" flag AS IS 

So, your kube-api server systemd unit will look as follows

--admission-control=Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
 --runtime-config=api/all=true,admissionregistration.k8s.io/v1alpha1=true

**Comment by den-is** [comment]
Current default action: https://github.com/kubernetes/kubernetes/pull/58428

**Comment by KlavsKlavsen** [comment]
Using this for 1.10.5 - I had to add the --runtime-config option (replacing what is in the guide curently) for this to work. --admission-control however has been deprecated by --enable-admision-control.. which is in the guide.
