### ISSUE TITLE
Mention gcloud ssh keys before using them

### ISSUE THREAD

**Issue by martinmosegaard** [kelseyhightower/kubernetes-the-hard-way#280]
In chapter 4, `04-certificate-authority.md`, I got to run `gcloud compute scp` commands, which prompted me for SSH key password and then generated keys, because it was the first time I ran SSH/SCP commands against gcloud.

It might be worth mentioning in the gcloud prerequisites.

**Comment by kelseyhightower** [comment]
Good suggestion. Fixed on the 1.10.2 branch: https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/1.10.2/docs/03-compute-resources.md#configuring-ssh-access
