### ISSUE TITLE
Cannot start kube-proxy: Needs Config File

### ISSUE THREAD

**Issue by rahulmishra** [kelseyhightower/kubernetes-the-hard-way#284]
I have been following this document to set up a cluster from scratch on a bunch of local vagrant machines. I have been running into issues with kube-proxy though.

When i tried to create the kube-proxy service with

>  cat > kube-proxy.service <<EOF
[Unit]
Description=Kubernetes Kube Proxy
Documentation=https://github.com/kubernetes/kubernetes
[Service]
ExecStart=/usr/local/bin/kube-proxy \\
  --cluster-cidr=10.200.0.0/16 \\
  --kubeconfig=/var/lib/kube-proxy/kubeconfig \\
  --proxy-mode=iptables \\
  --v=2
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
EOF 
When i did this, journalctl reported the following:

> Jan 02 17:47:15 slave-1 kube-proxy[1568]: W0102 17:47:15.774208    1568 server.go:185] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file
Jan 02 17:47:15 slave-1 kube-proxy[1568]: F0102 17:47:15.869049    1568 helpers.go:119] error: no configuration has been provided
Jan 02 17:47:15 slave-1 systemd[1]: kube-proxy.service: main process exited, code=exited, status=255/n/a
Jan 02 17:47:15 slave-1 systemd[1]: Unit kube-proxy.service entered failed state.
Jan 02 17:47:15 slave-1 systemd[1]: kube-proxy.service failed.

Alright, i understand that i need to give a config file to kube-proxy.

I edited the systemd service definition to as follows:

[Unit]
Description=Kubernetes Kube Proxy
Documentation=https://github.com/kubernetes/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-proxy --config /var/lib/kube-proxy/kubeproxy.conf
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

On querying for status of kube-proxy , it reports

> ● kube-proxy.service - Kubernetes Kube Proxy
>    Loaded: loaded (/etc/systemd/system/kube-proxy.service; enabled; vendor preset: disabled)
>    Active: activating (auto-restart) (Result: exit-code) since Tue 2018-01-02 22:28:55 UTC; 4s ago
>      Docs: https://github.com/kubernetes/kubernetes
>   Process: 5239 ExecStart=/usr/local/bin/kube-proxy --config /var/lib/kube-proxy/kubeproxy.conf (code=exited, status=1/FAILURE)
>  Main PID: 5239 (code=exited, status=1/FAILURE)
> 
> Jan 02 22:28:55 slave-1 systemd[1]: kube-proxy.service: main process exited, code=exited, status=1/FAILURE
> Jan 02 22:28:55 slave-1 systemd[1]: Unit kube-proxy.service entered failed state.
> Jan 02 22:28:55 slave-1 systemd[1]: kube-proxy.service failed.

Now i went and checked the journal, and it tells me this

> Jan 02 22:28:44 slave-1 systemd[1]: Starting Kubernetes Kube Proxy...
Jan 02 22:28:44 slave-1 kube-proxy[5203]: I0102 22:28:44.722197    5203 feature_gate.go:184] feature gates: map[]
Jan 02 22:28:44 slave-1 kube-proxy[5203]: error: no configuration has been provided
Jan 02 22:28:44 slave-1 systemd[1]: kube-proxy.service: main process exited, code=exited, status=1/FAILURE
Jan 02 22:28:44 slave-1 systemd[1]: Unit kube-proxy.service entered failed state.
Jan 02 22:28:44 slave-1 systemd[1]: kube-proxy.service failed.
Jan 02 22:28:49 slave-1 systemd[1]: kube-proxy.service holdoff time over, scheduling restart.

The error tells me that i did not provide configuration to kube-proxy, but i clearly did because systemctl shows it.

Kubernetes Version: 1.9.0
OS : CentOS 7

Can someone help?

**Comment by rahulmishra** [comment]
On debugging this a little further and attempting to start kube-proxy manually with 
/usr/local/bin/kube-proxy --config /tmp/kp.config --v 10
I see the following logs

> I0103 00:04:44.333111   11506 feature_gate.go:184] feature gates: map[APIListChunking:true]
I0103 00:04:44.337952   11506 iptables.go:589] couldn't get iptables-restore version; assuming it doesn't support --wait
I0103 00:04:44.341662   11506 loader.go:357] Config loaded from file /var/lib/kube-proxy/kubeconfig
F0103 00:04:44.341772   11506 helpers.go:119] error: no configuration has been provided

What configuration is it looking for? Clearly it read my config file because thats where the feature gates and kubeconfig locations are defined..

**Comment by tokiwinter** [comment]
Is `/var/lib/kube-proxy/kubeconfig` present, syntactically correct, and properly formatted?

**Comment by rahulmishra** [comment]
My kubeconfig was syntactially valid but it didn't have a current-context set. When i set the current-context, it bootstrapped.
Thanks for the pointer

**Comment by Klmanjaro** [comment]
Is your kubeconfig a yaml file ? I am getting this error: 
/usr/local/bin/kube-proxy --config ./kube-proxy.kubeconfig --v 10
F0430 12:51:03.473083   18711 helpers.go:119] error: no kind "Config" is registered for version "v1"
Will you be able to share the file? thanks.

**Comment by caemiller** [comment]
> Is `/var/lib/kube-proxy/kubeconfig` present, syntactically correct, and properly formatted?

Thank you @tokiwinter. I had this same is, and my problem ended up being a typo in the kubeconfig file. I'm new to Kubernetes, and would have never thought my issue would be a typo in my kubeconfig file when the error was "no configuration has been provided error."

**Comment by aneeq2021** [comment]
@rahulmishra @caemiller  could you please share your kubeconfig file. I am facing the same issue .

 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/kube-proxy-config.yaml 
F0209 06:42:08.580939   13727 server.go:377] invalid configuration: no configuration has been provided


more /var/lib/kube-proxy/kubeconfig 
{ 
 kubectl config set-cluster kubernetes-the-hard-way \
    --certificate-authority=ca.crt \
    --embed-certs=true \
    --server=https://192.168.1.186:6443 \
    --kubeconfig=kube-proxy.kubeconfig

  kubectl config set-credentials system:kube-proxy \
    --client-certificate=kube-proxy.crt \
    --client-key=kube-proxy.key \
    --embed-certs=true \
    --kubeconfig=kube-proxy.kubeconfig

  kubectl config set-context default \
    --cluster=kubernetes-the-hard-way \
    --user=system:kube-proxy \
    --kubeconfig=kube-proxy.kubeconfig

  kubectl config use-context default --kubeconfig=kube-proxy.kubeconfig
}
