### ISSUE TITLE
cri-containerd setup

### ISSUE THREAD

**Issue by snyamars** [kelseyhightower/kubernetes-the-hard-way#300]
Hi,
To setup the lab on AWS, can I assume that containerd setup needs to be installed as a prerequisite?

Rgds
Sreekanth

**Comment by frezbo** [comment]
Well you need to only setup cri-containerd on workers nodes only. I followed along the docs and made changes as per AWS, and for networking I used flannel.

**Comment by snyamars** [comment]
Thanks @frezbo. Can I do the same using docker installation instead of cri-containerd?
Could you guide me to AWS documentation location by any chance?

**Comment by frezbo** [comment]
Wel this is my kubelet config with AWS, BTW I am still on docker 1.12

**Comment by snyamars** [comment]
Thanks @frezbo. It helps.
