### ISSUE TITLE
 Changing the bind address for cri-container

### ISSUE THREAD

**Issue by rahulmishra** [kelseyhightower/kubernetes-the-hard-way#301]
I am running into an issue when testing the cluster on Vagrant.

When i perform 
kubectl exec -ti ${POD_NAME} ls /

I get an  error 
Error from server: error dialing backend: dial tcp 10.0.2.15:10010: getsockopt: connection refused

I looked into the kube api server logs and they tell me that it's getting a HTTP 500

`Jan 23 18:53:43 k8s-master kube-apiserver[10644]: E0123 18:53:43.343928   10644 status.go:64] apiserver received an error that is not an metav1.Status: error dialing backend: dial tcp 10.0.2.15:10010: getsockopt: connection refused
Jan 23 18:53:43 k8s-master kube-apiserver[10644]: I0123 18:53:43.344598   10644 wrap.go:42] POST /api/v1/namespaces/default/pods/nginx-8586cf59-kkqns/exec?command=ls&command=%2F&container=nginx&container=nginx&stdin=true&stdout=true&tty=true: (31.151ms) 500
`
I realized that 10010 is the port at which cri-container is listening
root@k8s-slave-1:~# netstat -anlp|grep 10010
tcp        0      0 10.0.2.15:10010         0.0.0.0:*               LISTEN      11358/cri-container

However, it seems that it is using the incorrect address on Vagrant(10.0.2.15). I have a private network set up and i would like cri-container to use that address instead.

Where can i configure that? I have been unable to locate any documentation on the same.

Thanks in advance

**Comment by rahulmishra** [comment]
As an update, i switched to using docker instead of cri-container and i can perform "exec" just fine. It would still be helpful to know how to override the default bind address of cri-container

**Comment by kelseyhightower** [comment]
I'm unable to support Vagrant at this time.

**Comment by rahulmishra** [comment]
For those who stumble upon this thread and run into the same issue i did.

You should be able to change the adddress and port by specifying the following flags in the systemd unit file
    --stream-addr 
    --stream-port string  

Reference: https://github.com/containerd/cri-containerd/releases (Scroll to the bottom)

**Comment by jdel** [comment]
Thanks a lot for this. I spent hours trying to give `--address, --node-ip` and other parameters to kubelet assuming it was the culprit...

**Comment by ansilh** [comment]
My VirtualBox with NAT had same problem. I was trying to use the internal IP and every time containerd picks NAT IP to listen streaming.
Found that the default route interface is the one which will be used for streaming by containerd and here it was my NAT gateway. As NAT IP is not routable in VirtualBox,  it was failing.

After adding below to the top of `/etc/containerd/config.toml` and restarting containerd fixed my issue

```
[plugins.cri]
  stream_server_address = "<worker host-only ip or routable IP>"
```
