### ISSUE TITLE
Client and Server certificates on Ubuntu 

### ISSUE THREAD

**Issue by containertime** [kelseyhightower/kubernetes-the-hard-way#306]
Trying to generate client and server certificates, it fails with an error message:

Failed to load config file: {"code":5200,"message":"failed to unmarshal configuration: invalid character 'k' after array element"}Failed to parse input: unexpected end of JSON input

Could you please assist?

**Comment by rahulmishra** [comment]
Could you please post the command you ran, the CSR, config files you used?

**Comment by containertime** [comment]
Sorry for the delay in responding to your assistance.
Am following the document, the area where i got stuck was: Generate the
admin client certificate and private key:

cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=kubernetes \
  admin-csr.json | cfssljson -bare admin

And the operating system details:
Distributor ID:    Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:    16.04
Codename:    xenial


Let me know if you need any additional information, will be happy to
provide and continue with the tutorial. Thank you for a great tutorial.

Regards,
Sri
