### ISSUE TITLE
admin kubeconfig (10) should be created before control plane (08)? 

### ISSUE THREAD

**Issue by burton-scalefastr** [kelseyhightower/kubernetes-the-hard-way#307]
I think the admin user should be created before the control plane...

My 

kubectl get componentstatuses

from 08 won't work without a config..

Granted I'm doing this a bit differently as I'm porting your docs to ansible but I think this is correct.

**Comment by waynr** [comment]
`kubectl get componentstatuses` is meant to be run on each of the controller nodes if I understand correctly. That's how I've been running it anyway.

**Comment by kelseyhightower** [comment]
Yes, as mentioned in the docs you should run those commands on the controller nodes as a quick smoke test.
