### ISSUE TITLE
failed to install cfssl in Ubuntu 17.10 and Linux Mint 18.2

### ISSUE THREAD

**Issue by thestrid3r** [kelseyhightower/kubernetes-the-hard-way#318]
I tried to install  cfssl using the given instruction and it's failed to install .
I have installed it using ` sudo apt-get install golang-cfssl`

**Comment by rahulmishra** [comment]
Can you install golang, set up GOPATH and use
`go get -u github.com/cloudflare/cfssl/cmd/cfssl`

**Comment by indrayam** [comment]
Btw, you will get compilation issues with go 1.10. You will be better off using go 1.9.x to run the command that @rahulmishra mentioned:
`go get -u github.com/cloudflare/cfssl/cmd/cfssl`
