### ISSUE TITLE
Setup Kubernetes in a bare-metal data center

### ISSUE THREAD

**Issue by avnsiva** [kelseyhightower/kubernetes-the-hard-way#32]
Hi,
I also read your book on Kubernetes Up and Running. In both this kubernetes-the-hard-way and in the book Kubernetes Up and Running, the examples are there only for GCE.

Will be much helpful if you could help with setting up kubernetes with bare metal multi host servers.

**Comment by avnsiva** [comment]
I guess most of the steps we are able to get it.

The concept of creating a network, route are specific to GCE. How do we implement this if we have a bare metal servers?

**Comment by wmangano** [comment]
correct me if im wrong @kelseyhightower ....but the loadbalancer/ingress steps are a little bit different. with baremetal or "non-cloud" compute resources you have to setup an ingress lb like vulcand or traeffik to route the traffic to your containers.

what about the dns or networking? is the skydns part different? do we have to setup flannel,calico for baremetal?

**Comment by Bregor** [comment]
@wmangano to be fair you could use good old NGINX right on bare-metal host which resolver is pointing to kube-dns and set upstreams like following:

    upstream kube-fb-bot {
      server fb.bots.svc.kubernetes.local:6680;
    }

**Comment by kelseyhightower** [comment]
@Bregor is right. When dealing with bare-metal you'll have to bring your own LB and configure your router. In the updated networking section for configuring routes I attempt to call this out.
