### ISSUE TITLE
Error: Could not fetch project

### ISSUE THREAD

**Issue by matthew-piziak** [kelseyhightower/kubernetes-the-hard-way#321]
I am following along in the tutorial and in [section 3](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-compute-resources.md) I get a "could not find project" error:

```
~ $ gcloud compute networks create kubernetes-the-hard-way --subnet-mode custom
ERROR: (gcloud.compute.networks.create) Could not fetch resource:
 - Failed to find project kubernetes-the-hard-way
```

My configuration seems to be set...

```
~ $ gcloud config list
[core]
account = …
disable_usage_reporting = True
project = kubernetes-the-hard-way

Your active configuration is: [default]
```

...and I am logged in with `gcloud auth login` and `gcloud auth application-default login`.

I may have missed a step but I can't find it.

**Comment by cch0** [comment]
compared to mine, didn't see region and zone in your output.

**Comment by kelseyhightower** [comment]
Please set a default region and zone.
