### ISSUE TITLE
Secure scheduler and controller manager access to the Kubernetes API Server

### ISSUE THREAD

**Issue by discordianfish** [kelseyhightower/kubernetes-the-hard-way#323]
Looks like scheduler/controller manager don't use client cert auth, which requires the apiserver to allow insecure access:

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md#client-authentication-configs

These components should also use a kubeconfig with client cert for authentication.

**Comment by kelseyhightower** [comment]
The scheduler and controller manager now use client auth and kubeconfigs on the 1.10.2 branch
