### ISSUE TITLE
Generating KUBERNETES_PUBLIC_ADDRESS gives error

### ISSUE THREAD

**Issue by dwschulze** [kelseyhightower/kubernetes-the-hard-way#327]
KUBERNETES_PUBLIC_ADDRESS=$(gcloud compute addresses describe kubernetes-the-hard-way \
  --region $(gcloud config get-value compute/region) \
  --format 'value(address)')

gives

ERROR: (gcloud.compute.addresses.describe) Could not fetch resource:
 - The resource 'projects/whi-selfserv-172722/regions/us-west1/addresses/kubernetes-the-hard-way' was not found

**Comment by hareeshrao4839** [comment]
please authenticate googleSDK and Set Default region then  try

**Comment by ranaskr** [comment]
Verify if compute/region is set in your gcloud config by executing - 
`gcloud config get-value compute/region` 
If it shows (unset), then you need to set the region 
`gcloud config set compute/region us-west1`
I am using us-west1, so I set it to us-west1. You could use any other region.
Now, Verify again by executing
`gcloud config list`
You should see default region in gcloud config.
