### ISSUE TITLE
Control Plane instructions don't install kube-proxy

### ISSUE THREAD

**Issue by cyrus-mc** [kelseyhightower/kubernetes-the-hard-way#330]
Is there a reason why this instructions don't include the proxy on the control plane? 

Without it service IP table rules don't get created on the control plane nodes and this presents issues with add-ons like fluentd that run as a daemonset and utilize the k8s API for meta data retrieval.

**Comment by hareeshrao4839** [comment]
all app's expose towards internet via kube-Proxy, Control plane creates ingress rules and Services, so those rule's/Services are applied in Node kubeProxy.

**Comment by kelseyhightower** [comment]
@hareeshrao4839 Is correct. The API server is reachable by all worker nodes. In this guide the API server does not have the kubelet installed and will never run any pods provisioned via a daemonset.
