### ISSUE TITLE
Cant connect apiserver over kubernetes service

### ISSUE THREAD

**Issue by hieuvuvan** [kelseyhightower/kubernetes-the-hard-way#331]
`kubectl get svc` gived me
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.2.0.1     <none>        443/TCP   2h
nginx        ClusterIP   10.2.88.12   <none>        80/TCP    1h

but when i try `curl https://10.2.0.1:443` from worker node received:
"curl: (7) Failed to connect to 10.2.0.1 port 443: Connection refused"

**Comment by kelseyhightower** [comment]
Please double check the cluster IP:

```
kubectl get svc
```
```
NAME         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.32.0.1     <none>        443/TCP        18h
```

Testing from the worker nodes:

```
gcloud compute ssh worker-0
```

```
curl -i -k https://10.32.0.1:443/healthz
```
```
HTTP/2 200
content-type: text/plain; charset=utf-8
content-length: 2
date: Sun, 13 May 2018 15:47:29 GMT

ok
```
