### ISSUE TITLE
dashboard access

### ISSUE THREAD

**Issue by verizonold** [kelseyhightower/kubernetes-the-hard-way#336]
I follow the instructions here and deploy the dashboard. However, I get the following error when I access in browser:
Error: 'dial tcp 10.244.1.5:8443: getsockopt: connection timed out'
Trying to reach: 'https://10.244.1.5:8443/'

I see that the dashboard is deployed on a node with a IP of 10.244.1.5 and I can ping this container from the host node. However, from master, the host is reachable but not the container. Am I missing any routes that I should be creating? I am running both master and  minion in Virtual Box and bridge adapter/NAT interfaces.

Your help much appreciated.

**Comment by kelseyhightower** [comment]
Unfortunately this guide does not cover the Kubernetes dashboard.
