### ISSUE TITLE
kube-proxy service fails to start

### ISSUE THREAD

**Issue by Klmanjaro** [kelseyhightower/kubernetes-the-hard-way#339]
I am following this primer to set up a basic kubernetes cluster. Docs are well-written!

I run into this issue when starting kube-proxy service.Apr 18 16:05:15  "hostname" systemd[1]: Started Kubernetes Kube Proxy.
Apr 18 16:05:15 "hostname" systemd[1]: Starting Kubernetes Kube Proxy...
Apr 18 16:05:15 "hostname" kube-proxy[22656]: W0418 16:05:15.271210   22656 server.go:185] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
Apr 18 16:05:15 "hostname" kube-proxy[22656]: F0418 16:05:15.281932   22656 helpers.go:119] error: no configuration has been provided
Apr 18 16:05:15 "hostname" systemd[1]: kube-proxy.service: main process exited, code=exited, status=255/n/a
Apr 18 16:05:15 "hostname" systemd[1]: Unit kube-proxy.service entered failed state.
Apr 18 16:05:15 "hostname" systemd[1]: kube-proxy.service failed.

How to go about avoiding this issue? Instead of --kubeconfig in kube-proxy.service do we use --config flag ? Could I get an example of that file?
Does this documentation need to be updated to reflect this change?
Any pointers are appreciated!

**Comment by Klmanjaro** [comment]
I worked on kubeadm and got a cluster deployed.
Now looking back at this issue again:
I tried this: 
/usr/local/bin/kube-proxy --config ./kube-proxy.kubeconfig --v 10
F0430 12:51:03.473083   18711 helpers.go:119] error: no kind "Config" is registered for version "v1"
has anyone seen this before?
thanks.

**Comment by kelseyhightower** [comment]
The kube-proxy now uses a working configuration file with the `--config` flag
