### ISSUE TITLE
Google Cloud Platform free account limited to 8 compute instances

### ISSUE THREAD

**Issue by twakes** [kelseyhightower/kubernetes-the-hard-way#34]
The workshop uses 9 instances but the GCP free account is limited to 8. While not a big deal, it might improve UX to change example to use 8 instances to accommodate the limits on the GCE free account...or perhaps just add a note in the beginning acknowledging this.

**Comment by andrenth** [comment]
Would it be a bad idea to run etcd and the kubernetes controllers on the same machines, assuming etcd will only be used for kubernetes?

**Comment by aronchick** [comment]
Yes - generally these should be separate machines. Is there a particular
reason you'd want to overlap?

**Comment by andrenth** [comment]
In my particular use case I'm interest in a bare metal cluster, so reducing from 6 to 3 servers for Kubernetes infrastructure would be nice. I'm not sure if the hardware requirements to make this a good idea are documented anywhere though.

But my answer was in the context of @twakes' question as it would allow him to stay within the GCP free account limits.

**Comment by aronchick** [comment]
Ah -- well, as I mentioned, you can do it, but we don't recommend it. If
you had to overlap machines, you'd actually want to overlap the master with
the etcd, rather than where you run the pods.

**Comment by andrenth** [comment]
That's actually what I meant when I mentioned "controllers" -- the Kubernetes control plane in the same servers as etcd. The workers would be left alone.

**Comment by aronchick** [comment]
Ah - "controllers" also means replication controllers :)

As I mentioned, not ideal, but certainly acceptable.

**Comment by andrenth** [comment]
Oops, sorry for that :) I'm not very familiar with Kubernetes yet and was unclear about what I meant.

**Comment by kelseyhightower** [comment]
I've added a note to the infra setup guide in step one that users can skip setting up worker2 if they are using the GCP free trial.
