### ISSUE TITLE
curl complains certificates related error while visiting the load balancer 

### ISSUE THREAD

**Issue by changtimwu** [kelseyhightower/kubernetes-the-hard-way#343]
Just for record.  At the [very last instruction of chap 08](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md#verification-1), my curl on MacOS complains

```
curl  --cacert ca.pem https://${KUBERNETES_PUBLIC_ADDRESS}:6443/version
curl: (51) SSL: no alternative certificate subject name matches target host name 'xx.xx.xx.xx'
```

This can be easily fixed by adding `--insecure` option. 
```
curl --insecure --cacert ca.pem https://${KUBERNETES_PUBLIC_ADDRESS}:6443/version
{
  "major": "1",
  "minor": "9",
  "gitVersion": "v1.9.0",
  "gitCommit": "925c127ec6b946659ad0fd596fa959be43f0cc05",
  "gitTreeState": "clean",
  "buildDate": "2017-12-15T20:55:30Z",
  "goVersion": "go1.9.2",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Comment by changtimwu** [comment]
never mind.  This issue seems due to `f1-micro` instance.

**Comment by Hashfyre** [comment]
This happens on the recommended n1-standard-1 instance type too.
<img width="324" alt="screen shot 2018-10-11 at 12 31 07 pm" src="https://user-images.githubusercontent.com/581287/46786155-a9d2a700-cd51-11e8-8bc1-e4c999c26cd0.png">
![screen shot 2018-10-11 at 12 31 34 pm](https://user-images.githubusercontent.com/581287/46786156-a9d2a700-cd51-11e8-82ca-b697948d0363.png)

**Comment by fahlke** [comment]
Very likely the certificates that were created [here](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-kubernetes-api-server-certificate), are missing the Kubernetes public IP address.

Check the `kubernetes.pem` on all controller nodes by running the following command:
    
    openssl x509 \
      -in /var/lib/kubernetes/kubernetes.pem \
      -text \
      -noout | grep -A1 "Subject Alternative Name"`

This should include the Kubernetes public IP address somewhere.

If it does not include it, you need to recreate the certificate (`kubernetes.pem`), redeploy it on all controller nodes and restart the services that use it (at least the `kube-apiserver` and `etcd`).
