### ISSUE TITLE
Unclear if RBAC for Kubelet Authorization needs to be run on all controllers

### ISSUE THREAD

**Issue by irbull** [kelseyhightower/kubernetes-the-hard-way#348]
Most controller/worker commands must be executed on every instance, and this is often explicitly mentioned:

> The commands in this lab must be run on each controller instance: controller-0, controller-1, and controller-2. Login to each controller instance using the gcloud command. Example:

However, the section on *RBAC for Kubelet Authorization* only mentions _controller-0_ and doesn't give any indication that this must be run on each controller instance.

> gcloud compute ssh controller-0

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md#rbac-for-kubelet-authorization

If setting up RBAC is actually different from the rest, this should be explicitly mentioned; otherwise, if this command needs to be run across all the controllers, then that should be mentioned. I'd be happy to put together a pull request for this.

**Comment by kelseyhightower** [comment]
It's because RBAC is configured through the API server, which is then stored in etcd, and will be used by all future interactions with the API. I can add some clarity.

**Comment by anthonyclarka2** [comment]
I too ran into the ambiguity of RBAC-for-kubelet-authorization. May I humbly suggest the following addition before the "gcloud compute ssh controller-0" line:

"In this section you are interacting with your cluster as a whole, so these following 2 role creation commands only need to be run from a single controller"

I am learning a lot by following this guide and I wanted to say a huge thank you for writing it!

**Comment by kelseyhightower** [comment]
Thanks for the suggestion. I've added clarifying comments to the section. This is now fixed on master.
