### ISSUE TITLE
Unable to provision dynamic storage 

### ISSUE THREAD

**Issue by fii** [kelseyhightower/kubernetes-the-hard-way#349]
Provisioning dynamic storage fails with this error message. I'll keeping hacking it but just wondering if anyone has seen this ? 

  Warning  ProvisioningFailed  38s (x9 over 8m)  persistentvolume-controller  Failed to provision volume with StorageClass "default": Failed to get GCE GCECloudProvider with error <nil>

**Comment by kelseyhightower** [comment]
@fii You need to configure a cloud provider first. An exercise I've left for the reader.
