### ISSUE TITLE
kube-scheduler doesn't start

### ISSUE THREAD

**Issue by stpabhi** [kelseyhightower/kubernetes-the-hard-way#351]
./kube-scheduler --config=/etc/kubernetes/config/kube-scheduler.yaml --v=2
I0520 02:15:58.882580   71670 flags.go:27] FLAG: --address=""
I0520 02:15:58.882952   71670 flags.go:27] FLAG: --algorithm-provider=""
I0520 02:15:58.883124   71670 flags.go:27] FLAG: --alsologtostderr="false"
I0520 02:15:58.883314   71670 flags.go:27] FLAG: --config="/etc/kubernetes/config/kube-scheduler.yaml"
I0520 02:15:58.883486   71670 flags.go:27] FLAG: --contention-profiling="false"
I0520 02:15:58.883649   71670 flags.go:27] FLAG: --failure-domains="kubernetes.io/hostname,failure-domain.beta.kubernetes.io/zone,failure-domain.beta.kubernetes.io/region"
I0520 02:15:58.883836   71670 flags.go:27] FLAG: --feature-gates=""
I0520 02:15:58.884001   71670 flags.go:27] FLAG: --hard-pod-affinity-symmetric-weight="1"
I0520 02:15:58.884180   71670 flags.go:27] FLAG: --help="false"
I0520 02:15:58.884474   71670 flags.go:27] FLAG: --kube-api-burst="100"
I0520 02:15:58.884641   71670 flags.go:27] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0520 02:15:58.884821   71670 flags.go:27] FLAG: --kube-api-qps="50"
I0520 02:15:58.884989   71670 flags.go:27] FLAG: --kubeconfig=""
I0520 02:15:58.885150   71670 flags.go:27] FLAG: --leader-elect="true"
I0520 02:15:58.885321   71670 flags.go:27] FLAG: --leader-elect-lease-duration="15s"
I0520 02:15:58.885494   71670 flags.go:27] FLAG: --leader-elect-renew-deadline="10s"
I0520 02:15:58.885655   71670 flags.go:27] FLAG: --leader-elect-resource-lock="endpoints"
I0520 02:15:58.885827   71670 flags.go:27] FLAG: --leader-elect-retry-period="2s"
I0520 02:15:58.885990   71670 flags.go:27] FLAG: --lock-object-name="kube-scheduler"
I0520 02:15:58.886151   71670 flags.go:27] FLAG: --lock-object-namespace="kube-system"
I0520 02:15:58.886321   71670 flags.go:27] FLAG: --log-backtrace-at=":0"
I0520 02:15:58.886502   71670 flags.go:27] FLAG: --log-dir=""
I0520 02:15:58.886664   71670 flags.go:27] FLAG: --log-flush-frequency="5s"
I0520 02:15:58.886837   71670 flags.go:27] FLAG: --logtostderr="true"
I0520 02:15:58.886998   71670 flags.go:27] FLAG: --master=""
I0520 02:15:58.887176   71670 flags.go:27] FLAG: --policy-config-file=""
I0520 02:15:58.887339   71670 flags.go:27] FLAG: --policy-configmap=""
I0520 02:15:58.887500   71670 flags.go:27] FLAG: --policy-configmap-namespace=""
I0520 02:15:58.887661   71670 flags.go:27] FLAG: --port="10251"
I0520 02:15:58.887834   71670 flags.go:27] FLAG: --profiling="false"
I0520 02:15:58.887995   71670 flags.go:27] FLAG: --scheduler-name="default-scheduler"
I0520 02:15:58.888172   71670 flags.go:27] FLAG: --stderrthreshold="2"
I0520 02:15:58.888361   71670 flags.go:27] FLAG: --use-legacy-policy-config="false"
I0520 02:15:58.888524   71670 flags.go:27] FLAG: --v="2"
I0520 02:15:58.888686   71670 flags.go:27] FLAG: --version="false"
I0520 02:15:58.888861   71670 flags.go:27] FLAG: --vmodule=""
F0520 02:15:58.892978   71670 helpers.go:119] error: no configuration has been provided

**Comment by stpabhi** [comment]
Never mind. I didn't run the below commands on the node. It's working now.

kubectl config set-cluster kubernetes \
    --certificate-authority=ca.pem \
    --embed-certs=true \
    --server=https://127.0.0.1:6443 \
    --kubeconfig=kube-scheduler.kubeconfig

  kubectl config set-credentials system:kube-scheduler \
    --client-certificate=kube-scheduler.pem \
    --client-key=kube-scheduler-key.pem \
    --embed-certs=true \
    --kubeconfig=kube-scheduler.kubeconfig

  kubectl config set-context default \
    --cluster=kubernetes \
    --user=system:kube-scheduler \
    --kubeconfig=kube-scheduler.kubeconfig

**Comment by gerrywastaken** [comment]
Thanks, it was also a config issue for me due to a typo in the conf file I had renamed the cluster but hadn't used the exact same name everywhere.
