### ISSUE TITLE
Unable to register node with API server: node is forbidden - 09

### ISSUE THREAD

**Issue by AlexandrSemak** [kelseyhightower/kubernetes-the-hard-way#353]
HI Everyone,
I faced with problem...
In module **09-bootstrapping-kubernetes-workers.md** i try get nodes but haven't result.

> No resources found.

In log API service a have follow message:

> Unable to register node "worker-0" with API server: nodes "worker-0" is forbidden: could not determine node from user 
> eviction manager: failed to get get summary stats: failed to get node info: node "worker-0" not found

Maybe some had been faced with this?

**Comment by isaidashev** [comment]
Yes. I have that problem

**Comment by biancajiang** [comment]
@alexandrsemak any resolution or trouble shooting hints to this?

**Comment by biancajiang** [comment]
never mind.  Found my issue is the same as https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/439#issuecomment-474336901
