### ISSUE TITLE
Problems with authorization of kube-controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by IvanovOleg** [kelseyhightower/kubernetes-the-hard-way#354]
`E0522 21:53:26.598561       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Unauthorized`

`E0522 21:54:37.749664       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.PersistentVolume: Unauthorized`
kubectl cluster-info --kubeconfig=kube-controller-manager.kubeconfig asks password
kubectl cluster-info --kubeconfig=admin.kubeconfig works fine

**Comment by stgleb** [comment]
@IvanovOleg how did you resolve it?

**Comment by IvanovOleg** [comment]
yes

**Comment by stgleb** [comment]
@IvanovOleg Could you please share something about that, because it looks like a have the same problem. I can authorize and get data from kube-api with curl usign cert and key, but kube-controller-manager fails with unathorized error.

**Comment by IvanovOleg** [comment]
@stgleb 
Do you have the exact same error?

**Comment by stgleb** [comment]
Yes,  I do

**Comment by IvanovOleg** [comment]
Then I recommend you to check controller-manager log file and find which resource it is trying to get. Find in the kubernetes api reference an appropriate path for that resource, perform the curl command with ssl certificates you have and see if you get a responce from api server.

**Comment by stgleb** [comment]
Thanks!

**Comment by dhirajkumar055** [comment]
If not using controller and scheduler cluster, make below parameters as false in below files.
--leader-elect=false
Files at : /etc/kubernetes/manifests/kube-controller-manager.yaml and /etc/kubernetes/kube-scheduler.yaml

**Comment by davidtinker** [comment]
I had to reboot the node with the problematic kube-controller-manager to fix this. It seems 'kubeadm certs renew all' and 'systemctl restart kubelet' doesn't always work.

**Comment by davidtinker** [comment]
Moving the manifest file out of /etc/kubernetes/manifests, waiting a bit to check process has stopped, and putting it back works.

**Comment by christian-2** [comment]
Same story here: problem occurred after `kubeadm certs renew all`. Log files for `kube-scheduler` showed lots of "unauthorized" errors (similar also for `kube-controller-manager`) even though manual inspection suggested that JWT token in `serviceaccount/default` in namespace `kube-system` verified alright against `/etc/kubernetes/pki/sa.pub`. Reboot of master nodes (I have two of them in an HA setup) apparently resolved the issue. The cluster concerned is running Kubernetes v1.23.1.

**Comment by schmichri** [comment]
Reboot of master nodes helped also on my v1.20.15 cluster

**Comment by Tankchupa** [comment]
> Moving the manifest file out of /etc/kubernetes/manifests, waiting a bit to check process has stopped, and putting it back works.

This has worked for me without the need to restart the master nodes. Thanks!

**Comment by yudaprama** [comment]
> Moving the manifest file out of /etc/kubernetes/manifests, waiting a bit to check process has stopped, and putting it back works.

Thanks this work for me too. How did you manage to know this will work?

**Comment by davidtinker** [comment]
I didn't. Just gave it a try and luckily it did.

**Comment by auxsvr** [comment]
In my case, I had to move both the controller-manager and the scheduler manifests.

**Comment by ahmedshehata101** [comment]
> Moving the manifest file out of /etc/kubernetes/manifests, waiting a bit to check process has stopped, and putting it back works.

This worked for me in version 1.26

**Comment by verticall** [comment]
> Moving the manifest file out of /etc/kubernetes/manifests, waiting a bit to check process has stopped, and putting it back works.

It work.

**Comment by kuizhiqing** [comment]
> Moving the manifest file out of /etc/kubernetes/manifests, waiting a bit to check process has stopped, and putting it back works.

It works.

**Comment by khacdatdo** [comment]
For anyone wonder how or why it work, just [read this guide](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal) 😜

**Comment by erduoya77** [comment]
I tried removing /etc/kubernetes/controller-manager.conf and waited for a long time, but the problem persists

![Image](https://github.com/user-attachments/assets/e65b056d-5c1f-418a-8013-47443e410451)

**Comment by AumniDhruv** [comment]
Reboot the system and try again.

> I tried removing /etc/kubernetes/controller-manager.conf and waited for a long time, but the problem persists
> 
> ![Image](https://github.com/user-attachments/assets/e65b056d-5c1f-418a-8013-47443e410451)

**Comment by CanGuan** [comment]
> Moving the manifest file out of /etc/kubernetes/manifests, waiting a bit to check process has stopped, and putting it back works.将清单文件从 /etc/kubernetes/manifests 中移出，等待一段时间以检查进程是否已停止，然后再将其放回，即可解决问题。

I mess up my cluster by deleting sc, pvc, rs... The answer from gpt doesn't help, but this work for me.

Here my error logs:

controller-manager:
E0312 01:21:54.199162       1 leaderelection.go:347] error retrieving resource lock kube-system/kube-controller-manager: Unauthorized

kube-scheduler:
W0311 12:25:09.962109 1 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Unauthorized E0311 12:25:09.962135 1 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Unauthorized W0311 12:25:12.463187 1 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Pod: Unauthorized E0311 12:25:12.463219 1 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Pod: failed to list *v1.Pod: Unauthorized

**Comment by shubhamdhole97** [comment]
> Moving the manifest file out of /etc/kubernetes/manifests, waiting a bit to check process has stopped, and putting it back works.

Actually this work
