### ISSUE TITLE
Clarify VPC Creation Step

### ISSUE THREAD

**Issue by liamfoneill** [kelseyhightower/kubernetes-the-hard-way#355]
After running: 

gcloud compute networks create kubernetes-the-hard-way --subnet-mode custom

the CLI returns this:

Did you mean [global] for network: [kubernetes-the-hard-way] (Y/n)?

for GCP newbies like me please clarify in the docs which to pick! 👍

**Comment by twajr** [comment]
@liamfoneill I'm pretty sure this happens when you do not have a default project set for gcloud as I experienced this today when building out a new jump server. Once I set a project:
```
gcloud config set project your-project-name
```
it no longer asked if this was global, and that makes sense.

**Comment by Lachlan-White** [comment]
@twajr thats correct, it is when the default hasn't been set for the project.

Just think @liamfoneill doesn't wants that line in the page.

@liamfoneill maybe you can create PR with the added line into the page so whoever does look at this can see exactly what you mean and merge or close the issue

**Comment by hareeshrao4839** [comment]
@liamfoneill 
gcloud compute networks create kubernetes-the-hard-way --subnet-mode custom --project <projectname> . 

or
gcloud config set project your-project-name && gcloud compute networks create kubernetes-the-hard-way --subnet-mode custom

**Comment by DorrinPk** [comment]
I think the confusion is from `gcloud init`. It prompts you to create a project and if you say no and don't set a default project you'll have this problem. 

Also for building the VPC and the rest the project needs to have billing set up which a GCE newbie might not know.
