### ISSUE TITLE
Migrate to another platform (Gitlab or another) to keep things moving

### ISSUE THREAD

**Issue by julian-alarcon** [kelseyhightower/kubernetes-the-hard-way#359]
Hi!

You should consider the migration to another platform after the MS announcement of the acquisition of GitHub.
http://www.itprotoday.com/open-source/why-open-source-software-moving-gitlab-after-microsoft-github-deal
https://www.bleepingcomputer.com/news/technology/gitlab-sees-huge-traffic-spike-after-news-of-microsoft-buying-github/
https://dev.to/maxart2501/what-i-think-is-bad-about-microsoft-acquiring-github-gme
https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/
https://blog.github.com/2018-06-04-github-microsoft/

**Comment by DanyC97** [comment]
will be good to close this issue

**Comment by kelseyhightower** [comment]
GitHub being bought by Microsoft is not an issue for me.
