### ISSUE TITLE
OpenStack support

### ISSUE THREAD

**Issue by e-minguez** [kelseyhightower/kubernetes-the-hard-way#361]
I've forked the repo to fit OpenStack based platforms here https://github.com/e-minguez/kubernetes-the-hard-way-osp
I'm not sure if you are interested in merging it here but just in case I can do it if you want.

Thanks.

**Comment by kelseyhightower** [comment]
Thanks for doing the work, but I would like to focus on a single platform. Please continue to keep your fork in sync.
