### ISSUE TITLE
Healthchecks and nginx problems

### ISSUE THREAD

**Issue by kdudala** [kelseyhightower/kubernetes-the-hard-way#364]
Hiya, I got most of the way through this awesome guide and got stuck at the point where I had to configure nginx to proxy requests to the healthcheck endpoints. Upon running `kubectl get componentstatuses --kubeconfig admin.kubeconfig`,

I keep getting the following error:

`The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?`

Should this be my internal_ip instead of localhost? Any guidance you can provide would be much appreciated.

**Comment by lukepereira** [comment]
I'm having the same issue. How did you resolve this?
