### ISSUE TITLE
Storage and Helm

### ISSUE THREAD

**Issue by kbaegis** [kelseyhightower/kubernetes-the-hard-way#366]
Awesome guide. I really wish it included some information on storage classes and/or helm. I can't get any charts deployed without persistentvolumeclaims.

**Comment by hareeshrao4839** [comment]
@kbaegis  
Cloud Service Providers provides Kubernetes as services(KAAS), if your using KAAS that is Fully Managed By CSP, so We need To  Understand How its Configure & Communicates of Components/Services b/w Master and client nodes.  

For Storage ; https://kubernetes.io/docs/concepts/storage/storage-classes/
For Helm : https://github.com/helm/helm    and https://helm.sh/

Thank You

**Comment by kelseyhightower** [comment]
As @hareeshrao4839 has pointed out, this guide is focused on the absolute core of Kubernetes and the foundation of how clusters are built. The two items you pointed out are explained in other guides.
