### ISSUE TITLE
endpoints access for worker nodes fail

### ISSUE THREAD

**Issue by KlavsKlavsen** [kelseyhightower/kubernetes-the-hard-way#369]
When I setup a worker node.. It can't fetch from any urls from apiserver. f.ex. https://lbip:6443/api/v1/endpoints?limit=500&resourceVersion=0"
It seems to be an rbac problem.
If I try to curl:
curl --cert /var/lib/kubernetes/worker01.pem --key /var/lib/kubernetes/worker01-key.pem .. I get:
  "message": "endpoints is forbidden: User \"system:node:worker01\" cannot list endpoints at the cluster scope",

I am using kubernetes 1.11.0

**Comment by KlavsKlavsen** [comment]
I get the same if I try to use the kubernetes client cert 
  "message": "endpoints is forbidden: User \"kubernetes\" cannot list endpoints at the cluster scope",
This works fine:
kubectl get componentstatuses --kubeconfig admin.kubeconfig

**Comment by KlavsKlavsen** [comment]
cert is created using cfssl in your guide and looks fine?
```
 Subject: C = DK, ST = Copenhagen, L = Copenhagen, O = system:nodes, OU = Infrastructure, CN = system:node:worker01
```

**Comment by KlavsKlavsen** [comment]
I fixed this, by altering this line in kube-api-server systemd:
  --runtime-config=api/all=true
to this:
  --runtime-config=api/all=true,admissionregistration.k8s.io/v1alpha1=true

**Comment by KlavsKlavsen** [comment]
That should probably be updated in your guide ?

**Comment by palbiez** [comment]
This don't solve the same problem at my side. But the following command solves it:

 `kubectl create clusterrolebinding cluster-system-anonymous --clusterrole=cluster-admin --user=system:anonymous`

**Comment by hareeshrao4839** [comment]
please check RBAC file or kubeconfig for node Authorization https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md
