### ISSUE TITLE
Minor typo in kubernetes-the-hard-way/docs/06-kubectl.md

### ISSUE THREAD

**Issue by C24IO** [kelseyhightower/kubernetes-the-hard-way#37]
In the section - Configure Kubectl

# /var/run/kubernetes/token.csv on the controller nodes
chAng3m3,admin,admin 

Should be 

# /var/lib/kubernetes/token.csv on the controller nodes
chAng3m3,admin,admin

**Comment by kelseyhightower** [comment]
This is fixed on master.
