### ISSUE TITLE
Create branch for tag 1.9.0

### ISSUE THREAD

**Issue by alrosot** [kelseyhightower/kubernetes-the-hard-way#371]
I was following the 1.9.0 documentation step-by-step and I found a small issue.

I have it fixed on my fork and I'd be very happy to submit a pull request. But for that I'd need the branch for 1.9.0 created, so I can target my pull request to it.

That's the small change I'm proposing:

https://github.com/alrosot/kubernetes-the-hard-way/commit/1120c845f1f2b6957a12252243a994e3b0da8079

NB: I haven't finished running all the commands on the guide yet.

**Comment by kelseyhightower** [comment]
It's hard enough to keep this guide up to date so for the time being I'm going to stick to one current release. Maybe I'll container maintaining branches in the future.
