### ISSUE TITLE
Deploy pods in Kubernets

### ISSUE THREAD

**Issue by meeca1218** [kelseyhightower/kubernetes-the-hard-way#373]
kubeadm init -pod-network-cidr=192.168.100.0/24
It works well and I can created two clients without error.
But have trouble to deploy pods.
kubectl create service nodeport nginx --tcp=80:80
kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        46m
nginx        NodePort    10.106.129.93   <none>        80:31458/TCP   1m
I thought the cluster-IP should have been using 192.168.100.x subnet.  Why it is uing 10.x.x.x network.
curl can not connect to my client port 31458.
lsof on client shows port 31458 is used by the right program.
kubectl describe pods
Name:               nginx-78f5d695bd-lm8hm
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               devminions2/.....
Start Time:         Sun, 29 Jul 2018 11:21:46 +0000
Labels:             app=nginx
                    pod-template-hash=3491825168
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/nginx-78f5d695bd
Containers:
  nginx:
    Container ID:   
    Image:          nginx
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fs8c2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-fs8c2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fs8c2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                        From                         Message
  ----     ------                  ----                       ----                         -------

Warning  FailedCreatePodSandBox  34m (x2798 over 1h)        kubelet, devminions2  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "95d937e792c40b31e2a492840a0e3f3d7050d41f15c3971682b3ab05981b0d2d" network for pod "nginx-78f5d695bd-lm8hm": NetworkPlugin cni failed to set up pod "nginx-78f5d695bd-lm8hm_default" network: open /run/flannel/subnet.env: no such file or directory
  Normal   SandboxChanged          <invalid> (x4770 over 1h)  kubelet, devminions2  Pod sandbox changed, it will be killed and re-created.

Anything wrong with my flannel setup ?  

Thanks so much in advance.

**Comment by hareeshrao4839** [comment]
kubeDNS issue

**Comment by meeca1218** [comment]
Hi,
Thx for the info.  How could you debug it and fix it ?
meeca1218

    On Wednesday, August 1, 2018, 4:17:42 AM PDT, Hareesh Chatarasupalli <notifications@github.com> wrote:  
 
 
kubeDNS issue

**Comment by meeca1218** [comment]
Sorry, I am new in Kubernetes field.
# kubectl get nodes
NAME                 STATUS    ROLES     AGE       VERSION
podaac-devk8s        Ready     master    3d        v1.11.1
podaac-devminions1   Ready     <none>    3d        v1.11.1
podaac-devminions2   Ready     <none>    3d        v1.11.1

/usr/bin/kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS              RESTARTS   AGE
default       nginx-78f5d695bd-lm8hm                  0/1       ContainerCreating   0          3d
kube-system   coredns-78fcdf6894-8h8j2                1/1       Running             0          3d
kube-system   coredns-78fcdf6894-qb75l                1/1       Running             0          3d
kube-system   etcd-podaac-devk8s                      1/1       Running             0          3d
kube-system   kube-apiserver-podaac-devk8s            1/1       Running             1          3d
kube-system   kube-controller-manager-podaac-devk8s   1/1       Running             1          3d
kube-system   kube-flannel-ds-amd64-28fnb             0/1       CrashLoopBackOff    976        3d
kube-system   kube-flannel-ds-amd64-4tc77             0/1       CrashLoopBackOff    978        3d
kube-system   kube-flannel-ds-amd64-ltb8z             1/1       Running             0          3d
kube-system   kube-proxy-b8n5j                        1/1       Running             0          3d
kube-system   kube-proxy-dw7h5                        1/1       Running             0          3d
kube-system   kube-proxy-l2dcc                        1/1       Running             0          3d
kube-system   kube-scheduler-podaac-devk8s            1/1       Running             1          3d

Seems like coredns is running.
kube-flannel... is in CrashLoopBackOff state, not sure what does that mean.

kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-0               Healthy   {"health": "true"}

But could not deploy application....
kubectl create -f /examples/nginx-deployment.yaml --record
deployment.apps/nginx-deployment created
kubectl rollout status deployment/nginx-deployment
Waiting for deployment "nginx-deployment" rollout to finish: 0 of 3 updated replicas are available...
error: deployment "nginx-deployment" exceeded its progress deadline

kubectl cluster-info dump
error: missing apiVersion or kind and cannot assign it; no kind is registered for the type core.NodeList

**Comment by meeca1218** [comment]
After I do the kubeadm reset and reinstall it.  Everything works fine now.  Thx everyone.
