### ISSUE TITLE
get masters 

### ISSUE THREAD

**Issue by mhamdisemah** [kelseyhightower/kubernetes-the-hard-way#382]
when i make  kubectl get no --all-namespaces it gives me only workers node no master showed ,how can i get masters node

**Comment by hareeshrao4839** [comment]
kubectl get no

**Comment by kelseyhightower** [comment]
The master components are not running under kubernetes so there are no "master nodes". The master nodes are controller-0, controller-1, and controller-2. There are no kubelets running on the controller nodes. That's why you only see the worker nodes.
