### ISSUE TITLE
dns timout

### ISSUE THREAD

**Issue by gio-salvador** [kelseyhightower/kubernetes-the-hard-way#383]
Would you have any recommendations for those getting the following response from the DNS queries:

$ kubectl exec -ti $POD_NAME -- nslookup kubernetes
;; connection timed out; no servers could be reached

command terminated with exit code 1

**Comment by devopsprosiva** [comment]
Replace kubedns with coredns

**Comment by omarrayward** [comment]
@gio-salvador 
Have you tried the solution proposed [here](https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/356).
This issue may be a duplicate

**Comment by jonashackt** [comment]
@omarrayward is right, it´s just the busybox image is crap - see this fix https://github.com/kelseyhightower/kubernetes-the-hard-way/pull/384

**Comment by kelseyhightower** [comment]
KubeDNS has been replaced with CoreDNS and all examples have been tested with the new configuration and verified to be working with the latest release of this guide.
