### ISSUE TITLE
Pods Ips diferent from PodCIDR

### ISSUE THREAD

**Issue by brunovlucena** [kelseyhightower/kubernetes-the-hard-way#386]
Hi, All

I followed the tutorial, with exception of the networking (kube-router) and TLS Bootstraping.

The bridge plugin seems not be setting up the bridge-interface's ip correctly. Any suggestions? 
![screenshot from 2018-09-14 15-24-50](https://user-images.githubusercontent.com/20466126/45552935-bcc98880-b832-11e8-8f8f-b14d0c0fc86f.png)

If I setup manually networking as I suppose it should be, then I receive an error from k8s
![screenshot from 2018-09-14 16-39-33](https://user-images.githubusercontent.com/20466126/45557044-061ed580-b83d-11e8-9ea2-f07b85a8c447.png)

![screenshot from 2018-09-14 16-50-07](https://user-images.githubusercontent.com/20466126/45557623-4c286900-b83e-11e8-96f9-416693b0c9c3.png)

after removing the kube-bridge's ip address
![screenshot from 2018-09-14 16-55-50](https://user-images.githubusercontent.com/20466126/45557970-1932a500-b83f-11e8-923c-6c41561a2a8b.png)

**Comment by kelseyhightower** [comment]
I'm not in position to support different networking backends. I provide a reference path which should work, but it'll be up to you for any other backend.
