### ISSUE TITLE
Upgrade to v1.11.3

### ISSUE THREAD

**Issue by abdennour** [kelseyhightower/kubernetes-the-hard-way#388]
Hello team,

Let's upgrade this great walkthrough to the latest stable version v1.11.3

**Comment by hareeshrao4839** [comment]
1. take a ETCD backup, stop k8s service's , download latest binaries, replace them, then start services , and check all components healthcheck, if its good, then we have to restore etcd

**Comment by kelseyhightower** [comment]
This guide is now updated for Kubernetes v1.12.0.

**Comment by abdennour** [comment]
Greeting @kelseyhightower
