### ISSUE TITLE
Scheduler token

### ISSUE THREAD

**Issue by jmastr** [kelseyhightower/kubernetes-the-hard-way#39]
Hi there,

this is the best Kubernetes deep dive tutorial I've ever seen. Thank you!

Can someone please explain, where the scheduler token is used, or if it is unnecessary.

**Comment by kelseyhightower** [comment]
Thanks for the question. I've added more details in the docs: https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-kubernetes-controller.md#authentication
