### ISSUE TITLE
kube-proxy  fails to start

### ISSUE THREAD

**Issue by pbaettig** [kelseyhightower/kubernetes-the-hard-way#391]
Trying to start `kube-proxy` fails
```
# systemctl start kube-proxy; journalctl -fu kube-proxy
-- Logs begin at Mon 2018-10-01 10:45:42 CEST. --
Oct 01 13:49:00 worker-0 systemd[1]: Started Kubernetes Kube Proxy.
Oct 01 13:49:00 worker-0 kube-proxy[7625]: F1001 13:49:00.317416    7625 server.go:360] invalid configuration: no configuration has been provided
Oct 01 13:49:00 worker-0 systemd[1]: kube-proxy.service: Main process exited, code=exited, status=255/n/a
Oct 01 13:49:00 worker-0 systemd[1]: kube-proxy.service: Unit entered failed state.
Oct 01 13:49:00 worker-0 systemd[1]: kube-proxy.service: Failed with result 'exit-code'.
Oct 01 13:49:05 worker-0 systemd[1]: kube-proxy.service: Service hold-off time over, scheduling restart.
Oct 01 13:49:05 worker-0 systemd[1]: Stopped Kubernetes Kube Proxy.
```

The systemd service file looks like this: 
```
[Unit]
Description=Kubernetes Kube Proxy
Documentation=https://github.com/kubernetes/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-proxy \
  --config=/var/lib/kube-proxy/kube-proxy-config.yaml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

The config file `/var/lib/kube-proxy/kube-proxy-config.yaml` looks like this:
```
kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clientConnection:
  kubeconfig: "/var/lib/kube-proxy/kubeconfig"
mode: "iptables"
clusterCIDR: "10.200.0.0/16"
```
`/var/lib/kube-proxy/kubeconfig` looks like this:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://192.168.99.100:6443
  name: kubernetes-the-hard-way
contexts:
- context:
    cluster: kubernetes-the-hard-way
    user: system:kube-proxy
  name: default
current-context: ""
kind: Config
preferences: {}
users:
- name: system:kube-proxy
  user:
    client-certificate-data: ...
    client-key-data: ...
```
`certificate-authority-data`,  `client-certificate-data` and `client-key-data` have been replaced with `...`

Any input is highly appreciated :slightly_smiling_face:

**Comment by hareeshrao4839** [comment]
Please Check  kube-proxy.service systemd unit file:  (your missing something service section) 

cat <<EOF | sudo tee /etc/systemd/system/kube-proxy.service
[Unit]
Description=Kubernetes Kube Proxy
Documentation=https://github.com/kubernetes/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-proxy \\
  --config=/var/lib/kube-proxy/kube-proxy-config.yaml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF


  sudo systemctl daemon-reload
  sudo systemctl enable containerd kubelet kube-proxy
  sudo systemctl start containerd kubelet kube-proxy

i tried its working fine

**Comment by Kydybets** [comment]
Hi @pbaettig we can take a look together.
But look like you missed to create the apiserver API to configure the proxy.

**Comment by pbaettig** [comment]
Hi @Kydybets, thanks for the input! I didn't have time in the last couple of days to go back and try to get it working but thanks to your comment and some other stuff I read I'm semi-confident that I'll be able to get it working :smile: .
