### ISSUE TITLE
PodSecurityPolicy support

### ISSUE THREAD

**Issue by wmuizelaar** [kelseyhightower/kubernetes-the-hard-way#392]
Hi,

Thanks for this superdope guide to understanding and building a k8s-cluster 'the hard way'. 

I would love to have added a section about PodSecurityPolicies, how to make sure you setup a cluster where the default kube-system deployments are done 'secure' with the correct policies - would that be appropriate in this guide?

Regards,
Wietse

**Comment by kelseyhightower** [comment]
I'm trying to keep things a simple as possible and focus on the core of Kubernetes and set the stage for people to explore additional concepts such as PodSecurityPolicies on their own.
