### ISSUE TITLE
Error starting kube-controller-manager & kube-scheduler

### ISSUE THREAD

**Issue by vaibhavsood** [kelseyhightower/kubernetes-the-hard-way#395]
From docs/08-bootstrapping-kubernetes-controllers.md

`sudo systemctl start kube-apiserver kube-controller-manager kube-scheduler` errors out with

`...
ct 12 05:26:31 ip-10-0-1-92 kube-scheduler[9290]: WARNING: the provided config file is an unsupported apiVersion ("componentconfig/v1alpha1"), which will be removed in future r
Oct 12 05:26:31 ip-10-0-1-92 kube-scheduler[9290]: WARNING: switch to command-line flags or update your config file apiVersion to "kubescheduler.config.k8s.io/v1alpha1"
Oct 12 05:26:31 ip-10-0-1-92 kube-scheduler[9290]: WARNING: apiVersions at alpha-level are not guaranteed to be supported in future releases
Oct 12 05:26:31 ip-10-0-1-92 kube-scheduler[9290]: **invalid configuration: no configuration has been provided**
Oct 12 05:26:31 ip-10-0-1-92 systemd[1]: kube-scheduler.service: Main process exited, code=exited, status=1/FAILURE
Oct 12 05:26:31 ip-10-0-1-92 systemd[1]: kube-scheduler.service: Failed with result 'exit-code'.
`

This gets resolved by running `kubectl config use-context default --kubeconfig=kube-controller-manager.kubeconfig` from docs/05-kubernetes-configuration-files.md inside the controller VM.

The documentation does not mention this, the above command as mentioned on page 05 as i interpret it is to be run from outside any controller VM, should this be moved to page 08 instead?

This seems to be a similar thread: https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/351

**Comment by kelseyhightower** [comment]
I've tested this on master.
