### ISSUE TITLE
Use bootstrap tokens to add nodes to cluster

### ISSUE THREAD

**Issue by surajssd** [kelseyhightower/kubernetes-the-hard-way#402]
Rather than using X 509 certs to authenticate nodes use bootstrap tokens to add nodes to the cluster.

Links:

- [TLS bootstrapping](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/)
- [Authenticating with Bootstrap Tokens](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/)
- [Add new node to k8s with bootstrap token](https://suraj.io/post/add-new-k8s-node-bootstrap-token/) (Shameless self plug)

**Comment by kelseyhightower** [comment]
Given that I need to create certificates already I prefer to use certificates for everything.
