### ISSUE TITLE
Network range should be 10.200.0.0/16 not 10.200.0.0/24 in example

### ISSUE THREAD

**Issue by spuder** [kelseyhightower/kubernetes-the-hard-way#403]
Step 3 says to create workers with network range of `10.200.0.0/16`, but the example shows `--metadata pod-cidr=10.200.${i}.0/24`

Is that a typo? or am I just not understanding correctly.

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-compute-resources.md

>The Kubernetes cluster CIDR range is defined by the Controller Manager's --cluster-cidr flag. In this tutorial the cluster CIDR range will be set to 10.200.0.0/16, which supports 254 subnets.

>Create three compute instances which will host the Kubernetes worker nodes:

>for i in 0 1 2; do
  gcloud compute instances create worker-${i} \
    --async \
    --boot-disk-size 200GB \
    --can-ip-forward \
    --image-family ubuntu-1804-lts \
    --image-project ubuntu-os-cloud \
    --machine-type n1-standard-1 \
    --metadata pod-cidr=10.200.${i}.0/24 \
    --private-network-ip 10.240.0.2${i} \
    --scopes compute-rw,storage-ro,service-management,service-control,logging-write,monitoring \
    --subnet kubernetes \
    --tags kubernetes-the-hard-way,worker
done

**Comment by chuckinator0** [comment]
The rest of the tutorial requires each worker node to have pod-cidr range 10.200.${i}.0/24. I don't think it's a typo because the cluster needs to have access to 10.200.0.0/16 in order to assign 10.200.${i}.0/24

**Comment by dineshba** [comment]
It is a `typo`. Should be /24
> The Kubernetes cluster CIDR range is defined by the Controller Manager's --cluster-cidr flag. In this tutorial the cluster CIDR range will be set to 10.200.0.0/24, which supports 254 subnets.

Reasons:
- Using /24 while creating worker
- /16 will give 65534 subnets, but as the above statement is 254 which is /24
- In most of the places, people choose Pod-CIDR range in /24 which give 254 pods per node.
