### ISSUE TITLE
CoreDNS yaml file missing

### ISSUE THREAD

**Issue by gdamberg** [kelseyhightower/kubernetes-the-hard-way#405]
In chapter 12 Deploying the DNS Cluster Add-on

CoreDNS is deployed with this command:

`kubectl apply -f https://storage.googleapis.com/kubernetes-the-hard-way/coredns.yaml`

But the coredns.yaml file is not available.

**Comment by SultanSGillani** [comment]
Having the same issue.

Receiving: 

> No resources found

When using the command: `kubectl get pods -l k8s-app=kube-dns -n kube-system`
Same thing happens with `kubectl get pods -l run=busybox`

**Comment by serain** [comment]
FWIW worked for me today (9th Nov 2018).

**Comment by jwsomis** [comment]
For me it finds, the file, but fails to start up.

`kubectl get pods -l k8s-app=kube-dns -n kube-system` returns
```
NAME                       READY   STATUS             RESTARTS   AGE
coredns-595db6f9cb-6qb66   0/1     CrashLoopBackOff   3          62s
coredns-595db6f9cb-drfqh   0/1     CrashLoopBackOff   3          62s
```

**Comment by fullstackinfo** [comment]
Try to get the config file locally using curl to make sure the url is correct. If you retrieve the file, then just run "kubectl apply -f <local-file>" I did this earlier today and it worked for me.

**Comment by maphysics** [comment]
ubuntu changed how it handles dns.

https://github.com/kubernetes/kubeadm/issues/1037

**Comment by gdamberg** [comment]
The download link is now working
