### ISSUE TITLE
Question: Revoke/Rotate Kubernetes Certificates

### ISSUE THREAD

**Issue by ashishkulk** [kelseyhightower/kubernetes-the-hard-way#411]
I was wondering if anyone can guide me to documentation/steps on how to rotate/revoke kubernetes certificates?

```
"ca.crt", "ca.key", "apiserver.crt", "apiserver.key", "client.crt", "client.key", "etcdclient.key", "etcdclient.crt", "etcdserver.crt", "etcdserver.key", "etcdpeer0.crt", "etcdpeer0.key", "kubectlClient.crt", "kubectlClient.key"
```

**Comment by kelseyhightower** [comment]
This is a bit out of scope for this guide. This issue has been open for a while so maybe the kubernetes slack is a better place to ask as question like this.
