### ISSUE TITLE
kubelet, worker-0  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox 

### ISSUE THREAD

**Issue by sandeepunix** [kelseyhightower/kubernetes-the-hard-way#413]
root@ubuntu-xenial:~# kubectl apply -f https://storage.googleapis.com/kubernetes-the-hard-way/coredns.yaml
serviceaccount/coredns created
clusterrole.rbac.authorization.k8s.io/system:coredns created
clusterrolebinding.rbac.authorization.k8s.io/system:coredns created
configmap/coredns created
deployment.extensions/coredns created
service/kube-dns created
root@ubuntu-xenial:~# kubectl get pods -l k8s-app=kube-dns -n kube-system
NAME                       READY   STATUS              RESTARTS   AGE
coredns-699f8ddd77-r2z5v   0/1     ContainerCreating   0          112s
coredns-699f8ddd77-r58wz   0/1     ContainerCreating   0          112s
root@ubuntu-xenial:~/files# kubectl describe pod coredns-699f8ddd77-r58wz   -n kube-system
Name:               coredns-699f8ddd77-r58wz
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               worker-0/10.240.0.20
Start Time:         Thu, 08 Nov 2018 10:42:47 +0000
Labels:             k8s-app=kube-dns
                    pod-template-hash=699f8ddd77
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/coredns-699f8ddd77
Containers:
  coredns:
    Container ID:  
    Image:         coredns/coredns:1.2.2
    Image ID:      
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-2lfx5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-2lfx5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-2lfx5
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                 From               Message
  ----     ------                  ----                ----               -------
  Normal   Scheduled               59m                 default-scheduler  Successfully assigned kube-system/coredns-699f8ddd77-r58wz to worker-0
  Warning  FailedCreatePodSandBox  59m                 kubelet, worker-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "91383d1dd59c98b0f65881989b6a969b3d006dda444cc34fe16184f292c8fe97": failed to find network info for sandbox "91383d1dd59c98b0f65881989b6a969b3d006dda444cc34fe16184f292c8fe97"
  Warning  FailedCreatePodSandBox  58m                 kubelet, worker-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "555a3d6eab5c3e76d1cc20fba1eb2f006dc89259475f2ba02135a91b03b7d8ba": failed to find network info for sandbox "555a3d6eab5c3e76d1cc20fba1eb2f006dc89259475f2ba02135a91b03b7d8ba"
  Warning  FailedCreatePodSandBox  58m                 kubelet, worker-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "16a21d2129821239044e3c42cf76dccb8a6e1502d26bf2fa27bed768f7050e83": failed to find network info for sandbox "16a21d2129821239044e3c42cf76dccb8a6e1502d26bf2fa27bed768f7050e83"
  Warning  FailedCreatePodSandBox  58m                 kubelet, worker-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "0291d022c46fc4f24690304ac7fe442e0d3f227ea9b579e346057372c12584ca": failed to find network info for sandbox "0291d022c46fc4f24690304ac7fe442e0d3f227ea9b579e346057372c12584ca"
  Warning  FailedCreatePodSandBox  58m                 kubelet, worker-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c1ff8444d7b86ef041d71f227939264e5128cdd151c451e0a4287fee4d9daa3f": failed to find network info for sandbox "c1ff8444d7b86ef041d71f227939264e5128cdd151c451e0a4287fee4d9daa3f"
  Warning  FailedCreatePodSandBox  57m                 kubelet, worker-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "0fb82d75cf4d3f3f887b083337f8f63084ac1a1a5b9098b7125316a315173e60": failed to find network info for sandbox "0fb82d75cf4d3f3f887b083337f8f63084ac1a1a5b9098b7125316a315173e60"
  Warning  FailedCreatePodSandBox  57m                 kubelet, worker-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8c703875e3e16447c9d517e6ee16f3cb2ae2a96bdbc45297523a4c0e522e18b5": failed to find network info for sandbox "8c703875e3e16447c9d517e6ee16f3cb2ae2a96bdbc45297523a4c0e522e18b5"
  Warning  FailedCreatePodSandBox  57m                 kubelet, worker-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "d0b6961d9fa4cf9032c4fd465517b70e69b72037d09407ec398d65f990eaae86": failed to find network info for sandbox "d0b6961d9fa4cf9032c4fd465517b70e69b72037d09407ec398d65f990eaae86"
  Warning  FailedCreatePodSandBox  57m                 kubelet, worker-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "158bbab998175dc547ab75e515bbf4ab618a26fdbabc140da51aa6c7e17b2ec0": failed to find network info for sandbox "158bbab998175dc547ab75e515bbf4ab618a26fdbabc140da51aa6c7e17b2ec0"
  Warning  FailedCreatePodSandBox  4m (x244 over 57m)  kubelet, worker-0  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "e01153d06de9d9fd082bed392f43d81404fe29333ed42105f6bfc7249f92577d": failed to find network info for sandbox "e01153d06de9d9fd082bed392f43d81404fe29333ed42105f6bfc7249f92577d"

**Comment by sandeepunix** [comment]
Hello Friends,

I am facing below issues when applying the DNS addons. I am new to kubernetes. Need help in fixing below issue.

**Comment by DimJacq** [comment]
Hello, do you find a solution because I have the same problem.
Thank you

**Comment by kelseyhightower** [comment]
This should be fixed on the updated version of the guide.
