### ISSUE TITLE
Metrics server deployment

### ISSUE THREAD

**Issue by pyaillet** [kelseyhightower/kubernetes-the-hard-way#414]
Would it be interesting to have additional doc regarding the deployment of metrics server and the necessary configuration of the aggregation layer ?
If so, I could propose something but I would like to know the best approach:
1. Modifying the main "path" and enabling aggregation layer in all cases
2. Add some optional documentation as side notes

**Comment by minasys** [comment]
I have a trouble configuring the metrics server after following Kubernetes the Hard Way, and I totally agree with @pyaillet

**Comment by kylix3511** [comment]
The goal of Kelsey Hightower’s  — kubernetes-the-hard-way exercise is deep and detailed understanding and learning of how and what makes Kubernetes, Kubernetes. ( It is not also production grade …. it is designed and developed for educational and learning purpose. ) 

Metrics, heapster, kubernetes-dashboard, prometheus, grafana and other Helm charts and metrics are on top of Kubernetes-the-hard-way is not recommended production grade.

**Comment by pyaillet** [comment]
I agree with you on the fact that it's not meant to build a real production cluster. 

However, I found interesting that the metrics server shows how to configure the agregation layer.

**Comment by kelseyhightower** [comment]
While I would love to add as many add-ons as possible but its just too hard for me to test and maintain.
