### ISSUE TITLE
Why do we need the --cluster-signing-key-file flag?

### ISSUE THREAD

**Issue by category** [kelseyhightower/kubernetes-the-hard-way#417]
Please can someone explain why we need to set the `--cluster-signing-key-file` flag in the [`kube-controller-manager.service`](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md) file, when we are not using TLS bootstrapping?

I'm not sure why the ` kube-controller-manager ` has the CA private key, `ca-key.pem`, if it is not going to receive CSRs from `kubelet`s.

**Comment by kelseyhightower** [comment]
I enabled this flags to enable support for generic certificate requests not just for kubelet bootstrapping.
