### ISSUE TITLE
Using CNI as overlay networking

### ISSUE THREAD

**Issue by linuxus** [kelseyhightower/kubernetes-the-hard-way#42]
Hi @kelseyhightower 
Although I can see the that Layer 3 routing is used in these labs to allow inter-PODs communication when they're running on different worker nodes.  I was hoping to see the leverage of CNI software as the underpinning networking technology. Probably would be interested to see how to use an overlay network with CNI interface with the built-in plugins.

Thanks a lot for this amazing work!

**Comment by kelseyhightower** [comment]
@linuxus I really want to stick to the most basic use of networking here. You make a good point, but my goal is to show a single path to success. I'm going to lean on other docs to document the details of CNI. This is a good suggestion, but I really want to keep things focused.

**Comment by veverjak** [comment]
@kelseyhightower it would be also maybe worth mentioning that on aws you can have max 50 Routes per route table (http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html#vpc-limits-route-tables). Not everyone lives in GCP dream land ;). 
Also thanks a lot for this wonderful repo.
