### ISSUE TITLE
DNS not working in pods and base nodes

### ISSUE THREAD

**Issue by aditya7002** [kelseyhightower/kubernetes-the-hard-way#421]
Hello ,

I have a Kubernetes cluster with one master node and two slave nodes . All master and slave nodes are in CentOS 7. I have deployed eureka on the cluster with only one instance or replica. I want to access the eureka service using its DNS name. When I query the DNS from the master server , I get the response as ----

[root@kubernetus ~]# nslookup eureka-server.default.svc.cluster.local 10.96.0.10
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   eureka-server.default.svc.cluster.local
Address: 10.106.146.187

But when I issue this command from the shell of a centos 7 base image pod , I get the response as ----

[root@centos7-97d59467-f7wbp /]# nslookup eureka-server.default.svc.cluster.local 10.96.0.10
;; connection timed out; no servers could be reached

Following is my centos pod resolv.conf ---->

[root@centos7-97d59467-f7wbp /]# cat /etc/resolv.conf
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

I have created this cluster using flannel. Similar DNS response as above can also be found when I execute it from any of the slave nodes (including the node on which the eureka pod is hosted) 

[root@kubernetus2 bridge]# nslookup eureka-server.default.svc.cluster.local 10.96.0.10
;; connection timed out; no servers could be reached

Can anybody help me in this issue ?

**Comment by bserdar** [comment]
I had the same problem when I went through this tutorial using Centos 7. I ended up using kube-router for networking:

https://github.com/bserdar/kubernetes-the-hard-way

**Comment by drweber** [comment]
Hi,

looks like I have similar issue

```
╰ POD_NAME=$(kubectl get pods -l run=busybox -o jsonpath="{.items[0].metadata.name}")

╰ kubectl exec -ti $POD_NAME -- nslookup kubernetes

Server:    10.32.0.10
Address 1: 10.32.0.10

nslookup: can't resolve 'kubernetes'
command terminated with exit code 1

**Comment by szogun1987** [comment]
Same problem in here. I have checked logs
`kubectl logs coredns-699f8ddd77-xwmdg -n kube-system`
and I got
`E1203 12:27:52.668648       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:348: Failed to list *v1.Service: Get https://10.32.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.32.0.1:443: i/o timeout`

**Comment by aditya7002** [comment]
Finally able to solve the issue myself. It is a firewall issue. Once I stopped the firewall, communication started to happen between nodes & pods properly . But I need to know which ports need to be opened in firewall so that communication can happen properly as in any production system, we can stop or disable the firewall.

**Comment by bserdar** [comment]
The networking backend is supposed to open/close ports in the firewall, and set up routes and bridges based on the networking requirements. With the way it is described in this tutorial, it didn't work with kube-proxy on Centos, that's why I replaced it with kube-router instead of troubleshooting it. You should not disable the firewall.

**Comment by AlphaSocket** [comment]
Hi
I got the same issue and with tcpdump I found out that the coredns pods couldn't resolve the node hostnames cause systemd-resolver wasn't aware of them
I'm using ubuntu instances and I also applied the `--resolv-conf=/run/systemd/resolve/resolv.conf` option in the kubelet unit file

So I've applied this workaround:
- Map all master nodes and worker nodes IPs in all nodes /etc/hosts 
- Restart kubelet services
- Delete the pods 

I wonder if there's a cleaner way to map all cluster nodes dynamically in the systemd resolver

**Comment by maxwell92** [comment]
I ran into the same problem here, ufw was stopped but didn't solve it.

**Comment by kelseyhightower** [comment]
I only have the bandwidth to test this on Ubuntu. Looks like you got some help for others.
