### ISSUE TITLE
SSL extensions in cfssl kubernetes profiles

### ISSUE THREAD

**Issue by schlitzered** [kelseyhightower/kubernetes-the-hard-way#424]
the kubernetes cfssl profile lists the following ssl extensions:

"signing", "key encipherment", "server auth", "client auth"

are all extensions needed by all certificates? if not, could someone please explain what ssl extension is needed by which certificate type?

Kind Regards.

**Comment by kelseyhightower** [comment]
I'm sure with a little work we can make additional profiles for each component but in an attempt to help simply things I've chosen to keep things as simple as possible. If some one is willing to do the work regarding separate profiles I'd be happy to review and consider updating the guide.
