### ISSUE TITLE
Kubernetes binaries or kubelet  with manifests ?

### ISSUE THREAD

**Issue by genti-t** [kelseyhightower/kubernetes-the-hard-way#43]
Great guide for everyone, well done.
This guide definitely explains in details how to put all the pieces together. Wish I had something like this a year ago :)

I know that this guide is just a walk through, but there are some details that might create confusion. I already have an automated deployment  based on CoreOS and wanted to know if this is "the right" way to automate in production.

- No need for flannel anymore ? CNI will take care of that, right ?
- Is it ok to use the Kubernetes binaries as in this documentation or is it better to use the CoreOS way (https://coreos.com/kubernetes/docs/latest/deploy-master.html), using kubelet with :

`--config=/etc/kubernetes/manifests` ?

**Comment by kelseyhightower** [comment]
This guide is to help you understand the moving parts. Looks like mission accomplished for you. Now you can test other setups and see how they work for you. I have opinions, but they hardly matter. Try the CoreOS way and see how it works out for you.

Only testing will answer your question.
