### ISSUE TITLE
cfssljson supports -version (now)

### ISSUE THREAD

**Issue by Code0x58** [kelseyhightower/kubernetes-the-hard-way#432]
https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/02-client-tools.md
> The cfssljson command line utility does not provide a way to print its version.

This is not true in at least 1.3.2 as you can do `cfssljson -version`. I'll have a look later and update this. I assume it should also be 1.2.0+.

**Comment by kelseyhightower** [comment]
Thanks for the suggestion but at this point I'm going to build and host my own cfssl binaries and link to upstream for people who wish to build their own. I'm now using 1.3.4 and show people how to print the version for both binaries.
