### ISSUE TITLE
Using `tar -C` on a symbolic link may have dire results

### ISSUE THREAD

**Issue by christianh814** [kelseyhightower/kubernetes-the-hard-way#434]
Just a note on [this section](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md#download-and-install-worker-binaries)

It states

```
  sudo mv runsc-50c283b9f56bb7200938d9e207355f05f79f0d17 runsc
  sudo mv runc.amd64 runc
  chmod +x kubectl kube-proxy kubelet runc runsc
  sudo mv kubectl kube-proxy kubelet runc runsc /usr/local/bin/
  sudo tar -xvf crictl-v1.12.0-linux-amd64.tar.gz -C /usr/local/bin/
  sudo tar -xvf cni-plugins-amd64-v0.6.0.tgz -C /opt/cni/bin/
  sudo tar -xvf containerd-1.2.0-rc.0.linux-amd64.tar.gz -C /
```

Specifically this command may be an issue ` sudo tar -xvf containerd-1.2.0-rc.0.linux-amd64.tar.gz -C /` for people (like myself) running Fedora 28 and newer.

On Fedora `/bin/` is a symbolic link

```
[root@jumpbox k8s-the-hard-way]# ll /bin
lrwxrwxrwx. 1 root root 7 Jul 12 21:48 /bin -> usr/bin
```

I had the issue of `sudo tar -xvf containerd-1.2.0-rc.0.linux-amd64.tar.gz -C /` replacing the symlink with a `/bin` dir contained in the tarball.

I know this was written for Ubuntu; but others following along could make use of a note.

**Comment by bserdar** [comment]
This is a problem in Centos 7 as well. I have a modified version of this in my fork:

https://github.com/bserdar/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md

**Comment by nefigtut** [comment]
the same is for Ubuntu 19.04 where `/bin` is also a symlink to `/usr/bin`. one can use it by supplying `--image-family ubuntu-1904 --image-project ubuntu-os-cloud` to the `gcloud compute instances create` command.

unpacking the tarball overwrites the `/bin` symlink. this renders a system unstable, for example `ssh` cannot connect to a system any more.

```
tar -xvf containerd-1.2.0-rc.0.linux-amd64.tar.gz
sudo mv bin/* /bin
rmdir bin
```
should work fine.

**Comment by rangsan** [comment]
I found this issue as well. It break the OS.
[devops@node05 ~]$ ls -l /bin/bash
ls: cannot access /bin/bash: No such file or directory

**Comment by kelseyhightower** [comment]
This should now be fixed on master. I'm now extracting the binaries in a local directory then moving them under bin.
