### ISSUE TITLE
kubectl not  getting nodes-No resource found

### ISSUE THREAD

**Issue by bganeshmail** [kelseyhightower/kubernetes-the-hard-way#439]
Dear All,

Documentation is excellent.I am not sure where to report my problem.So requesting here,

I am following all the steps but still i could not get node list.Could you please help me..

I am running this on Gcloud...

bganeshmail@cloudshell:~ (lively-lock-134023)$ kubectl get componentstatuses
NAME                 STATUS    MESSAGE             ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-1               Healthy   {"health":"true"}
etcd-2               Healthy   {"health":"true"}
etcd-0               Healthy   {"health":"true"}
bganeshmail@cloudshell:~ (lively-lock-134023)$ kubectl get nodes
No resources found.
bganeshmail@cloudshell:~ (lively-lock-134023)$

**Comment by cgroeschel** [comment]
Had the same issue so went back to workers to check service status of the kubelet service and that was stopped. 
When I tried to run the kubelet command shown in kubelet.service directly, it gave me a hint as to what's preventing the start:

F0210 15:26:09.311965   26136 server.go:262] failed to run Kubelet: Running with swap on is not supported, please                                                                                                                         disable swap! or set --fail-swap-on flag to false. 

So I added that flag to the kubelet.service file and it restarted fine:

cat /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes
After=containerd.service
Requires=containerd.service

[Service]
ExecStart=/usr/local/bin/kubelet \
  --config=/var/lib/kubelet/kubelet-config.yaml \
  --container-runtime=remote \
  --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock \
  --image-pull-progress-deadline=2m \
  --kubeconfig=/var/lib/kubelet/kubeconfig \
  --network-plugin=cni \
  --register-node=true \
  --fail-swap-on=false \
  --v=2
Restart=on-failure
RestartSec=5

[Install]

WantedBy=multi-user.target

sudo systemctl daemon-reload
sudo systemctl restart kubelet

Then the workers shows up healthy:

kubectl get nodes
NAME       STATUS   ROLES    AGE     VERSION
worker-1   Ready    <none>   11m     v1.12.0
worker-2   Ready    <none>   9m15s   v1.12.0

**Comment by pandatk** [comment]
I couldn't find the nodes either so i went digging. mi Issue is different to the one  @cgroeschel has : 
kubelet doesnt findthe node it is running on : 

> 
> Mar 06 13:49:42 worker-0 kubelet[2880]: E0306 13:49:42.595638    2880 kubelet.go:2236] node "worker-0" not found
> Mar 06 13:49:42 worker-0 kubelet[2880]: E0306 13:49:42.696597    2880 kubelet.go:2236] node "worker-0" not found
> Mar 06 13:49:42 worker-0 kubelet[2880]: E0306 13:49:42.797492    2880 kubelet.go:2236] node "worker-0" not found
> Mar 06 13:49:42 worker-0 kubelet[2880]: E0306 13:49:42.898501    2880 kubelet.go:2236] node "worker-0" not found
> Mar 06 13:49:42 worker-0 kubelet[2880]: E0306 13:49:42.999390    2880 kubelet.go:2236] node "worker-0" not found
> Mar 06 13:49:43 worker-0 kubelet[2880]: E0306 13:49:43.100241    2880 kubelet.go:2236] node "worker-0" not found
> Mar 06 13:49:43 worker-0 kubelet[2880]: E0306 13:49:43.201192    2880 kubelet.go:2236] node "worker-0" not found
> Mar 06 13:49:43 worker-0 kubelet[2880]: E0306 13:49:43.302035    2880 kubelet.go:2236] node "worker-0" not found

So i went looking in containerd and here's what i found : 

> Mar 06 13:49:30 worker-0 containerd[2825]: time="2019-03-06T13:49:30.432381696Z" level=info msg="No cni config template is specified, wait for other system components to drop the configuration

but it looks like the files for configuring cni are where they should be..

> ~# ls -l /etc/cni/net.d/
> -rw-r--r-- 1 root root  303 Mar  5 21:20 10-bridge.conf
> -rw-r--r-- 1 root root   54 Mar  5 21:20 99-loopback.conf

If someone could help me know where i went wrong..

**Comment by bganeshmail** [comment]
Thanks much cgroeschel...I will rerun the setup and check if the worker nodes are shown after disabling the swap..

**Comment by pandatk** [comment]
If someone is looking for this one day, my issue was that i changed the port apiserver is listening on and didnt change kube-proxy kubeconfig accordingly... duh

**Comment by wahlfeld** [comment]
> If someone is looking for this one day, my issue was that i changed the port apiserver is listening on and didnt change kube-proxy kubeconfig accordingly... duh

I don't recall changing any ports and I'm having the same issue as you with containerd. Looks like a couple errors though, not sure if they're related?

> $ journalctl -u containerd | less
> Mar 19 09:39:26 worker-0 containerd[14346]: time="2019-03-19T09:39:26.734
> 082089Z" level=warning msg="failed to load plugin io.containerd.snapshott
> er.v1.btrfs" error="path /var/lib/containerd/io.containerd.snapshotter.v1
> .btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"

> $ journalctl -u containerd | less
> Mar 19 10:02:02 worker-0 containerd[14346]: time="2019-03-19T10:02:02.131626075Z" level=info msg="No cni config template is specified, wait for other system components to drop the config."

> $ ls -l /etc/cni/net.d/
> -rw-r--r-- 1 root root 303 Mar 19 09:27 10-bridge.conf
> -rw-r--r-- 1 root root  54 Mar 19 09:28 99-loopback.conf

**Comment by wahlfeld** [comment]
So turns out I was looking in the wrong place. Logs from kube-proxy and kubelet indicated a networking issue connecting to the API server via the GCP load balancer. I had whitelisted my office IP only in the firewall rule which blocked all the nodes. Admittedly I wasn't expecting the nodes to go through the internet to get to the API server but whatever.

![image](https://user-images.githubusercontent.com/24707819/54605112-6ab32b00-4a40-11e9-8357-b6088ef56194.png)

**Comment by subratsahoo** [comment]
I had same failure while trying to run "kubectl get nodes" with error "No resources found"
checked the worker-node :"sudo systemctl status kubelet" found error "kubelet.service: Unit entered failed state." and "kubelet.service: Failed with result 'exit-code'"
 
Further debug found worker node swapp memory was active on /etc/fstab.
switched off the swapp memory "sudo swapoff -a" and restart the kubelet service  and found "/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)" 

Now kubectl get nodes returns the status of all active nodes.

**Comment by hareeshrao4839** [comment]
swapoff -a and restart all kubelets

**Comment by ntkawasaki** [comment]
I ran into this issue and am going to leave a comment here in case it can benefit someone else because it confused me for a very long time.

I was trying to go through this tutorial on but **AWS**, so I was semi following this tutorial but also following [this](https://github.com/slawekzachcial/kubernetes-the-hard-way-aws) AWS version I found online. The issue came down to the **node names** being different between these two pages. I wanted my nodes to be like Kelsey's, "worker-0", "worker-1", and "worker-2" instead of the ones I found in the AWS tutorial being "ip-10-240-0-0"... So I altered that part of the commands to create the SSL certs, nodes, etc. Then I kept getting these No Resources found errors when trying to start up my worker nodes. Had absolutely no clue why for about 3 days until I finally stumbled upon [this](https://github.com/kubernetes/kops/issues/5767) page where I read about how AWS kubernetes clusters will still name their nodes according to the private DNS entries for each host. So despite my naming everything "worker-0", etc, the names came out to actually be those "ip-10..." names. 

Note that the AWS tutorial actually accounts for this AWS specific thing and names their nodes appropriately, I just tried to still name mine like Kelsey's because I thought it was more intuitive than private IPs. If you completely follow the AWS one itll work.

Just dropping this in here to save people some time if you tried to do this in AWS!

**Comment by anton-opsguru** [comment]
I have run into a similar issue as it appears kubeconf on worker side was generated with empty API server address      server: https://:6443
Resolved by adding a load balancer IP address in /var/lib/kubelet/kubeconfig  server section.

**Comment by ArseniiPetrovich** [comment]
Yeah, well... Looks like the issue lies in fact that all of us created Kubernetes cluster in our own environment, not on GCP. But it's still hard to identify where might the root of the issue be.
Any other suggestions besides the described above?

**Comment by ArseniiPetrovich** [comment]
Okay, so the issue in my case was in the way I used the HAProxy to balance traffic between instances. I've decided to terminate SSL on backend and use the plain HTTP connection at the frontend. 
I'm not sure why, but despite the fact that I've updated `https` to `http` at Kubelet config it still were not able to work with HTTP connection. So I've configured HAProxy to work in HTTPS-Passthrough mode and pointed Kubelets to the HTTPS LB endpoint, and that solved my issue ;)

**Comment by fraserw** [comment]
> I have run into a similar issue as it appears kubeconf on worker side was generated with empty API server address server: https://:6443
> Resolved by adding a load balancer IP address in /var/lib/kubelet/kubeconfig server section.

@anton-opsguru 

What did fill in there exactly? I can't be certain of what my load-balancer's IP actually is.

**Comment by fraserw** [comment]
Solved it. The issue I was running into is that I put the commands that create the  woerk-?.kubeconfig and kube-proxy config files into separate bash scripts. Running those caused the empty IP entry for KUBERNETES_PUBLIC_ADDRESS. Putting the following command at the top of those two scripts solved the issue for me, correctly populating the IP in the .kubeconfig files.

The missing command:

KUBERNETES_PUBLIC_ADDRESS=$(gcloud compute addresses describe k8s-the-hard-way \
  --region $(gcloud config get-value compute/region) \
  --format 'value(address)')

**Comment by kelseyhightower** [comment]
It's impossible for me to test other platforms. Hopefully this work while GCP specific points you in the right direction for other platforms.

**Comment by mhobotpplnet** [comment]
> So turns out I was looking in the wrong place. Logs from kube-proxy and kubelet indicated a networking issue connecting to the API server via the GCP load balancer. I had whitelisted my office IP in the firewall rule which blocked all the nodes. Admittedly I wasn't expecting the nodes to go through the internet to get to the API server but whatever.
> 
> ![image](https://user-images.githubusercontent.com/24707819/54605112-6ab32b00-4a40-11e9-8357-b6088ef56194.png)

Yeah I did same thing, basically wanted to isolate the cluster to office ips etc, once I opened it up and restarted the worker node kublet and proxy etc everything was fine

**Comment by rcontisplk** [comment]
Thanks for finding this, I was tearing my hair out. While the instructions are technically correct (the best kind of correct!), they say "An external load balancer will be used to expose the Kubernetes API Servers to remote clients", which implies that only *remote* clients (eg, your workstation) may need access to the LB, which is not quite true. This load balancer is used for the kubelets and hence it's easy to break the tutorial if you don't allow the 'external' firewall up to 0.0.0.0/0.

**Comment by kennychen101** [comment]
Hi I have the same problem, and I have tried everything mentioned here and still no luck. I notice this error from "systemctl status kubelet": 

Process: 16412 ExecStart=/usr/local/bin/kubelet --config=/var/lib/kubelet/kubelet-config.yaml --container-runtime=remote --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock --image-pull-progress-deadline=2m --kubeconfig=/var/lib/kubelet/kubeconfig --network-plugin=cni --register-node=true --fail-swap-on=false --v=2 --hostname-override=k8snode1 --allow-privileged=true (code=exited, status=255)
 Main PID: 16412 (code=exited, status=255)

What does this "(code=exited, status=255)" mean? 

[user@k8smaster1 ~]$  sudo ETCDCTL_API=3 etcdctl member list   --endpoints=https://127.0.0.1:2379   --cacert=/etc/etcd/ca.pem   --cert=/etc/etcd/kubernetes.pem   --key=/etc/etcd/kubernetes-key.pem
30ca4decc2813048, started, k8smaster2.aero.org, https://10.208.4.99:2380, https://10.208.4.99:2379, false
7576ce438de8acb9, started, k8smaster1.aero.org, https://10.208.5.86:2380, https://10.208.5.86:2379, false
a291ca9b99a4509e, started, k8smaster3.aero.org, https://10.208.4.100:2380, https://10.208.4.100:2379, false

What does "false" mean here? 


================
[user@k8smaster1 ~]$ kubectl get componentstatuses
NAME                 STATUS    MESSAGE             ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-2               Healthy   {"health":"true"}
etcd-1               Healthy   {"health":"true"}
etcd-0               Healthy   {"health":"true"}

[user@k8smaster1 ~]$ kubectl get nodes
No resources found.

[user@k8smaster1 ~]$  kubectl get all --all-namespaces
NAMESPACE   NAME                         READY   STATUS    RESTARTS   AGE
default     pod/nginx-5b8c4fbff7-fgrml   0/1     Pending   0          3h39m
default     pod/nginx-5b8c4fbff7-xxbqp   0/1     Pending   0          3h39m


NAMESPACE   NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
default     service/kubernetes   ClusterIP   10.208.4.1   <none>        443/TCP   2d3h

NAMESPACE     NAME                                     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/kube-flannel-ds-amd64     0         0         0       0            0           <none>          3h51m
kube-system   daemonset.apps/kube-flannel-ds-arm       0         0         0       0            0           <none>          3h51m
kube-system   daemonset.apps/kube-flannel-ds-arm64     0         0         0       0            0           <none>          3h51m
kube-system   daemonset.apps/kube-flannel-ds-ppc64le   0         0         0       0            0           <none>          3h51m
kube-system   daemonset.apps/kube-flannel-ds-s390x     0         0         0       0            0           <none>          3h51m
kube-system   daemonset.apps/weave-net                 0         0         0       0            0           <none>          4h20m

NAMESPACE   NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
default     deployment.apps/nginx   0/2     2            0           3h39m

NAMESPACE   NAME                               DESIRED   CURRENT   READY   AGE
default     replicaset.apps/nginx-5b8c4fbff7   2         2         0       3h39m


Appreciate any help!

**Comment by ricardoptcosta** [comment]
> I have run into a similar issue as it appears kubeconf on worker side was generated with empty API server address server: https://:6443
> Resolved by adding a load balancer IP address in /var/lib/kubelet/kubeconfig server section.



> I have run into a similar issue as it appears kubeconf on worker side was generated with empty API server address server: https://:6443
> Resolved by adding a load balancer IP address in /var/lib/kubelet/kubeconfig server section.

What must have happened in my case was that when generating kubeconfig files for each worker node, I probably retrieved the Load Balancer IP address and saved it (KUBERNETES_PUBLIC_ADDRESS) in a different tab of the terminal from the tab where I then generated the config files themselves.  

To solve this, I added the load balancer IP address to the kubernetes-the-hard-way cluster. To be concrete, I changed, in each worker node, line 5 of /var/lib/kubelet/kubeconfig from  _server: https://:6443_ to  _server: https://<my-loadbalancer-ip-address>:6443_ 

Then, I restarted the kubelet service on each node and kubectl get nodes works :)
