### ISSUE TITLE
cannot see logs or exec into pod when using TLS bootstrapping

### ISSUE THREAD

**Issue by vikash32** [kelseyhightower/kubernetes-the-hard-way#441]
I have a cluster of below given configuration And i am using 1.12.0v release of k8s.
```
Master : 10.240.0.21/22 (i.e node1,node2 respectively)
worker: 10.240.0.23 (node3)
```
After configuring master, when i am bootstrapping worker nodes through TLS . The worker node csr get approved and issued by master  as shown below. 

```
(scraping) : vikash.singh $ kubectl describe csr node-csr-Cqwausxb1QPdcZ4ceu6KPH_tccD2YSa8xAzHuv1EACQ

Name:               node-csr-Cqwausxb1QPdcZ4ceu6KPH_tccD2YSa8xAzHuv1EACQ
Labels:             <none>
Annotations:        <none>
CreationTimestamp:  Sun, 17 Feb 2019 12:11:14 +0530
Requesting User:    kubelet-bootstrap
Status:             Approved,Issued
Subject:
         Common Name:    system:node:node3
         Serial Number:
         Organization:   system:nodes
Events:  <none>
```  
But after spinning a pod and trying to get `logs` or `exec` into it , It started throwing x509 certificate error on IP of node3(worker) node.
```
(scraping) : vikash.singh $ kubectl logs -f  nginx-sdsrvsz 
Error from server: Get https://10.240.0.23:10250/containerLogs/nginx-sdsrvsz: x509: cannot validate certificate for 10.240.0.23 because it doesn't contain any IP SANs
```

I can fix this issue by creating a certificate for this node manually but that totally override objective of TLS bootstrapping. Is there any other way around.

@kelseyhightower i have seen this [issue](https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/159). But it still happening.

**Comment by vikash32** [comment]
Got it Fixed, It is even wrote in [Docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#certificate-rotation)

Only need to add `--rotate-server-certificates` and `--rotate-certificates`  in kubelet configuration and approved manually.

**Comment by smrutimandal** [comment]
Feel like an idiot but took me 2 days to figure this out. Thanks a lot @vikash32
