### ISSUE TITLE
enabling the tmux session on gcloud cloud shell -does not work

### ISSUE THREAD

**Issue by bganeshmail** [kelseyhightower/kubernetes-the-hard-way#446]
Dear All:

I tried enabling the tmux session on gcloud cloud shell using the same steps outlined in the procedures but it does not open any new termianls ..

Enable synchronize-panes: ctrl+b then shift :. Then type set synchronize-panes on at the prompt.
When i presss ctrl+ b the shift:

I enter set synchronize-panes on 

but nothing happnes what went wrong..

**Comment by dineshba** [comment]
Did you create panes before/after `synchronize-panes` ?

Create pane: 
- `ctrl+b :split-window` or
- `ctrl plus b plus minus`
- `ctrl plus b plus underscore`
