### ISSUE TITLE
DNS addon as ReplicationController rather than Deployment

### ISSUE THREAD

**Issue by dlecorfec** [kelseyhightower/kubernetes-the-hard-way#45]
Great tutorial!

I see that Deployments seem to be way to go for deploying stuff, but it's not the case for the DNS addon.

Just wondering, is there any technical reason specific to this addon, or is just because it works fine as RC and it just isn't worth making a Deployment instead?

**Comment by kelseyhightower** [comment]
Thanks for the feedback. I've updated the dns add-on to use the new deployment that was released 9 days ago. The docs have been updated as well.
