### ISSUE TITLE
Could not resolve host: $KUBERNETES_PUBLIC_ADDRESS in lab8.

### ISSUE THREAD

**Issue by Rishats** [kelseyhightower/kubernetes-the-hard-way#452]
![lab8_error](https://user-images.githubusercontent.com/21194702/54533061-89b7ab80-49b3-11e9-82ad-eacd6704afc9.gif)

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md#verification-1

**Comment by Rishats** [comment]
This problem in my OS?(

**Comment by techgirlgeek** [comment]
What worked for me is taking out the escape characters:
curl --cacert ca.pem https://${KUBERNETES_PUBLIC_ADDRESS}:6443/version

**Comment by rkennedy** [comment]
Your movie shows backslashes before the braces in your `curl` command. The document you refer to does not show backslashes anywhere in the command. Looks to me like user error.

The sequence `$\{` doesn't expand to anything in your shell, but your shell will strip the backslashes prior to invoking Curl. Thus, Curl receives `https://${KUBERNETES_PUBLIC_ADDRESS}/version`, and it applies its [built-in globbing feature](https://ec.haxx.se/cmdline-globbing.html), which treats the braces as a list with one item in it, `KUBERNETES_PUBLIC_ADDRESS`. It fills that in and tries to resolve the _literal_ hostname `$KUBERNETES_PUBLIC_ADDRESS`, which fails, exactly as shown in your movie.

By moving the `$` inside the braces, you form the token `$KUBERNETES_PUBLIC_ADDRESS` on the command line, so your shell expands that. Curl sees `https://{35.204.72.0}/version`. Once again, it glob-expands the braces to a single-item list and ultimately visits the URL `https://35.204.72.0/version`.

**Comment by mkaschke** [comment]
I have the same issue and I don't know why it is not working. (I am on a Mac OS)

```
> curl --cacert ca.pem https://$\{KUBERNETES_PUBLIC_ADDRESS\}:6443/version
curl: (6) Could not resolve host: $KUBERNETES_PUBLIC_ADDRESS 
```

**Comment by devadaviddd** [comment]
You should remove "\" from the code copy before run it
![image](https://github.com/kelseyhightower/kubernetes-the-hard-way/assets/103375085/0e40a26d-0570-4c3b-8531-c07868901980)
