### ISSUE TITLE
Verification's after bootstrapping not working - noob, help!

### ISSUE THREAD

**Issue by monk78anthony** [kelseyhightower/kubernetes-the-hard-way#466]
Hi all,

I am new to building K8s, and I have followed the instructions on GCP cutting and pasting, so it's frustrating to hit a brick wall and not know why. I have a feeling it is going to be a simple thing I have yet to learn.
Firstly, when I run this on any controller - **kubectl get componentstatuses --kubeconfig admin.kubeconfig**
I get this - **The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?**

Secondly, when I try to verify the NGINX health check I do this as indicated in Section 8 - **curl -H "Host: kubernetes.default.svc.cluster.local" -i http://127.0.0.1/healthz**
I get this - **HTTP/1.1 502 Bad Gateway
Server: nginx/1.14.0 (Ubuntu)
Date: Fri, 14 Jun 2019 21:37:40 GMT
Content-Type: text/html
Content-Length: 182
Connection: keep-alive
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>**

Any help is gladly received. Ant

**Comment by jawaharshaik** [comment]
Hi, 

I think thats problem with simply running these commands by copy & paste. I had same problem earlier and resolved by simply update the format of 'encryption-config.yaml' file contents (see below)

kind: EncryptionConfig
apiVersion: v1
resources:
   - resources:
     - secrets
     providers:
       - aescbc:
          keys:
           - name: key1
             secret:<<secrets key>>
       - identity: {}

Thanks

**Comment by monk78anthony** [comment]
Thanks jawaharshaik I'll check that out and get back today. Ant

**Comment by monk78anthony** [comment]
Are you sure this YAML is right?

**Comment by jawaharshaik** [comment]
Hi, Sorry that YAML got formatted. Please refer to original one and adjust spacing for both secrets and providers( refer to this link : https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/) . Thanks

**Comment by monk78anthony** [comment]
Same errors. Am I missing another step maybe?

anta_gmail_com@controller-0:~$ kubectl get componentstatuses --kubeconfig                                                                                         admin.kubeconfig
The connection to the server 127.0.0.1:6443 was refused - did you specify the ri                                                                                        ght host or port?
anta_gmail_com@controller-0:~$ curl -H "Host: kubernetes.default.svc.clus                                                                                        ter.local" -i http://127.0.0.1/healthz
HTTP/1.1 502 Bad Gateway
Server: nginx/1.14.0 (Ubuntu)
Date: Mon, 17 Jun 2019 21:05:12 GMT
Content-Type: text/html
Content-Length: 182
Connection: keep-alive

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

**Comment by anwather** [comment]
Can you run ```sudo systemctl status kube-apiserver.service kube-controller-manager.service kube-scheduler.service etcd.service```

**Comment by anwather** [comment]
My apiserver.service was showing an error.
```
Jun 25 10:36:42 kube-master-1 kube-apiserver[48308]: error: enable-admission-plugins plugin "Initializers" is unknown
```
I will try removing Initializers from the apiserver service definition.

**Comment by anwather** [comment]
@monk78anthony this fixed my problem - in the service definition:- 
```
--enable-admission-plugins=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota \\
```

**Comment by scmdvr** [comment]
@anwather: thanks, this fixed same problem for me too!!

**Comment by kelseyhightower** [comment]
This is fixed on master.

**Comment by tjmoyes** [comment]
I was having this issue just now, and I found I had to echo out the encryption key and put it in the encryption-config file manually.
