### ISSUE TITLE
Quota Exceeded on #CPU using Google Cloud on Free Trial

### ISSUE THREAD

**Issue by caledhwa** [kelseyhightower/kubernetes-the-hard-way#47]
So, I currently have nothing but the $300 credit for Google Cloud over 60 days. That's all good. However, since https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/01-infrastructure.md requires creating 9 machines, I run into issues because I'm only allowed to create 8 machines. 

Therefore I get 

```
ERROR: (gcloud.compute.instances.create) Some requests did not succeed:
 - Quota 'CPUS' exceeded. Limit: 8.0
```

I'm just running through the tutorial so I thought I'd let you know. I figure that I can do the tutorial with only 2 workers anyhow -- probably not as compelling, but that's ok.

**Comment by kelseyhightower** [comment]
Thanks for reporting this. I'm going to look into scaling this down to 8 nodes or add a warning that the free account limits people to 8 nodes.

**Comment by kelseyhightower** [comment]
I've added a note that users can skip setting up worker2 if they are using the GCP free trial. Thanks.

**Comment by rodolfo-r** [comment]
I'm on GCP's free trial. GCP won't let me create more than 4 compute instances
`ERROR: (gcloud.compute.instances.create) HTTPError 403: Quota 'IN_USE_ADDRESSES' exceeded. Limit: 4.0 in region us-central1.`

Region us-west1 also has a limit of 4 instances.

Solution would be to use only two worker and two controller nodes for people on the GCP free trial.

**Comment by Nigar21** [comment]
I got 
Operation type [start] failed with message "Quota 'IN_USE_ADDRESSES' exceeded. Limit: 4.0 in region us-west4."
and I am unable to increase the quota, I am the owner and it is not within the free tiar
