### ISSUE TITLE
Doesn't it need endpoint-reconciler-type flag in kube-apiserver option?

### ISSUE THREAD

**Issue by jmyung** [kelseyhightower/kubernetes-the-hard-way#470]
Dear all,

Doesn't it need `endpoint-reconciler-type` flag in kube-apiserver option?

In terms of @kelseyhightower 's [kubernetes-api-server](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md#configure-the-kubernetes-api-server) guide, I think that endpoint-reconciler-type is needed.

In the [kube-apiserver of kubernetes.io docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/#kube-apiserver), when `--apiserver-count` is used, `--endpoint-reconciler-type=master-count` must be enabled.

I am wondering if it is omitted.

Thank you.

**Comment by kelseyhightower** [comment]
Right now I'm not using master-count and all the defaults should be working.
