### ISSUE TITLE
Translation into Japanese

### ISSUE THREAD

**Issue by sh-tatsuno** [kelseyhightower/kubernetes-the-hard-way#478]
Hi, I'm Sho from Japan.
Would you mind if I translate this repo into Japanese?

**Comment by jmyung** [comment]
I also would like to submit **Korean** localization work gladly with **Japanese** localization.

I also have Korean version of this awesome lab.
(Please check [this](https://github.com/jmyung/kubernetes-the-hard-way-modified) out)

Thank you for opening the gate, @sh-tatsuno

**Comment by kelseyhightower** [comment]
I've updated the copyright on the repo and have chosen to adopt a creative commons license which grants you permission to do the translation and as long as you agree to share to content under a similar license and not for commercial usage with prior approval.

**Comment by inductor** [comment]
@sh-tatsuno 
Hey, actually I have just finished the translation into Japanese.
https://github.com/inductor/kubernetes-the-hard-way
