### ISSUE TITLE
estimated cost duplicated VMs

### ISSUE THREAD

**Issue by ilyesAj** [kelseyhightower/kubernetes-the-hard-way#479]
when using the estimated cost link on 01-prerequisites.md there 12 machines estimated on gcp calculator :
![image](https://user-images.githubusercontent.com/34598860/64564899-dec8ee80-d352-11e9-9001-18cbdb2a80c5.png)
i think that's a mistake , we only needs 6 machines : 3 controllers and 3 workers

**Comment by kelseyhightower** [comment]
Fixed on master.
