### ISSUE TITLE
Unable to read /coredns.yaml (12-dns-addon.md)

### ISSUE THREAD

**Issue by svatwork** [kelseyhightower/kubernetes-the-hard-way#481]
Tried: 
`kubectl apply -f https://storage.googleapis.com/kubernetes-the-hard-way/coredns.yaml`
Got: 
`error: unable to read URL "https://storage.googleapis.com/kubernetes-the-hard-way/coredns.yaml", server reported 403 Forbidden, status code=403 `

**Comment by robinzoncruzo** [comment]
Just if you needed, i've had it saved luckily
https://gist.githubusercontent.com/robinzoncruzo/d21282ebb5ae0d09eec89402f1993eb1/raw/22fd4a98dfb654f148bf413e75b444665412dfec/coredns.yaml

**Comment by kelseyhightower** [comment]
Fixed.
