### ISSUE TITLE
kube-apiserver need to reach pods network

### ISSUE THREAD

**Issue by pmint93** [kelseyhightower/kubernetes-the-hard-way#486]
Since controller nodes has no kubelet running, which mean if I install the network plugin (eg: flannel), it won't be scheduled on controller nodes.
So probably controller nodes can not reach pods network, which lead to the issues with admission webhooks.
> Admission webhooks are HTTP callbacks that receive admission requests and do something with them

In example with [istio](https://istio.io), when we create the istio gateway, the kube-apiserver trigger a callback to istio-galley service in order to validate the resource, which will fail.

Another kubernetes docs describe that apiserver need to reach pods and services [here](https://kubernetes.io/docs/concepts/architecture/master-node-communication/#apiserver-to-nodes-pods-and-services)

What do you think about this issue ? Do you has any recommend to make this works ?
And generally, It would be good to know the current limitations of this architecture.

Thanks.

**Comment by strowk** [comment]
I had the same problem, when trying to install metrics server. I managed to solve it by installing kube-proxy on controller nodes. 

See issue for other details:
https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/505

**Comment by pmint93** [comment]
@strowk Are you sure installing kube-proxy on controller nodes solve the problem ?
kube-proxy only create the iptables rules that handle NAT from service IPs to pod IPs
The real problem here is the pod IPs is unreachable.

**Comment by strowk** [comment]
@pmint93 my mistake. The kube-proxy only works for services. Though I am sure it actually works - I've just tried it on my cluster and was able to reach pod through service ip, while pod ip still does not work. So for some applications it's enough - like for metrics server - apiserver only needs to reach any of metrics server pod, it does not matter which specifically, so it does that though the service ip. I guess that service mesh could require actually addressing pod directly and might not work with this solution.

**Comment by stefan-kiss** [comment]
this implementation does not make use of an overlay network. routes to access pods are controlled manually / directly in this step:

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/11-pod-network-routes.md

most installations install kubelet on master nodes
actually most installations run all other services than kubelet as static pods on the master nodes [](https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/)

If you go that way you will find out that to keep non-essential pods from running on the designated master nodes you also have to use a combination of labels and taints. And that overlay network daemon-sets usually have tolerations for those taints.

i think you could start reading about this here: [](https://github.com/kubernetes/kubernetes/issues/28687
)

**Comment by pmint93** [comment]
Yah I see.
I'm trying to install kubernetes the hard way out of GCP which is not exactly match with this guide.
So, probably this issue not really related.

**A note** for anyone want to do the same. I've found a possible workaround with kube-router.

Kube-router offer a feature allow you to BGP-peering your kube-router (on each worker nodes) with external peer. So, I can run quagga (for example) in controller node to make controller join the pod network.
