### ISSUE TITLE
Error creating instances with ubuntu image

### ISSUE THREAD

**Issue by jpmcb** [kelseyhightower/kubernetes-the-hard-way#514]
When executing the following command from the provisioning lab:

```
for i in 0 1 2; do
  gcloud compute instances create controller-${i} \
    --async \
    --boot-disk-size 200GB \
    --can-ip-forward \
    --image-family ubuntu-1804-lts \
    --image-project ubuntu-os-cloud \
    --machine-type n1-standard-1 \
    --private-network-ip 10.240.0.1${i} \
    --scopes compute-rw,storage-ro,service-management,service-control,logging-write,monitoring \
    --subnet kubernetes \
    --tags kubernetes-the-hard-way,controller
done
```
I get the following error:
```
ERROR: (gcloud.compute.instances.create) HTTPError 404: The resource 'projects/jpmcb-k8s-the-hardway/global/images/family/ubuntu-1804-lts' was not found
```

I was able to correct this by including the image family flag as it seemed to be attempting to pull images from my project's own resources:

```
--image-project ubuntu-os-cloud
```

Should the above command be updated to include the image family flag?

**Comment by jpmcb** [comment]
My mistake, I believe I entered the command wrong! 🙈

**Comment by techoutliers** [comment]
I am getting the same error. 
```
ERROR: (gcloud.compute.instances.create) HTTPError 404: The resource 'projects/ubuntu-os-cloud/zones/asia-northeast3-a/imageFamilyViews/ubuntu-2004-lts' was not found```

**Comment by LinaC404** [comment]
Mark, I encountered same issue 
`ERROR: (gcloud.compute.instances.create) HTTPError 404: The resource 'projects/ubuntu-os-cloud/zones/us-west1-c/imageFamilyViews/ubuntu-2004-lts' was not found`

**Comment by gcpbeginner** [comment]
I think I encountered the same issue.
The output looks like the following:
`ERROR: (gcloud.compute.instances.create) HTTPError 404: The resource 'projects/ubuntu-os-cloud/zones/us-west1-c/imageFamilyViews/ubuntu-2004-lts' was not found`

**Comment by outranker** [comment]
What do you think the problem is? 
Were you able to solve this issue?
I wonder if the same error occurs with images other than Ubuntu
