### ISSUE TITLE
Chapter 9 - POD-CIDR is 404

### ISSUE THREAD

**Issue by kbreit** [kelseyhightower/kubernetes-the-hard-way#529]
`POD_CIDR=$(curl -s -H "Metadata-Flavor: Google" \
  http://metadata.google.internal/computeMetadata/v1/instance/attributes/pod-cidr)` is giving me a 404 error saying it's not found. This happens as a copy paste from the documentation and is being executed from worker nodes, not controllers.

**Comment by kbreit** [comment]
I never set this when creating the instances.

**Comment by SpaceAceMonkey** [comment]
I am sharing my experience, in case anyone else made the same goofy mistake I did.

When creating the nodes, I did not copy/paste. I typed everything out to help myself learn, resulting in this.

`gcloud compute instances describe worker-0 --format='value(metadata.items)'`.

`{'key': 'pod-cider', 'value': '10.200.0.0/24'}`

As you can see, that is the beverage, and not the routing standard.
