### ISSUE TITLE
Update kubernetes api server certificate

### ISSUE THREAD

**Issue by vofish** [kelseyhightower/kubernetes-the-hard-way#531]
Hello there,

I've created a Kubernetes cluster according to 'Kubernetes-the-hard-way', but I intentionally generated certificates with 72h expiration period. Just to have kinda troubleshooting training.
ca-config.json
{
  "signing": 
{
    "default": {
      "expiry": "72h"
    },
    "profiles": {
      "kubernetes": {
        "usages": ["signing", "key encipherment", "server auth", "client auth"],
        **"expiry": "72h"**
      }
    }
  }
}

Is there any easy way to fix this issue?
Thanks in advance.

Kind regards,
Vova

**Comment by talebi1** [comment]
you might find this interesting https://www.youtube.com/watch?v=Cl-EWv3LmJA

**Comment by vofish** [comment]
I asked, so I'm answering.
First of all, you need to update the expiration period in **ca-config.json**, then:

1. re-generate all certs (chapter 04-certificate-authority);
2. re-generate config files (chapter 05-kubernetes-configuration-files);
3. copy and move certs, configs to its places (chapters 07-bootstrapping-etcd, 08-bootstrapping-kubernetes-controllers, 09-bootstrapping-kubernetes-workers), restart **etcd, kube-apiserver, kube-controller-manager, kube-scheduler, containerd, kubelet, kube-proxy**.

Now you should have a working k8s cluster.
