### ISSUE TITLE
CA and Generating TLS Certificates and GoDaddy wildcard certificate

### ISSUE THREAD

**Issue by itkroplis** [kelseyhightower/kubernetes-the-hard-way#538]
Hi!  I read Provisioning a CA and Generating TLS Certificates. 
I have GoDaddy wildcard certificate *.myfirm.com and I want use it for Kubernetes PKI. Is it possible?
How to need executing this?:
{

cat > ca-config.json <<EOF
{
  "signing": {
    "default": {
      "expiry": "8760h"
    },
    "profiles": {
      "kubernetes": {
        "usages": ["signing", "key encipherment", "server auth", "client auth"],
        "expiry": "8760h"
      }
    }
  }
}
EOF

cat > ca-csr.json <<EOF
{
  "CN": "Kubernetes",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "Kubernetes",
      "OU": "CA",
      "ST": "Oregon"
    }
  ]
}
EOF

cfssl gencert -initca ca-csr.json | cfssljson -bare ca

}

This need to save as xxx.yaml and execute with kubectl?!
Please give me example!

**Comment by kelseyhightower** [comment]
It maybe possible, but I don't have the bandwidth to test it.
