### ISSUE TITLE
How long is this tutorial expected to take?

### ISSUE THREAD

**Issue by rafaeleyng** [kelseyhightower/kubernetes-the-hard-way#541]
Hi, kubernetes begginer here 😃

This resource seems amazing, I'm just not sure whether it should be the next material I should study (I don't need any kind of "if you are not sure, this is not for you" kind of answers here).

It will help to have _a ballpark estimate_ on the README of how long this tutorial is expected to take. For me, is really hard to estimate whether it would take something like 8 hours, or something like a full month with 8 hours per day. Knowing that in advance helps to plan the studies.

Thanks for the awesome resource!

**Comment by patpicos** [comment]
Lab 1-5 took me 1 hour so far. I'll keep updating to give you a sense. (I am running on Azure)

**Comment by patpicos** [comment]
7-8 20mins.

**Comment by rafaeleyng** [comment]
Oh, nice. So it seems to be something to be done in a single day, not something like spending a whole month working on 😄.

Nonetheless, I think would be nice to contain an estimate on the README, for newcomers.

**Comment by patpicos** [comment]
3 hours seems like a reasonable amount of time to perform this tutorial. Its been pretty seemless so far. only had to troubleshoot one thing.

I also learned `tmux` in the process (had not used it before)

**Comment by patpicos** [comment]
https://github.com/kelseyhightower/kubernetes-the-hard-way/pull/543

**Comment by brommell** [comment]
> Oh, nice. So it seems to be something to be done in a single day, not something like spending a whole month working on 😄.

it really depends, for me - without kubernetes and cloud background, those labs took around two weeks, a couple hours almost every day.

**Comment by brommell** [comment]
> 3 hours seems like a reasonable amount of time to perform this tutorial. Its been pretty seemless so far. only had to troubleshoot one thing.

@patpicos you forgot to mention your technical background, it depends a lot.

**Comment by patpicos** [comment]
True. Been doing cloud for almost 3 years and k8s for 7 months if that helps put in perspective

On Mar 3, 2020 5:04 AM, brommell <notifications@github.com> wrote:

3 hours seems like a reasonable amount of time to perform this tutorial. Its been pretty seemless so far. only had to troubleshoot one thing.

@patpicos<https://github.com/patpicos> you forgot to mention your technical background, it depends a lot.

**Comment by jmyung** [comment]
When I want to check the meaning of each step, it took more time for me.
 (e.g. following `Bootstrapping the Kubernetes Control Plane` step needs to figure out [Kubernetes Components](https://kubernetes.io/docs/concepts/overview/components/))
