### ISSUE TITLE
Etcd –client-cert-auth

### ISSUE THREAD

**Issue by elcct** [kelseyhightower/kubernetes-the-hard-way#56]
Hello,

When I use this flag in etcd, `kubectl get cs` will say:

```
etcd-2               Unhealthy   Get https://gc03.gloriouscloud.com:2379/health: remote error: bad certificate 
```

But otherwise the cluster seems to be working fine.

Is this a reason in your tutorial you are not using client authentication in etcd?

I am trying to understand what I am doing wrong or if it is something else.

I was writing similar set of tutorial regarding installation of Kubernetes on bare metal.

https://medium.com/@elcct/kubernetes-on-bare-metal-part-5-kubernetes-master-b6a0388fa993

and I am stuck on this problem :)

Thanks!

**Comment by kelseyhightower** [comment]
@elcct The cert you generated most likely does not include the "gc03.gloriouscloud.com" hostname. If you notice the list for the guide here all the hostnames where included in the certificate.

**Comment by elcct** [comment]
@kelseyhightower 

This is configuration of the key I used:

```
{ 
 "CN": "client", 
 "hosts": [
   "127.0.0.1",
   "gc01",
   "gc02",
   "gc03",
   "gc04",
   "gc05",
   "gc01.gloriouscloud.com",
   "gc02.gloriouscloud.com",
   "gc03.gloriouscloud.com",
   "gc04.gloriouscloud.com",
   "gc05.gloriouscloud.com",
   "10.2.222.77",
   "10.2.217.141",
   "10.2.218.205",
   "10.2.221.141",
   "10.2.224.77",
   "163.172.135.90",
   "212.47.252.91",
   "163.172.139.217",
   "212.47.227.244",
   "163.172.154.174"
 ], 
 "key": { 
   "algo": "rsa", 
   "size": 2048
 }
}
```

I was able to communicate with `etcd` using that key and also `etcd` was listing kubernetes entries, just cluster was reported not healthy.

Thanks

**Comment by kelseyhightower** [comment]
Your issue maybe related to communication between the etcd works, but I don't have the bandwidth to troubleshoot that. I finding it hard enough to support AWS and GCE.
