### ISSUE TITLE
small fix bootstrapping kubernetes controllers

### ISSUE THREAD

**Issue by kfirufk** [kelseyhightower/kubernetes-the-hard-way#578]
With kubernetes 1.18.3 I needed to change
--runtime-config=api/all to --runtime-config=api/all=true

**Comment by rantomanik** [comment]
https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/578#issue-633593980

**Comment by bryfry** [comment]
This issue is fixed in PR https://github.com/kelseyhightower/kubernetes-the-hard-way/pull/535 not yet merged
