### ISSUE TITLE
Why was the Untrusted Workloads removed?

### ISSUE THREAD

**Issue by alexclarkofficial** [kelseyhightower/kubernetes-the-hard-way#581]
This is more of a naive question than an issue.

I am following https://github.com/prabhatsharma/kubernetes-the-hard-way-aws and periodically cross referencing this tutorial when I have problems. I noticed `Untrusted Workloads` was removed from the Smoke Test lab when the tutorial was updated for Kubernetes 1.15.

I also noticed that the AWS tutorial has a `Check images/pods/containers on worker nodes using crictl` section in the Smoke Test lab, while this tutorial does not.

Can someone shed some light on why these sections are not present/were removed?

**Comment by moehajj** [comment]
According to this pull request #400, it seems to be mainly for the convenience of maintaining this tutorial.

**Comment by alexclarkofficial** [comment]
That's a great find, thanks @moehajj!

**Comment by kelseyhightower** [comment]
@moehajj is right. I need to keep this thing focused.
