### ISSUE TITLE
The cleanup script instructions do not remove the load balancer or its associated resources.

### ISSUE THREAD

**Issue by DamaniN** [kelseyhightower/kubernetes-the-hard-way#605]
The current clean up script doesn't remove the load balancer or it's associated resources. This can be done by running the following:

gcloud -q compute forwarding-rules  delete \
  kubernetes-forwarding-rule \
  --region $(gcloud config get-value compute/region)

gcloud -q compute target-pools  delete \
  kubernetes-target-pool \
  --region $(gcloud config get-value compute/region

gcloud -q compute http-health-checks delete  \
  kubernetes

**Comment by gaffneyd4** [comment]
I don't think this is true anymore: https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/14-cleanup.md#networking

Looks like this issue & PR can be closed.

**Comment by DamaniN** [comment]
Strange, I must have been working from an older copy. The PR can be removed.
