### ISSUE TITLE
Could you add a lab to support the type LoadBalancer for exposing services to Internet?

### ISSUE THREAD

**Issue by mydharma** [kelseyhightower/kubernetes-the-hard-way#62]
By following the instructions in "kubernetes-the-hard-way", I was able to setup the cluster and run deployments. But, I couldn't get the applications exposed in AWS externally. I think it would be helpful to add a lab for that.

Thank you.

**Comment by kelseyhightower** [comment]
NodePorts work, but you'll have to hit services via one of the nodes IP address. With a little research you should be able to enable cloud provider integration and modify this setup to enable it.
