### ISSUE TITLE
External dns lookup fails inside pod

### ISSUE THREAD

**Issue by itzkumaran** [kelseyhightower/kubernetes-the-hard-way#621]
Trying to do some exercise on this link => https://github.com/dgkanatsios/CKAD-exercises/blob/master/b.multi_container_pods.md and my external dns resolution fails from the pod.
Version:

`sshanmugagani@MSI:~/cka/skk8/practise-1$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
`

Pod fails to resolve google.com:
`
sshanmugagani@MSI:~/cka/skk8/practise-1$ kubectl exec -ti dnsutils -- nslookup google
Server:         10.32.0.10
Address:        10.32.0.10#53

** server can't find google.us-west1-c.c.test.internal: SERVFAIL

command terminated with exit code 1
`

Pod's /etc/resolv.conf:
`
sshanmugagani@MSI:~/cka/skk8/practise-1$ kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
pod/dnsutils created
sshanmugagani@MSI:~/cka/skk8/practise-1$ k exec -it dnsutils -- cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local us-west1-c.c.test.internal c.test.internal google.internal
nameserver 10.32.0.10
options ndots:5
`
Getting worker node where pod runs:
`
sshanmugagani@MSI:~/cka/skk8/practise-1$ kgp -o wide
NAME        READY   STATUS       RESTARTS   AGE   IP            NODE       NOMINATED NODE   READINESS GATES
dnsutils    1/1     Running      0          60s   10.200.0.65   worker-0   <none>           <none>
multi       0/2     Completed    0          12h   10.200.0.53   worker-0   <none>           <none>
`
Worker node resolves:

`
sshanmugagani@worker-0:~$ nslookup google.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   google.com
Address: 74.125.20.101
Name:   google.com
Address: 74.125.20.100
Name:   google.com
Address: 74.125.20.139
Name:   google.com
Address: 74.125.20.138
Name:   google.com
Address: 74.125.20.113
Name:   google.com
Address: 74.125.20.102
Name:   google.com
Address: 2607:f8b0:400e:c09::65
Name:   google.com
Address: 2607:f8b0:400e:c09::8a
Name:   google.com
Address: 2607:f8b0:400e:c09::8b
Name:   google.com
Address: 2607:f8b0:400e:c09::71
`
Coredns:

`
sshanmugagani@MSI:~/cka/skk8/practise-1$ kgp $ks
NAME                       READY   STATUS    RESTARTS   AGE
coredns-5677dc4cdb-cfl2j   1/1     Running   1          11h
coredns-5677dc4cdb-xqm44   1/1     Running   1          11h
`
Coredns logs
`
sshanmugagani@MSI:~/cka/skk8/practise-1$ kubectl logs coredns-5677dc4cdb-cfl2j $ks
.:53
[INFO] plugin/reload: Running configuration MD5 = fbb756dad13bce75afc40db627b38529
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d
[ERROR] plugin/errors: 2 2953017454530458158.338294255644342916. HINFO: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 google.com.us-west1-c.c.test.internal. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 google.com. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 google.com. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 kube-dns. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.us-west1-c.c.test.internal. AAAA: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.c.test.internal. AAAA: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com. AAAA: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.c.test.internal. AAAA: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.goo. AAAA: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.us-west1-c.c.test.internal. AAAA: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.c.test.internal. AAAA: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.goo. AAAA: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.goo. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.us-west1-c.c.test.internal. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.c.test.internal. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.goo. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 neverssl.com.us-west1-c.c.test.internal. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 google.com. A: plugin/loop: no next plugin found
[ERROR] plugin/errors: 2 google. A: plugin/loop: no next plugin found
`

**Comment by sevanmakaraci** [comment]
Hello,

To resolve external dns, you need to add the following line to coredns configmap;
forward . /etc/resolv.conf

Sample configmap;
`apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }`

**Comment by itzkumaran** [comment]
Thank you, @sevanmakaraci . I will run some tests over the weekend and get back.

**Comment by itzkumaran** [comment]
Hello @sevanmakaraci 

Thanks for the suggestion, now its giving a different error. 
I could now resolve the endpoint using `dig` but not through nslookup. 

Please refer the below outputs and let me know if you have any thoughts to fix this.

```
sshanmugagani@MSI:~/cka/skk8/k8s-the-hard-way-script$ k exec -it dnsutils -- /bin/sh
/ # wget -O /work-dir/index.html http://neverssl.com/online
wget: bad address 'neverssl.com'
/ # wget -O /work-dir/index.html http://neverssl.com/online
wget: bad address 'neverssl.com'
/ # nslookup neverssl.com
;; reply from unexpected source: 10.200.1.8#53, expected 10.32.0.10#53
;; reply from unexpected source: 10.200.1.8#53, expected 10.32.0.10#53
/ # cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local us-west1-c.c.sk-kube-hard.internal c.sk-kube-hard.internal google.internal
nameserver 10.32.0.10
options ndots:5
```

```
sshanmugagani@MSI:~/cka/skk8/k8s-the-hard-way-script$ k exec -it dnsutils -- /bin/sh
/ # dig neverssl.com

; <<>> DiG 9.11.6-P1 <<>> neverssl.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36908
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;neverssl.com.                  IN      A

;; ANSWER SECTION:
neverssl.com.           30      IN      A       99.86.33.100
neverssl.com.           30      IN      A       99.86.33.225
neverssl.com.           30      IN      A       99.86.33.21
neverssl.com.           30      IN      A       99.86.33.62

;; Query time: 155 msec
;; SERVER: 10.32.0.10#53(10.32.0.10)
;; WHEN: Fri Nov 27 02:05:44 UTC 2020
;; MSG SIZE  rcvd: 153
```
```
sshanmugagani@MSI:~/cka/skk8/k8s-the-hard-way-script$ k exec -it dnsutils -- /bin/sh
/ # nslookup kubernetes
Server:         10.32.0.10
Address:        10.32.0.10#53

Name:   kubernetes.default.svc.cluster.local
Address: 10.32.0.1

```

```
sshanmugagani@MSI:~/cka/skk8/k8s-the-hard-way-script$ k get svc $ks
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
kube-dns   ClusterIP   10.32.0.10   <none>        53/UDP,53/TCP,9153/TCP   8h
```


```
sshanmugagani@MSI:~/cka/skk8/k8s-the-hard-way-script$ k get endpoints $ks
NAME                      ENDPOINTS                                                 AGE
kube-controller-manager   <none>                                                    8h
kube-dns                  10.200.0.7:53,10.200.1.8:53,10.200.0.7:9153 + 3 more...   8h
kube-scheduler            <none>                                                    8h
```


```
sshanmugagani@MSI:~/cka/skk8/k8s-the-hard-way-script$ k get endpoints
NAME         ENDPOINTS                                            AGE
kubernetes   10.240.0.10:6443,10.240.0.11:6443,10.240.0.12:6443   8h
nginx        10.200.1.6:80                                        7h59m
```

**Comment by itzkumaran** [comment]
Got this issue fixed by 
==> Loaded kernel module
`   modprobe br_netfilter`
===> Add flag for kube-proxy start up file
`--masquerade-all`
