### ISSUE TITLE
kube-proxy just uses one api-server

### ISSUE THREAD

**Issue by sgoodliff** [kelseyhightower/kubernetes-the-hard-way#66]
Hi,

I'm looking at the 05-kubernetes-worker page,  in the kubelet systemd file you have the --api-servers to list the 3 already configured but for the kube-proxy just the one master is set. Should the master bet set to some externally load balanced address or does it not matter ?

thanks

**Comment by wallyqs** [comment]
Think this relates to → https://github.com/kubernetes/kubernetes/issues/18174

**Comment by sgoodliff** [comment]
Thanks, 

I think I will use our hardware load balancer for kubelet & kube-proxy to connect to  api server(s) for now until a consistent solution across the components gets put in.

**Comment by kelseyhightower** [comment]
Fixed now. kube-proxy is configured to point to the loadbalancer sitting in front of the kubernetes master.
