### ISSUE TITLE
kube-proxy cannot connect - connection refused

### ISSUE THREAD

**Issue by gainax1** [kelseyhightower/kubernetes-the-hard-way#70]
Hi

I've followed steps 1-4 via the AWS steps and I'm seeing an error when I get to the last stage of 05

`sudo systemctl status kube-proxy --no-pager`

returns the following:

`Failed to list *api.Service: Get https://10.0.32.10:6443/api/v1/services?resourceVersion=0: dial tcp 10.0.32.10:6443: getsockopt: connection refused`

I've pretty much copied everything and changed the values to fit my AWS configuration.

I also see the same error when trying to connect the `kubelet`

`sudo systemctl status kubelet --no-pager`

`Failed to list *api.Service: Get https://10.0.32.10:6443/api/v1/services?resourceVersion=0: dial tcp 10.0.32.10:6443: getsockopt: connection refused`

**Comment by kelseyhightower** [comment]
@gainax1 Do you mind revisiting the firewall rules section for AWS again?

**Comment by gainax1** [comment]
@kelseyhightower just been through the firewall rules again, but unfortunately I'm seeing the same error

**Comment by kelseyhightower** [comment]
I've decided to focus on a single platform for this guide. I'm shifting focus to cover more configuration options such as RBAC, TLS bootstrapping, and add-ons. Too much time required to keep the IaaS bits in sync with AWS.

But everything should be working on GCP and the guide is now updated for Kubernetes 1.6
