### ISSUE TITLE
Cannot view api via browser - Unauthorized

### ISSUE THREAD

**Issue by gainax1** [kelseyhightower/kubernetes-the-hard-way#71]
Having gone through the tutorial step by step, when I list the cluster info `kubectl cluster-info`, I see the following:

```
Kubernetes master is running at https://kubernetes-xxxxxxxx.eu-west-1.elb.amazonaws.com:6443
```

Going to that URL, gives me a 401 Unauthorized.

I'm guessing it should either redirect me to the api list, or, ask for basic auth user/password?

**Comment by dylanmei** [comment]
Once everything is running, I have been able to run `kubectl proxy` on my local machine and then I could visit the dashboard via `localhost:8001` in my browser.

I believe this is some background into why it isn't very friendly out of the box: https://github.com/kubernetes/kubernetes/issues/7307

**Comment by gainax1** [comment]
@dylanmei, Thanks for that. Unfortunately, this returns the following:

    <h3>Unauthorized</h3>

**Comment by nelsonenzo** [comment]
I also get <h3>Unauthorized</h3>

**Comment by gregorskii** [comment]
I think this is actually due to the URL being used not being localhost. Use kubectl proxy to set it to a localhost address.

**Comment by nelsonenzo** [comment]
had to append "/ui"

**Comment by kelseyhightower** [comment]
Kube proxy is the way to go and before you can use the dashboard you'll have to deploy the dashboard add-on. This guide only provides instructions for the DNS add-on so you'll have to figure out how to install the dashboard the hard way.
