### ISSUE TITLE
Creating an ELB - pending state

### ISSUE THREAD

**Issue by gainax1** [kelseyhightower/kubernetes-the-hard-way#72]
Hi,

So, having followed the AWS tutorial, i have everything working, which is great!

The problem now, is that I'd like run my application on the workers, but, it seems that I cannot create the service load balancer

My service is something like the following:

    apiVersion: v1
    kind: Service
    metadata:
      name: cms
    spec:
      ports:
        - 
          name: http
          port: 80
          protocol: TCP
          targetPort: http
        - 
          name: https
          port: 443
          protocol: TCP
          targetPort: https  
      selector:
        name: cms
      type: LoadBalancer

When I check the service, I see the following:

    NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
    cms          10.32.0.74   <pending>     80/TCP,443/TCP   10m

I was hoping that the `EXTERNAL-IP` would be an AWS ELB, but its just stuck in this state

Any ideas?

**Comment by gainax1** [comment]
@kelseyhightower am I correct in thinking that:

   --cloud-provider= \

Should be:

    --cloud-provider=aws  \

to make it so my ELBs are created for my services?

**Comment by snoby** [comment]
+1 on this issue as well.

**Comment by snoby** [comment]
So far this is what I have discovered.  kube-api service on the controllers has to have an added config option "--cloud-provider=aws"  As does the kube-controller-manager.service.
[reference](https://github.com/coreos/coreos-kubernetes/issues/186)
ALSO
the Route and subnet needs to have a certain tag in them:
the route table I had to add the tag `KubernetesCluster=kubernetes`
The vpc has to have the tag: `KubernetesCluster=kubernetes`
Added the subnet to have the tag `KubernetesCluster=kubernetes`

I'm still having DNS issues, but that is probably something else:
`Could not create route 6d07b34f-8822-11e6-a312-12b65a4973d1 10.200.0.0/24 for node ip-10-240-0-20 after 453.249242ms: instance not found`

**Comment by craigwillis85** [comment]
@snoby, are you able to create the ELB though when you have `type: LoadBalancer` in your service?

**Comment by snoby** [comment]
NO.  The reason for this is that none of the "cloud-provider" flags were set to aws.  That being said after turning those options on and tagging everything with "KubernetesCluster=kubernetes".  I can;'t get the KUBE-DNS add-on to run.  Seems there is a problem with DNS resolution.

**Comment by craigwillis85** [comment]
Ok, I changed every `--cloud-provider` to be `--cloud-provider=aws` in the following files:

`kubelet.service`
`kube-apiserver.service`
`kube-controller-manager.service`

When I now create my service, with `type: LoadBalancer` I can see the ELB created

    NAME         CLUSTER-IP   EXTERNAL-IP        PORT(S)          AGE
    cms          10.32.0.39   a01a96b898aef...   80/TCP,443/TCP   5s
    kubernetes   10.32.0.1    <none>             443/TCP          46m

**Comment by craigwillis85** [comment]
@snoby, did you reload all of the daemons?

I did things like, 

- added the `--cloud-provider=aws` flag to the services above
- stopped each one e.g. (`sudo systemctl stop kubelet`)
- restarted the daemon (`sudo systemctl daemon-reload`)
- restarted the service e.g. (`sudo systemctl restart kubelet`)

This seemed to work for me

**Comment by snoby** [comment]
Yes, As a matter of fact I blew away everything and regenerated and had the exact same problem... I wonder if it has to do with the DHCP Options.  
@craigwillis85  - if you look at this document:

https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/design/aws_under_the_hood.md#tagging
Every AWS object needs to be tagged with "KubernetesCluster=kubernetes"

Finally (and this maybe where the problem is) i change the dhcp opt to use ec2.internal instead of the default because of this:
https://github.com/kubernetes/kubernetes/issues/11543

**Comment by gainax1** [comment]
I can now create the ELB following the above steps, so I'll close this

**Comment by fii** [comment]
@gainox Getting the same issue even after tagging the resources as per the above. Did you make any other changes ? Are you able to share exactly what you did?

Thanks

**Comment by tylux** [comment]
@craigwillis85's fix (adding --cloud-provider=aws to the various .service files worked for me)

**Comment by ksingh7** [comment]
@gainax1 @tylux @craigwillis85  ,  could not get this to work 

Have added --cloud-provider=aws thing in all unit files , daemon reload , restarted services 
Still does not works 

Any other advice

**Comment by ksingh7** [comment]
@gainax1 @tylux @craigwillis85 , don't bother about my last comment.  It started working after adding ``--cloud-provider=aws`` and **fixing  my typo**

Thanks for posting this solution.

**Comment by davidfeldi** [comment]
Hey @craigwillis85 
What do you mean by adding the ```--cloud-provider=aws``` to every service file?
is it the k8s service definition yml? or do you refer to something else?

Thanks.

**Comment by johnzheng1975** [comment]
I delete a k8s svc with elb, then after 1 min, I create it again
The svc is always pending, and, after 47 mins, the elb is showed finally.
What's wrong with it? A poor k8s/aws feature !!!
