### ISSUE TITLE
AWS tags

### ISSUE THREAD

**Issue by billyshambrook** [kelseyhightower/kubernetes-the-hard-way#74]
Hey @kelseyhightower, really awesome guide, deep dive and straight to the point!

Question, after reading the Kubernetes "AWS under the hood" doc, it says that you should apply a tag called "KubernetesCluster" to each AWS resource which Kubernetes then uses for filtering - https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/design/aws_under_the_hood.md#tagging

Does your setup avoid the need for this tag? or should we add it if we want more integration with AWS?

Thanks!

**Comment by kelseyhightower** [comment]
I've decided to focus on a single platform for this guide. I'm shifting focus to cover more configuration options such as RBAC, TLS bootstrapping, and add-ons. Too much time required to keep the IaaS bits in sync with AWS.
