### ISSUE TITLE
port-forward fails, socat not found

### ISSUE THREAD

**Issue by steveperry-53** [kelseyhightower/kubernetes-the-hard-way#78]
I followed all steps through the smoke test. I've tested several tasks/tutorials, and everything has been working. But when I tried a port forwarding exercise, I got this:

kubectl port-forward lobsters-2273945462-s4dr5 8080:3000
Forwarding from 127.0.0.1:8080 -> 3000
Forwarding from [::1]:8080 -> 3000
...
curl localhost:8080
...
E1003 15:41:30.093639   23963 portforward.go:327] an error occurred forwarding 8080 -> 3000: error forwarding port 3000 to pod lobsters-2273945462-s4dr5_default, uid : unable to do port forwarding: socat not found.

So I went to the worker node and installed socat.
Try again.
It works.

**Comment by kelseyhightower** [comment]
Lets get that installed.
