### ISSUE TITLE
instances failing checks in elb

### ISSUE THREAD

**Issue by craigwillis85** [kelseyhightower/kubernetes-the-hard-way#81]
I'm trying to run a smallish application on my workers.

Its a simple service and deployment, which i'm creating via `kubectl`

The service and deployment get created fine and it creates the elb fine (using `type: LoadBalancer`)

The problem is, I'm seeing at least one of my instances dropping from the elb with the following:

`Instance has failed at least the UnhealthyThreshold number of health checks consecutively`

I've ripped out the workers 3 times and re-built them and everytime I see this

Any ideas?

**Comment by craigwillis85** [comment]
Closing as this was user error

**Comment by adi658** [comment]
it would have been good if you had mentioned what the error was instead of just closing
