### ISSUE TITLE
Kube-proxy on workers are configured to single controller

### ISSUE THREAD

**Issue by mydharma** [kelseyhightower/kubernetes-the-hard-way#85]
I see that the kube-proxies on workers are configured to a single controller (controller0 in this case) as the api server. Is it by design or should we configure worker0 to controller0, worker1 to controller1 and worker2 to controller2?

Please clarify.

Thank you.

**Comment by KoeSystems** [comment]
@mydharma Having multiple controllers configured in kube-proxy is not supported (@justinsb confirm me that in the Slack channel) so if you want HA in that point you need to use a Load Balancer in front of the API, like the one that is created at the end of https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-kubernetes-controller.md

**Comment by kelseyhightower** [comment]
I'm now pointing kube-proxy at the loadbalancer that sits in front the kubernetes masters.
