### ISSUE TITLE
add kubernetes.default to kubernetes-csr.json hosts

### ISSUE THREAD

**Issue by noahdietz** [kelseyhightower/kubernetes-the-hard-way#86]
First, thank you for the awesome guide.

What do y'all think about adding the `kubernetes.default` service name to the list of hosts in  `kubernetes-csr.json`, [here](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/02-certificate-authority.md#set-the-kubernetes-public-address)?

I only ask because after completing this guide (and not cleaning everything up ;) ), I tried to deploy heapster (influxDB/grafana) and the cert we made and distributed here wouldn't work with `kubernetes.default`. It would be nice to have such well integrated components work out of the box during solo exploration.

Just a thought. Is it in scope of this tutorial? Thanks!

**Comment by kelseyhightower** [comment]
Sounds like a good idea to me.

**Comment by noahdietz** [comment]
PR is out! Let me know if there is something you would like changed about it. Thanks for the opportunity!
