### ISSUE TITLE
Container under pods can't connect to the internet

### ISSUE THREAD

**Issue by MeromTh** [kelseyhightower/kubernetes-the-hard-way#88]
I'm trying to run `apt-get` on your nginx smoke test pods.
Web in smoke test is working, but egress traffic is dead.
I think kube-dns are wrong because

```
kubectl exec busybox -- nslookup kubernetes.default
```

and I got

```
nslookup: can't resolve 'kubernetes.default'
Server:    10.32.0.10
Address 1: 10.32.0.10 kube-dns.kube-system.svc.cluster.local
```

Did I missed something?

**Comment by MeromTh** [comment]
FYI pure container, both ingress and egress, work fine.

**Comment by kelseyhightower** [comment]
Firewall rules have been added and we now ensure the right IP tables masquerade rules are in place.
