### ISSUE TITLE
vagrant version

### ISSUE THREAD

**Issue by ianmiell** [kelseyhightower/kubernetes-the-hard-way#91]
I'm trying to implement a vagrant version of this using an automated script:

https://github.com/ianmiell/shutit-k8s-the-hard-way/blob/master/shutit_k8s_the_hard_way.py#L18

everything appears to be working with the kube client etc, but my networking is not up to setting up the layer3 routing here:

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/07-network.md

as a result the services are not routing properly. For example, Vagrant appears to have a hard-coded ip: 10.0.2.15 for all the 8 machines I've set up (client, load_balancer (haproxy), controller0-2, worker0-2)

Is it possible you have some advice/experience, or can point me at someone who might be able to help? The end result would be a complete walkthrough runnable on a local machine.

Thanks.

**Comment by jomagam** [comment]
Do the controllers and workers you create have NAT networking ? Looks like you want to create an internal network. Read more at https://www.virtualbox.org/manual/ch06.html

**Comment by ianmiell** [comment]
Ah, should have updated: I eventually got it working, the steps are here:

https://github.com/ianmiell/shutit-k8s-the-hard-way

written up here, with video:

https://medium.com/@zwischenzugs/learn-kubernetes-the-hard-way-the-easy-and-cheap-way-6f82b665ccd9#.g48btm249

Having said that, I'm doing a similar thing now with openshift and need a way for internal DNS to work...
