### ISSUE TITLE
IAM role for controllers/workers

### ISSUE THREAD

**Issue by jomagam** [kelseyhightower/kubernetes-the-hard-way#98]
Not really an issue, but after going through the labs I do not see why the controllers and workers need an IAM role with RW access to EC2, ELB, ECR and Route53.

**Comment by kelseyhightower** [comment]
I've decided to focus on a single platform for this guide. I'm shifting focus to cover more configuration options such as RBAC, TLS bootstrapping, and add-ons. Too much time required to keep the IaaS bits in sync with AWS.
